### PR TITLE
take three | Tzula's super duper cool map update

### PR DESCRIPTION
**Pull request by AllCorruptingWyrm**
## About The Pull Request

The following PR adds as followed for the server and fixes a number of issues.
>Fixes the voids in the Keep reported by Elizabeths player
>Adds a number of anti grief and QoL features to the keep (Hand gets an gemerald ring and choker. There are now bar'd windows in the Stewards area.
>Removes secretly mapped in items that gave certain people an advantage 
>Adds anti gref measures to the Smithy.
>Adds the Grandmasters chambers to the Church & revamps part of it.
>Adds a feeding line for the poor. 
>Adjusts around the beggar spawn.
>Adds a new segment of Rockhill known as "The Estate" which is guarded by the town watch utilizing a shutter gate system.
>Adds a mini dungeon crypt that has one dungeon chest but is surrounded by running water. Gl.
>Added anti tunneling measures and things like that in the map. If you wanna break in, find the statue or tunnel in from the undersea.
> Some other things I might have forgotten to mention besides some mining ore spots.
> Also adds a new dungeon that advs can clear out and claim as home.

## Why It's Good For The Game

Mentioned above. 

## Pictures in game:

image
image
image
image
image
image

### CODE REVIEW

**Comment by AllCorruptingWyrm** [comment]
image
Was asked to try out this layout. Might be bad, we'll see how we feel about it I guess.

**Comment by AllCorruptingWyrm** [comment]
image
Meisters at the front of both of the shops too btw.

**Comment by DorfGuy1** [comment]
Wait, statues are doorways now?

**Comment by DorfGuy1** [comment]
When/if this is added, I'm curious who was getting advantages by doing mapping lol, seems kinda bad faith

**Comment by AllCorruptingWyrm** [comment]
> Wait, statues are doorways now?
Some statues teleport you, yeah.

**Comment by AllCorruptingWyrm** [comment]
image
image
made requested changes, gave beggar their area that Templars can patrol/lock for a safe nights sleep too.

**Comment by AllCorruptingWyrm** [comment]
the other doors arent reinforced. very close save.

**Comment by AllCorruptingWyrm** [comment]
yeah ok I give up I'll just atomize this PR

**Pull request closed without merging**
