### PR TITLE
Lizzay's Smithy Updoot

### PR DESCRIPTION
**Pull request by LilZizzle**
Just a complex, regal and new look to the horrid looking Smithy!

## About The Pull Request

Out with the old, in with the new. Reworks the Smithy look top to bottom, with a more realistic and cozy cottage feeling. Lots of QoL between the different member work zones and makes working together in a medieval shit storm seem slightly less bad!

image_2024-08-22_124020243
image_2024-08-22_124036004
image_2024-08-22_124057513

### CODE REVIEW

**Comment by LilZizzle** [comment]
I'm new to Mapping and PRs, so if something is off or wrong please lmk!

**Comment by Z0w0plankton** [comment]
Personally, while I think this LOOKS like a nice smithy, I think i tmight be really really annoying to work with.  Firstly, the open smith area invites anyone to go and just USE it. Considering how impatient some players are with smiths (to the point they break in and work the smith themselves if you leave for a few minutes, sometimes), I feel like this migth cause problems. This is further compounded by the fact that you either need to leave the material outside, for easy acces, or leave the door unlocked so you can walk back and forth quickly. Both of these things invite thefts and people doing things themselves. And from a more practical standpoint, its far to cramped for 2-4 people to work in. Most of these halls and doors are one tile wide, it would be a nightmare with an armorer, weaponsmith, and two apprentices.  A very nice looking smith, but I think it has massive practical problems. I dont see how this could work properly with how it is.

**Comment by Ruediger4** [comment]
I do agree with @Z0w0plankton regarding the space: too tight for 2 smiths + 2 apprentices, not even talking about masons/miners

It fucks, it looks nice, don't get it wrong, but knowing how players are here (and the cases where someone broke into a smithy because he didn't get immediate attention), an open/easy access just welcomes trouble which

ironically

can bring RP by having smiths hire mercs to keep people at bay

So like, pros: Looks pretty, and possibility of RPing around one of its flaws

Cons: TIGHT AS FUCK, said flaw (easy access to the furnace/anvil means people will try to self-serve), practically difficult to make it work

**Comment by LilZizzle** [comment]
Thanks for the feedback guys, I'll work on this again when I have the opportunity.

**Comment by codyman765** [comment]
So- Tossing some feedback into here since I truly don't know where to put it anymore with how this has been tossed around into multiple PR's, Thought it was not going to be merged until it was changed again and had feedback. But Like everyone else has said, it is nice looking, but the functionality is **NOT** there at all. With the changes made with #411 such as the immovable chest in a high traffic area, causing basically a grid lock whenever some one comes and goes. Between the chest and the grindwheel when someone comes in with a cart they lock the whole thing up and its a pain to go around everything to lock the door. The invisible walls are great until I noticed that people can now throw things at the smiths now via over the fences, pair that with how the smiths dont wear any armor of any kind. Nothing really is stopping anyone from throwing a stone at their head and watching them bleed out.  The smithy now has multiple doors all over, which isnt a big issue by itself, just gets confusing with the two sets of keys. 

Another thing I noticed is that the dirt floor out where the work area is will slow you down noticeably, pair that with how **oddly** far it is from the front desk and the amount of walking needed, makes it slow down the flow massively, causing orders to take even longer and in turn upsetting players waiting. And thats not even factoring in the slow down that will be experienced by the 1x1 paths smithies will have to walk through when there are more then one of them. Add in having the armoursmith, weaponsmith and the two apprentices, you get a full on grid lock and cant do anything. Most of the smithy work is done order via order and not stocking the racks due to the sheer number of items that can be smithed and the demand of the ingots

We also lost alot of the QOL love the old shop got from a prior PR #360 which helped with the work flow and speed of the smithy. Such as more iron, steel and sacks with some crackers. But the previous smith also had a meister, spare tools for each smith, Three lampterns for the masons and smiths. Along with lacking a torch right next to the furnaces for easy and quick relights.

A smaller note is now the lack of beds and rooms, both apprentices no longer have rooms and there is one bed im assuming the masons can fight over in the _barn_ section of the building. Over all **alot** of space was lost coming to this version of the smithy.

Again, the building itself looks very nice, but I just dont think its fit to be the powerhouse of smithing for the whole town at its size. I think it would look wonderful on the outskirts somewhere where a townie smith can claim it, or anyone who is so inclined. With the grand furnace removed at least. I would honestly love to play with it as a townie if it was in a more low traffic area that lets the tight confines of it not be as much of an issue with less massive lines of people with orders due to it not being the **main** smithy.

Trying it out for a round as a smith (round ID: Halberd406-17.14.51) alot of the feed back from the smith and players who frequently play in game as a smith is mainly negative with how _cramped_ the whole thing is. Alot of them just dont see it working and lack a desire to work around its flaws ontop of the demanding work as a smith, with a few of them saying they would look towards transiting to a different class even causing the server to loose its frequent smithy workers, which is frankly already small in size as alot of people dont have the desire to play smith with how much demand it gets.

Tagging a few people since this PR is closed- and once again I am not sure where to put this feedback 
@Tree445 @LilZizzle

**Pull request closed without merging**
