### PR TITLE
Allows Priests to be any Divine Pantheon of their chosing

### PR DESCRIPTION
**Pull request by AllCorruptingWyrm**
## About The Pull Request

Allows a Priest to be whatever God they want.

## Why It's Good For The Game

Because for some reason we needed this arbitrary change. Eora only, ???

### CODE REVIEW

**Comment by AllCorruptingWyrm** [comment]
> It was like this before, then swiftly changed because the priest needs to be able to giga heal someone or the round doesn't work.

They had Eora so this argument doesn't work. In fact, getting diagnose as a priest if chosing Pestra is even more effective!

**Comment by AllCorruptingWyrm** [comment]
or just give priest the revival spell.

**Comment by Decoy1240** [comment]
I agree with you but not every god has T2 spells let alone T4 so you should only allow those with T4 spells to be priest and as more get T4 spells more can be added

**Comment by AllCorruptingWyrm** [comment]
i'll just give them miracle & revival then

**Comment by Decoy1240** [comment]
> i'll just give them miracle & revival then

They should get unique things they have different personalities and aspects it just is really boring to play them all as the same

**Comment by AllCorruptingWyrm** [comment]
I'm going to shelve this into https://github.com/Tree445/Hearthstone/pull/536

**Pull request closed without merging**
