### PR TITLE
reversed rotman chance and no ghost on zombie, increased pq reward for revive etc.

### PR DESCRIPTION
**Pull request by EaglePhntm**
## About The Pull Request
reversed rotman chance from 5% to not be rotman to 95%, hopefully no more force ghosting on zombie (didnt test lazy) increased pq reward for reviving and burying so it actually matters and may work better on low pop, maybe i should have even given it more pq reward.

## Why It's Good For The Game
more continuity of characters without being rotmans, but still a small odd of being one, no more force ghosting because that is damn boring also prevents you from ever seeing anyone that may possibly take you to being cured or so. Finally gives more reward for burying and reviving, helps low pop and makes effort worth it more.

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
the reason why ppl aren't being buried is actually because of a lack of shovels, not pq. you'd solve this issue by mapping in a shovel in the graveyard

we also do NOT have pq set up yet.

**Comment by EaglePhntm** [comment]
you missed the point of pq chance, the fact we got extremely low pop it would not matter at all, and what, Thought we run nearly same code as ratwood, which has pq by commends and this sorta thing for the most part.

**Comment by bearrrrrrrr** [comment]
> you missed the point of pq change, the fact we got extremely low pop it would not matter at all, and what, Thought we run nearly same code as ratwood, which has pq by commends and this sorta thing for the most part.

db machine broke and pq dont do nuffin on purpose

this rly isnt needed, zombie time PR and a spare shovel are more than enough to fix this i think but it doesnt really matter ig

the ghost thing is good though

**Comment by EaglePhntm** [comment]
> > you missed the point of pq change, the fact we got extremely low pop it would not matter at all, and what, Thought we run nearly same code as ratwood, which has pq by commends and this sorta thing for the most part.
> 
> db machine broke and pq dont do nuffin on purpose. ~zombie time PR and a spare shovel are more than enough to fix this i think but it doesnt really matter ig. the ghost thing is good though~
> 
> after stinking on it it's good ig- and PQ's appear to be saved now

zombie pr dont have to do anything with this, but yeah, you can bury and revive zombies too.

**Pull request merged**
