### PR TITLE
[DRAFT] "I ALREADY TORTURE MYSELF" and Why I love Psydon

### PR DESCRIPTION
**Pull request by AllCorruptingWyrm**
## About The Pull Request

After playing Inquisitor and hearing feedback from a couple INKVD players. I thought I'd do this. This PR gives more "inquisition" coded skills to well, the Inquisition. It goes away with their innate crafting and other support role stuff to give more use to craftsmen. The Inquisitor gets a good knife skill and dodge expert to reflect them being a part of the rogue archetype. The Inquisitor also gets **two** confessors to act like henchmen for the Inquisitor. This PR also nerfs Grandmaster by removing their sflail given how powerful blunt damage is in the game and gives Priest the acolyte skills and fitting crosses.

## Why It's Good For The Game

This should drive home the differences between the sects and members of the Church more thoroughly and ensure there aren't any issues of overlap. Also Inquisitor finally gets armor because people think they are unstoppable lol.

### CODE REVIEW

**Comment by AllCorruptingWyrm** [comment]
This also brings the lore of the Inquisition more in line for what the server has (No mentions of a queen, etc)

**Comment by Troopermoores** [comment]
Good change I agree with nerfing flail skill.

**Comment by AllCorruptingWyrm** [comment]
image
erhm... fixed LOL.

**Comment by AllCorruptingWyrm** [comment]
Changed title to discuss the status of Inquisitor and authority/potential lore.

**Comment by worriedconcentrate** [comment]
The final edit of the inquisitor stats does seem a tad high BUT it is a one of role and the church will literally never back you, so that should be fine. We just need some medium armor pants and it's a decently solid role.

**Comment by AllCorruptingWyrm** [comment]
i'll shelve this for now and then do my big balance overhaul.

**Pull request closed without merging**
