### PR TITLE
Knight removal

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Reduces knight's spawn/late-joinable slots to zero.

## Why It's Good For The Game

Knight currently cannot exist in this gameplay culture. It's a clear frag-bait role. 

Different from Knight nerf PR. 

The less garrison roles the better, we're already seeing places using garrison as an attractive role due to their amazing access to weapons and equipment with rarely any oversight from a guard captain.

### CODE REVIEW

**Comment by EaglePhntm** [comment]
just readd pq req to knight, ezpz

**Comment by EaglePhntm** [comment]
> > just readd pq req to knight, ezpz
> 
> We both know that isn't happening. I'd rather axe this role or if someone has job code knowledge, to actually fully transform this into a body guard role. Like baroness guard in lyohaweb 2.
> 
> I'm sick of the justification but it's MUH elite soldier so it needs hilariously broken stats/equipment.

hey baroness guard is a pretty good idea with baroness bodyguard, with just one role slot, you can just copy knight file and modify it to get that effect likely if you wanted, need to also make spawns for those and add to job list though.

**Comment by coffeecoffeecoffee** [comment]
This is a clear and blatant textbook example of a salt PR. What a horrible idea.

**Comment by Stutternov** [comment]
Was more in favor of the Royal guard PR with 3 slots and just reducing guard slots.

While I agree theres an issue with roles theres also the issue that adventures can have equal stats to guards and tribe is basically a thing with tons of slots + antags.

Best to not flat remove but replace with something.

**Comment by Stutternov** [comment]
> I only really wish to remove this role and reconfigure manor guard into the new knights/royal-guard. Because it's just another role ontop of the very many garrison roles.
> 
> 
> 
> Currently there is 8 MAAs, which are all very good in skills. Knight is entirely un-needed and there is various design issues.
> 
> 
> 
> 

It should be done in one PR then rather than separate as it just looks as removal with no rework other than a 'plan' to do so in the future; which doesn't feel great to vouch for given it's unclear if/when it'll happen.

**Comment by LynxSolstice** [comment]
> > just readd pq req to knight, ezpz
> 
> We both know that isn't happening. I'd rather axe this role or if someone has job code knowledge, to actually fully transform this into a body guard role. Like baroness guard in lyohaweb 2.
> 
> I'm sick of the justification but it's MUH elite soldier so it needs hilariously broken stats/equipment.

This literally happened, there IS a PQ requirement for Knight now. This PR doesn't need to be up anymore imo, since the "impossible" happened.

**Comment by Wesreidau** [comment]
Knight is a completely different roleplaying experience and character archetype. I think this cannot be overstated as something important in a roleplaying game.

I can expect a knight to have conflicted interests in a matter of honor and loyalty to the king if he feels his family name is going to be forever tarnished by putting half the town to the sword under the orders of a mad king, or the stigma of betrayal if he kills said mad king. There is an internal conflict and however you think they should act likely depends on if you're a villager or a courtier writing your salt adminhelp after. How the knight acts is up to the character.

A royal bodyguard is just a goon you're paying to be very, very loyal. I do not see them having this concern.

I also question if watchmen can be reliable protectors of the crown since often times they'll side with the townsmen over the king when the king goes crazy. Facing only two bodyguards with no actual soldiers to man the walls, what is a king supposed to do?

You are categorizing bog guard and watchmen into the same rigorous command structure we'd expect of SS13 security, but here they are distinctly different. Watchmen shouldn't be in the castle. Bog guard shouldn't be in the town. Men at Arms should be going where the king commands them to hunt down the werewolf or kick in the church door over getting excommunicated. They have separate leaders and separate responsibilities, even if they all nominally swear to the King, and the number of bog rebellions and even town rebellions prove it.

**Pull request closed without merging**
