### PR TITLE
No More Bad Name

### PR DESCRIPTION
**Pull request by Stutternov**
## About The Pull Request

Was requested by coders to make this; was an easy port since it was done elsewhere.

Re-names Shylock given it's a really strange reference. At best, poor taste, at worst - well, there was Swastika sprites/code so.. 

Renames it to a fitting name and corrects anyone using the old name in game to the new one.

## Why It's Good For The Game

People made complaints how it feels weird to borderline anti-Semitic given the term of Shylock, even if it derives from a Shakespearian play (which is controversial normally anyway). This hopefully fixes that without a hassle for players.

### CODE REVIEW

**Comment by Stutternov** [comment]
Note for future PRs: The accent_universal.json technically has slurs in it that violates Github ToS; this should be done back-end and not live on Github possibly to avoid issues with Github ToS and taking down of repos.

**Comment by Stutternov** [comment]
> Similarly, the Blood of Giza is purely about copying lifeweb's special which goes like, "You have the blood of ancient Semites, you can now see prices."

Sir there were swasticas in game across multiple areas, Open anti-semitism in old universal language correct code, and old lore for saytr people was they were half goat slavers who were basically Muslim.

Codebase has its curses, it could be a coincidence but it gets harder to believe each time. It's best to move away from and has generated complaints and has been requested by staff and players to change.

**Comment by faaaay** [comment]
> I believe the name was in reference to less about the story of Shylock being Jewish and more the fact that the shylock implants you in your finger therefore taking a pound of flesh for future debts.
> 
> Historically, bankers were Jewish. It's literally impossible to separate this. This is why there is plenty of anti-Semite canards about them controlling money and were viewed with distrust.

Bro
Is this the hill you want to die on? You really, really want to keep this?
"Oh technically it's not explicitly anti-semitic, it's just a reference to an anti-semitic caricature"
There is nothing lost by renaming this.

> Similarly, the Blood of Giza is purely about copying lifeweb's special which goes like, "You have the blood of ancient Semites, you can now see prices."

You see how that is anti-semitic, right? Why would we want to copy that?

**Comment by faaaay** [comment]
Also, a lot of bankers were jewish because christians and muslims weren't allowed to lend money and jews were discriminated against in other fields - sometimes, they couldn't own land or even farm on someone else's land. A lot of bankers were jewish _because of anti-semitism_.

**Comment by Stutternov** [comment]
> Don't stand here and say I hate the sematic people when it's very obvious that during the time period that the play was set, that it was going to be a Jewish banker.

No one called you anti-sematic, the question was 'why would we want this here'. 

The play itself is an issue debated still irl, the codebase had constant references in it; be it due to actual beliefs or just being edgy, I'm unsure. And, as someone who lives in an area where this term is still in use, half the usages of the term in the modern day is anti-sematic to the point I've heard it directly used as an insult. (Mostly by old Irish-Americans or Italian-Americans.) 

It's not worth the baggage when the server is attempting to be a new setting anyway.

**Pull request merged**
