### PR TITLE
Update rogue.dm

### PR DESCRIPTION
**Pull request by Cecily-C-Catherine**
Removes patron restrictions for rogues after being asked for a lot

## About The Pull Request
Removes patron restrictions for rogues after being asked for a lot

## Why It's Good For The Game
Allows some more player freedom other than "you will be the greedy man," and plenty of people have asked for it by now

### CODE REVIEW

**Comment by eeshaa1** [comment]
> I never really understood the player freedom argument. This is an open question to please explain it.

Players have more freedom to play who they want now that they can be a rogue of any religion.

**Comment by eeshaa1** [comment]
> > > I never really understood the player freedom argument. This is an open question to please explain it.
> > 
> > 
> > Players have more freedom to play who they want now that they can be a rogue of any religion.
> 
> This has explained nothing and said nothing.

What specifically do you want explained?

**Comment by eeshaa1** [comment]
> > > > > I never really understood the player freedom argument. This is an open question to please explain it.
> > > > 
> > > > 
> > > > Players have more freedom to play who they want now that they can be a rogue of any religion.
> > > 
> > > 
> > > This has explained nothing and said nothing.
> > 
> > 
> > What specifically do you want explained?
> 
> How does just allowing more options to be taken actually give players freedom? I don't really see how it's freedom beyond the fact you can be like, a Psydonian rogue? What is it really.

You are no longer restricted to being a communist, lol. You get to pick whatever religion you want and can thus have more freedom with the type of character your rogue is.

**Comment by Stutternov** [comment]
You could always be whatever religion (besides Psydon, ironically). It's just your main patron given those are the only two who endorse stealing.

Patron =/= religion, it means you patron god of many.

**Comment by eeshaa1** [comment]
> > You could always be whatever religion (besides Psydon, ironically). It's just your main patron given those are the only two who endorse stealing.
> > Patron =/= religion, it means you patron god of many.
> 
> I believe the restriction code-block just says something like, "I was accepted by X patron in my younger ages and therefore I became accustomed to Y Patron."

how does this benefit the game?

**Comment by eeshaa1** [comment]
Also you got mad and muted me in the Discord LOL so i think this conversation is over. Tragic!

**Comment by eeshaa1** [comment]
> nigga what
> 
> Actual schizo retard

OMG now youre posting weird things please state relevance to the conversation NOW

**Comment by EaglePhntm** [comment]
nice

**Comment by Tree445** [comment]
> You could always be whatever religion (besides Psydon, ironically). It's just your main patron given those are the only two who endorse stealing.
> 
> Patron =/= religion, it means your patron god of many. This function exists to highlight that going into a life of such these are the gods who you'd be endorsed by and paying tribute especially to; though you are still worshiping other gods. (Unless you are a heretic.)
> 
> Religion here, besides the Psydon one weirdly, is polytheistic.

Exactly what I usually go by. It's also kinda a pain for new players to have to choose from the entire list instead of having a default patron for their role, that serves as an introduction for them. If you want to RP worshiping someone else you can, but this is most likely always going to be your patron as it aligns the most with your role's lifestyle.

**Comment by Wesreidau** [comment]
Matthios has been reworked and is no longer communist.

There is no reason why you cannot be a Matthios-worshipping rogue. Or an Abyssor worshipping rogue. Or a Malum worshipping rogue. Or a Graggar worshipping rogue. Rogues aren't even required to steal, you might be a duelist who worships Baotha. Who cares.

All that makes sense is possibly preventing certain gods in the good pantheon from being your patron, but then we presume said rogue is playing an evil character and not some chaotic good archetype. You can be an Astratan duelist going around putting a silver dagger in nite creachurs as a discount witch-hunter.

Let people do what they want.

**Comment by eeshaa1** [comment]
> > > nigga what
> > > Actual schizo retard
> > 
> > 
> > OMG now youre posting weird things please state relevance to the conversation NOW
> 
> image
> 
> Source? Studies?

This got me permabanned from the Discord haha so I guess you bested me either way. Sorry for freaking out.

**Comment by eeshaa1** [comment]
> You could always be whatever religion (besides Psydon, ironically). It's just your main patron given those are the only two who endorse stealing.
> 
> Patron =/= religion, it means your patron god of many. This function exists to highlight that going into a life of such these are the gods who you'd be endorsed by and paying tribute especially to; though you are still worshiping other gods. (Unless you are a heretic.)
> 
> Religion here, besides the Psydon one weirdly, is polytheistic.

But, within the mechanics, when I "pray" to my God, I'm praying to an admin, no? And that admin is roleplaying the God that the game /made/ me follow by joining, which I'm sure can cause some issues and objectively limit your options regarding roleplay.

**Pull request closed without merging**
