### PR TITLE
Revert "No More Bad Name"

### PR DESCRIPTION
**Pull request by Jeff-Dome**
Reverts Tree445/Hearthstone#201

Someone asked for it idc

### CODE REVIEW

**Comment by YuiY1997** [comment]
please rename the SHYLOCK to MORSHU

**Comment by Wesreidau** [comment]
Against reverting back to the shylock. The name makes no sense outside of one specific context, and we seem to be moving away from that context.

**Comment by faaaay** [comment]
> > Why though.
> 
> Someone wanted it revert. Idc on the matter

Weren't you very vocally against #201?

**Comment by faaaay** [comment]
> I don't think you read the entire thing. Moron. I agreed with Rebel's points in the end but sure.

That's a really unnecessarily rude way to talk to other people. I hope you consider the way you interact with others.
I thought it was relevant to mention.

**Comment by coffeecoffeecoffee** [comment]
*wiggles my finger at u & lectures*
I believe the biggest thing was that the way it was could hypothetically, albeit by a bit of a stretch, get the github taken down or something. The shylock DOES NOT implant something in your finger - I think it's supposed to be a magic device that identifies you by blood, so it needs a sample?

**Pull request closed without merging**
