### PR TITLE
Revert "Accents [REUPLOAD AGAIN]"

### PR DESCRIPTION
**Pull request by DeltaFire15**
Reverts Tree445/Hearthstone#236

Untested PR. Quite literally has accent adjustment code in your prefs twice and does not make use of savefile updating to ensure it definitely works for existing characters.
Also does not integrate into the savefile AT ALL, which is the entire point of using character prefs. Origin PR needs a major redo.

### CODE REVIEW

**Comment by faaaay** [comment]
We really need more defined, thorough checks for PRs.

**Comment by DeltaFire15** [comment]
Gupdate: I actually missed the most obvious issue:
The preference, meant to be between rounds, does not actually have any implementation into the savefile.

Sometimes the one about not seeing a tree in a forest really is true.

**Comment by DeltaFire15** [comment]
> We really need more defined, thorough checks for PRs.

Unfortunately the only effective things for this are
a) Compile test which makes sure your main doesn't flat-out brick (no idea why it still is disabled).
b) Further tests to make sure nothing egrocious that you expect to brick bricks.
and most importantly:
c) Have a maintainer that actually knows code read it and scream at people (this one is the main thing that catches issues across codebases, besides the classic "the user is the tester")
[Bonus: d) Testing things on local and rereading one's own code to make sure there's no weird stuff.]

**Comment by Stutternov** [comment]
> a) Compile test which makes sure your main doesn't flat-out brick (no idea why it is still disabled).

Meant to tell host how to but I forgot to, they don't know how to turn on checkers (should be in settings).

> [Bonus: d) Testing things on local and rereading one's own code to make sure there's no weird stuff.]

Unthinkable...... never done before..... this will NEVER be standard practice......

**Comment by Gardelin013** [comment]
Yeah, it should be reverted for the time being. I tested it on my local, but was too hasty it seems.

**Comment by DeltaFire15** [comment]
I don't feel like keeping this in my browser tabs if all I'm doing is fix merge conflicts for something apparently not considered relevant.

**Pull request closed without merging**
