### PR TITLE
Adventurer/Merc Changes - v2

### PR DESCRIPTION
**Pull request by Stutternov**
## About The Pull Request

Does what I was doing before but Lynx did the work and my PR closed itself, annoyingly. So, I've done similar again with some changes. Similar to prior one: https://github.com/Tree445/Hearthstone/pull/209

Tl;dr list:
- Clerics brought down to T2 spells upon staff request, again. No more heavy armor training. Nature cleric now has dodge expert and bonus speed slightly, since.. he starts with worse light-armor for some reason? So, here, different play-style. Others still get medium training.
- Bard lost medium armor training; you're a musician. Idk why you have this.
- Paladin is now limited to 5 slots, but you start with half-plate now instead of only chain. Also gave them no more rng climbing skill, you get 3 base now. Also - gave tower shield instead of metal one. Metal one is legit best in game, it is NOT equal to the 50% chance for wood.
- Monk gained 1 endurance for 1 strength; he already has master tier unarmed which is massive - and level 4 in wrestling, which scales on strength. Just take the mildly better stamina.
- No more medium armor on rouge, also made the duelist class ACTUALLY not just Rogue+ - rebalanced to be different, still good class especially comparing to other adventurers with their dodge skill. (Also, deleted assassin type - because unplayable AND we have assassin as its own class already; why a rogue subtype assassin? It's identical.)
- Warrior is basically unchanged, just got rid of his random rng combat skills. You're a proper 'jack of all, master on none'.
- Steppesman now has crit resistance; he was weak before given his speed isn't through-the-roof and dodge expert with no starting armor was bad. Also, gave him leather pants and a gambeson so he has at LEAST basic armor.
- Desert Rider now has doge expert due to their speed stat and to set them apart as not just a 'lesser-Grenzehoft'

## Why It's Good For The Game

Overall these were part of changes I made prior in the last adventurer PR with some mild changes, some of these changes were direct asked for - such as mercenary change, part of the cleric changes,

### CODE REVIEW

**Comment by Ryan-Blackwell** [comment]
Quick note on the desert rider getting dodge master - Desert Rider still has a net +12 to their stats compared to grenzelhoft's +7 and steppe's +6, so I'd argue against buffing them with anything new unless you're also factoring in a rebalance for their +2 str / +3 end / +2 con / +2 per / +3 spd

**Comment by faaaay** [comment]
I agree with altering Desert Rider stats a bit, but other than that, good changes. Cleric needs this. Steppesman buffs are also welcome.

**Comment by Stutternov** [comment]
> Quick note on the desert rider getting dodge master - Desert Rider still has a net +12 to their stats compared to grenzelhoft's +7 and steppe's +6, so I'd argue against buffing them with anything new unless you're also factoring in a rebalance for their +2 str / +3 end / +2 con / +2 per / +3 spd

Done, standardized it to the same points as Grenzel (strength and speed worth 'two' points for each level, other stats worth one) so all total to ~9 stat bonus.

**Comment by Kotbulle** [comment]
Behold, the one and only time I will ever comment on a PR.

I can't agree with the cleric changes, at least for spells. You already have to sit somewhere for 20-30 minutes depending on what flavor of cleric you're playing to even unlock them, longer if you're interrupted by other things happening. I understand people may ask for it because the proper Church is underplayed, but this is NOT the way to fix that. All it does really is remove more people from being able to revive/cure rot when there's already very little and, being honest, most people aren't going to suddenly start playing Church because cleric was nerfed. War cleric, I can understand being changed a bit, and I like the armor change admittedly, but the spells should stay. Having more people that can cure rot or revive really isn't a bad thing.

It's the main reason people stopped playing Paladin (myself included.) Limiting miracles at all just sucks from a gameplay standpoint.
Aside from that:
Bard losing medium armor is probably a good change but I rarely see bards.
Paladins getting Cleric's old half-plate isn't going to make them any more enticing to play, nor is a shield considering all of these can just be forged.

**Pull request merged**
