### PR TITLE
New Potions - Fortitude, Swiftness, Intellect, Virility, Paralysis

### PR DESCRIPTION
**Pull request by Lynx22330**
## About The Pull Request

Introduces 5 new potions. Time is assuming that REAGENTS_METABOLISM occurs every second. 

3 stat potions.             - ~160 seconds each
1 immobilizing potion. - ~9 seconds per 3 units (totaling to ~45 seconds with a full bottle)
1 erotic potion.            - ~300 seconds total.

The stat potions are as follows, in order of difficulty descending from most difficult, to least difficult:

Paralysis Potion: Crafted with (2 ash, 1 Dorpel, and 1 Beespider Fang at difficulty 4 crafting), paralyzes anyone who consumes the potion. Note - The potion is intentionally designed to only be crafted into 3 UNITS OF PARALYSIS, meaning you must work really hard to get a potion to paralyze someone for longer than 10 seconds. Yes, the paralysis is near instant. (Applies 200 ticks of stun, if I am reading the Paralysis code correctly, intended for if someone consumes it and instantly ticks metabolism, giving people enough time to react.)

Fortitude Potion: Crafted with (1 Ash, 1 Toper, and 1 Volf Head at difficulty 3 crafting), grants the consumer 1 STR and 3 CON for the duration. Beef up, buttercup!

Virility Potion: Crafted with (1 Eora's Bud [peaceflower], 5 Breastmilk, 1 Ash at difficulty 2 crafting), grants the consumer the ability to have infinite orgasms during its duration. When the duration ends, they are immediately spent and need to recharge their batteries, so to speak.   

Swiftness Potion: Crafted with (2 Feathers, 1 Ash, and 2 Antlers at difficulty 1 crafting), grants the consumer 1 DEX and 3 SPD for the duration. Swifter than arrow!

Intellect Potion: Crafted with (1 Apple, 1 Egg, 1 Raw Steak, 1 Ash at difficulty 0 crafting), grants the consumer 2 INT and 2 PER for the duration. Intended to be the potion you use to level up Alchemy since there is currently no way to grind Alchemy. 

## Why It's Good For The Game

Adds potions! The paralysis potion is going to be up for debate on if it should stay or not, as it is a concern of mine when adding it into this PR in the first place. I'd need to see some in-game interaction with it and player feedback in the OOC or here on the PR for better input. 

The other potions are simply stat improvements that primarily helps non-melee users, as most non-melee users are typically the ones crafting these ingredients. It does slightly buff melee users, but I intended it to be minor as to not make someone a total threat by having +3 strength and chopping your arm off or your head in one swing just because of that. 

On top of that, this is to improve the magic and alchemy experience!!! There's barely any potions and nearly NO REASON to leave the town of Rockhill when doing potion crafting, causing the teaching experience with the Court Magician and Apprentice to grow VERY stale! This is intended to get people to go out of Rockhill, possibly into the bog, and explore the map. This benefits the Court Magician by giving them a reason to go outside of the keep for an actual cause by gathering Alchemy supplies and makes it so that the Scrying Orb is a much more valuable item and possibly considered to be left at the tower and left open to being stolen. This is beneficial to the Apprentice, as this allows them to learn the surrounding area and get taught the local city, some basic survival skills, and so on and so forth, great for new players and simultaneously great for roleplay as well!

Finally, this helps everyone. It gives new items to cycle into the economy to flow mammon around by making ANTLERS become a viable source of income with people who are collecting alchemy supplies, gives Beespiders a use outside of silk, and provides a new kind of playstyle outside of simply being a 'mage' who can cast fireballs!

I do hope you consider this addition into the game! It should all be working correctly, however if it isn't please smash me over the head with not one, but two planks. Thank you!

### CODE REVIEW

**Comment by Lynx22330** [comment]
I messed up a little in the last PR when I force pushed, didn't realize it would prevent me from re-opening the PR !

**Comment by Ephemeralis** [comment]
The intellect potion looks a little overtuned as it stands. 5 int/5 per at 0 craftdiff for some really fairly trivial farming reagents is pretty crazy - I'd suggest raising it to 2 craftdiff (maybe even 3) and substituting the egg and apple for bones (possibly ground bones?) and something like westleach leaf respectively.

**Comment by Lynx22330** [comment]
> The intellect potion looks a little overtuned as it stands. 5 int/5 per at 0 craftdiff for some really fairly trivial farming reagents is pretty crazy - I'd suggest raising it to 2 craftdiff (maybe even 3) and substituting the egg and apple for bones (possibly ground bones?) and something like westleach leaf respectively.

Fair! I was actually thinking about finding a use for bones during this but I felt like it wouldn't make sense for intellect potion. The main reason I did 5 was because it was supposed to be for XP grinding and whatnot. I'll drop it down to 2:4 respectively as I had oversighted the fact that wizards/magical folk already have really high base INT.

As for the bone idea, I shall incorporate it! Gives the bones more use within Rockhill rather than just Antlers alone!

The craftdiff however I want it to remain the same so people can learn alchemy. There's currently no alchemy item with craft diff 0 as far as I'm aware. 

Let's try... 1 apple, 2 bones, 1 raw steak?

AS for the westleach leaf, I don't know what I want to do with it. I was thinking of originally adding it to the potion of summoning idea I had earlier, but I didn't go through with it 100% as it seemed like more of a hell to balance instead of simply letting people fight with their bodies. . . Spamming summon potions... Would be a total mess.

**Comment by faaaay** [comment]
AFAIK, intellect and perception are some of the less used stats, right? 5/5 is good, but not necessarily disastrous. Bones and leaf seem like an appropriate recipe, though.

**Comment by Lynx22330** [comment]
Yeah I was thinking 5/5 but they're right with it being overtuned for a start. Can definitely just start small before we start bumping values up. It's only fair. 

The thing about Westleach leaf is that it's a non-renewable item once you begin hitting the later stages of the game, and it's really easy for it to start rotting. ... actually thats a lie i just remembered you can grow it. Well there, that was my ORIGINAL reason of not implementing it lol

Hmm... I can move steak off and do Westleach Leaf. I didn't use it originally as I was trying to keep it easy for everyone to start alchemy. ((I forgot that you can grow Westleach leaf! I had impressions you couldn't. lol ))

**Comment by DeltaFire15** [comment]
Life() processes every two seconds (+- lag)

Also wouldn't the total duration of the stat buff be more like 100 seconds even if it ticked at 1/s? (45, *2 because metabolism, + 10 seconds at the end from lingering status effect.)

Additionally, wouldn't it be more useful to have the reagent within the stat potions more in the single-sip range and have the buff status handle things instead so you could not microdose it for each seperate 10-second status cycle (~250 seconds effective time if used that way)?

**Comment by Lynx22330** [comment]
> Life() processes every two seconds (+- lag)
> 
> Also wouldn't the total duration of the stat buff be more like 100 seconds even if Life() ticked at 1/s? (45, *2 because metabolism, + 10 seconds at the end from lingering status effect.), assuming "sipping the entire potion in one tick".
> 
> Additionally, wouldn't it be more useful to have the reagent amount within the stat potions more in the single-sip range and have the buff status handle things instead so you could not microdose it for each seperate 10-second status cycle (~250 seconds effective time if used that way, currently, even more if diluding)?

You're not wrong about Dilution... I had wanted to try and keep parity alongside the other potions for it to be utilize. But. I will say. Allowing it to be diluded to increase its duration (if that does even work? I don't know how that mechanically works?) sounds like adding Redstone into a potion in MC and seeing its duration increase, so sort of like making Alchemy have a little more depth...  

I could make them all be more like a single sip to grant you the buff with the status effect handler.

But. If someone is mini-sipping the potion to extend its duration, I cannot see how that would be ideal or annoying. 
The buff applied on you is immediately removed when you metabolize it entirely. 

Thank you about telling me the Life() process, I didn't read too deep into the reagent metabolism. Having each potion for 160 seconds and 300 seconds for Virility doesn't sound bad, however paralysis would seem to be needing some very needed changes. 

I'll definitely look into making it a single sip consumable if it does get abused, I'd need to actually see what ways players are abusing it in order to strike new ideas on how to implement it. Dilution already gives me an idea to add a new mineral that can be utilized as a 'buffer' to extend the durations of potions when you consume it. Perhaps it can come with the downside of not being able to eat or drink anymore if you use the buffer? Unsure! Many ideas will unfold.

**Comment by DeltaFire15** [comment]
> The buff applied on you is immediately removed when you metabolize it entirely.

Please point me towards the section of your code that does that because I do not see anything that would do that.

**Comment by Lynx22330** [comment]
> > The buff applied on you is immediately removed when you metabolize it entirely.
> 
> Please point me towards the section of your code that does that because I do not see anything that would do that.

The buff stops being applied to the character when it stops metabolizing after the duration? 
I can set the status effect down to like 20 to make it truly stop metabolizing, but I had thought to be generous with a baseline of 100. (Which, I am assuming is 5 seconds?)

You only get the status effects as long as you're metabolizing. Once you stop metabolizing, the effects go away.

**Comment by DeltaFire15** [comment]
Status effects are in game ticks (10/s) which means 100 equals ten seconds.
This is what makes microdosing viable,as even if you drink 0.1u, the effect will still last at least ten seconds.
The same applies to your para potion, as you apply a really long stun on every metabolism tick, which means you can also just dilude it into 0.1u parts, have it tick once for stun, then apply another 0.1u element once about to run out

**Comment by Lynx22330** [comment]
I'll drop the effects to 10 ticks then. Paralysis is still only 3u yielded upon crafting. I'll drop the paralysis state to something else.

AS for the microdosing, huhm. 

I can set it so that each potion is only 3u crafted, then? But then most players wouldn't understand why cuz of microdosing stuff... 

Bleh, okay. Looks like I'll need to set this up to be a single consumable item. Was hoping to have it stay as a liquid and not cause issues when people metabolize. I still do want to see people use this in-game as its liquid reagent state to see how negatively it'd impact, if at all. Mostly out of curiosity. I'll work on seeing to adding a single use consumable with the stat effect duration, thank you for enlightening me on the topic! 

Time to spend another day on this---

Nnnoooo

Nevermind

I know exactly what I can do ...

Let me make a quick commit real quick!

**Comment by Lynx22330** [comment]
Okay looking over this the original idea didn't work. Just gonna opt in to have elixers that are 1 unit each and untransferable to other items other than for consumption. 

They grant you the status effect upon consumption however and will be able to be 'spilled' or 'splashed' so that people can empty them just to be mean >:)

**Comment by Lynx22330** [comment]
Alright! I decided to add a "OVERDOSE THRESHOLD" to the potions, so that when someone "overdoses" they can get the effects. It requires you to take 4 swigs of a single bottle, or 8 for combined potions. (They all require 19u of overdose since you drink 6u from the bottles at once.)

I think Im gonna add a check to see when the overdose process ends to clear out all of the potion reagent in someone's body in order to make sure it clears in order to enforce people to drink 20u each time the status effect ends if they want to get another buff.

**Comment by lowpowermia** [comment]
hey i  just gotta say 5 perception as a buff is a little busted cause that nearly doubles the damage of a crossbow (which already does mondo damage)
goes from a 1.0 mod at 10 perception to 1.5x mod, alongside the crossbow's natural 2x mod, that's either a 3x multiplier or a 2.5x multiplier for the actual bolt's damage which already has like. 50 pen??? 140 damage going to 210 or even more if you have DECENT perception in the first place.

**Comment by Lynx22330** [comment]
Yippee, you now need to drink 20u of a potion to gain it's effect. This can be changed easily by changing the overdose amount, and the amount removed after the overdose threshold proc is triggered. 

This prevents microdosing, or mixing altogether, and encourages people to utilize primarily pure potions unless they intend on buffering their potion effect.

I set metabolism to 0 to garuntee, but, like I said, they can buffer it and then combine all 3 potions together all at once and take one sip. I'll aim to make it a little easier to proc the potion effect whilst still causing metabolism to tick over... I'm thinking of setting it to 0.2 and having the overdose proc at 19, and then removing 20 units to ensure that it's always 4 sips before OD.

**Comment by Kroto-Ker** [comment]
Amazing work!

**Comment by Lynx22330** [comment]
THE PR IS READY TO BE MERGED IF ANYONES INTERESTED BY THE WAY! I DONT KNOW WHAT ELSE TO CHANGE!

**Pull request merged**
