### PR TITLE
t3 Eoran spell [WIP DO NOT MERGE]

### PR DESCRIPTION
**Pull request by Gardelin013**
Rewriting it to be more serious

### CODE REVIEW

**Comment by faaaay** [comment]
Nope, no thank you. ERP mechanics should stay within ERP. If I have Defiant on and everyone around me starts coming, I have still been drawn in to this.

**Comment by YuiY1997** [comment]
> Nope, no thank you. ERP mechanics should stay within ERP. If I have Defiant on and everyone around me starts coming, I have still been drawn in to this.

this tbh. PLus I'm fairly certain this will just be used to stun and gank people without defiant on.

**Comment by YuiY1997** [comment]
would be nice to have a different spell completely. 

This one just seems out of place and fetish content-y. We need something more to do with Eora, and church slots in general than just sex mechanics.

**Comment by coffeecoffeecoffee** [comment]
> I can already see people mid-combat turning off the menu to powergame. This will happen anyone fights anyone now.
> 
> Get out of jail free, toggle ERP menu to nullify powers. Redesign this to be a different spell.

I actually don't think that's a bad thing. If you want, maybe it can simply become a paralyzing stun on anyone who has it set to off? But I like the idea.

**Comment by Gardelin013** [comment]
There is no Stun, people. Just Jitter animation.

**Comment by Kroto-Ker** [comment]
we got the flower spell for beauty. now add the cum spell. commit to the theme.

**Comment by Gardelin013** [comment]
Spell rewritten, made less spamable and working on consent-message only

**Comment by Mannybrado** [comment]
revive people from death or instant orgasm, your choice!

**Pull request closed without merging**
