### PR TITLE
Fuck Storage Powercreep

### PR DESCRIPTION
**Pull request by Ruediger4**
## About The Pull Request

MFW I can smithe a backpack-tier item without the downside of a backpack

## Why It's Good For The Game

Right now you can access the doctor's bag without having to take it off your back, making backpacks redundant.

You can't have your cake and eat it too. The alternative is restricting doctor bags to only surgical items. But IDK how to code that. I may do that instead of this. But I'm dropping this to make people see the issue.

### CODE REVIEW

**Comment by Ruediger4** [comment]
> Take a look over at code/game/objects/items/storage/belt.dm;
> 
> > /obj/item/storage/belt/utility/ComponentInitialize()
> > . = ..()
> > var/datum/component/storage/STR = GetComponent(/datum/component/storage)
> > STR.max_w_class = WEIGHT_CLASS_NORMAL
> > STR.max_combined_w_class = 21
> > STR.set_holdable(list(
> > /obj/item/crowbar,
> > /obj/item/screwdriver,
> > etc etc etc
> > /obj/item/inducer,
> > /obj/item/plunger
> > ))
> 
> That _should_ let you set the objects that can go into it, assuming RT didn't make entirely bespoke storage code. Worth an experiment, anyway.

So true, lemme toy with it later

**Comment by Ruediger4** [comment]
> dip shit doesnt ask the original person who coded it to fix it and goes in making a salt PR. the storage restriction line wasnt added. next time use words instead of a salt PR.

image

On one hand i didnt know who added it + was too lazy to look it up

On the other, lol lmao I said i'd look at adding storage restriction, and you can see I didnt yet

**Comment by Ruediger4** [comment]
> image
> 
> 
> 
> speaking of powercreep you should also mention in your fucking with weapons and armor too. or make an entirely new PR specifically for that. gets confusing for people who... actually code and not make there favorite weapon stronger when they see these commits.
> 
> 
> 
> *spits

Ngl seeing you spend at least 4 posts being this unhinged over adding a single line of code and not bothering to see that those changed files are things from my first PRs and believing it to be "UR SNEAKBUFFING UR SHIT" is genuinely entertaining

For someone who "no longer codes here" you sure are getting stressed about it bud! Nonetheless thank you for dropping by and leaving your constructive criticism that will be used to further build PRs!

Hope you have a wonderful Saturday!image

**Comment by Ruediger4** [comment]
> > > image
> > > speaking of powercreep you should also mention in your fucking with weapons and armor too. or make an entirely new PR specifically for that. gets confusing for people who... actually code and not make there favorite weapon stronger when they see these commits.
> > > *spits
> > 
> > 
> > Ngl seeing you spend at least 4 posts being this unhinged over adding a single line of code and not bothering to see that those changed files are things from my first PRs and believing it to be "UR SNEAKBUFFING UR SHIT" is genuinely entertaining
> > For someone who "no longer codes here" you sure are getting stressed about it bud! Nonetheless thank you for dropping by and leaving your constructive criticism that will be used to further build PRs!
> > Hope you have a wonderful Saturday!image
> 
> doesnt code here doesnt mind swinging by to insult folks like you. this isnt discord or twitter, your meme screenshot response shows your age. and your lack of knowledge that thos commits still apply to your code even if "first pr" also shows you shouldnt even be making PR's. you didnt branch off from them which means on a merge its going to be merged with it because you merged them into your main branch instead of having it as a separate branch.

# OK

**Comment by EerieDream** [comment]
> > > image
> > > speaking of powercreep you should also mention in your fucking with weapons and armor too. or make an entirely new PR specifically for that. gets confusing for people who... actually code and not make there favorite weapon stronger when they see these commits.
> > > *spits
> > 
> > 
> > Ngl seeing you spend at least 4 posts being this unhinged over adding a single line of code and not bothering to see that those changed files are things from my first PRs and believing it to be "UR SNEAKBUFFING UR SHIT" is genuinely entertaining
> > For someone who "no longer codes here" you sure are getting stressed about it bud! Nonetheless thank you for dropping by and leaving your constructive criticism that will be used to further build PRs!
> > Hope you have a wonderful Saturday!image
> 
> doesnt code here doesnt mind swinging by to insult folks like you. this isnt discord or twitter, your meme screenshot response shows your age. and your lack of knowledge that thos commits still apply to your code even if "first pr" also shows you shouldnt even be making PR's. you didnt branch off from them which means on a merge its going to be merged with it because you merged them into your main branch instead of having it as a separate branch.

Crying-baby-010

**Comment by EvenInDeathIStillServe** [comment]
most constructive hearthstone pr conversation

**Comment by Stutternov** [comment]
> doesnt code here doesnt mind swinging by to insult folks like you. this isnt discord or twitter, your meme screenshot response shows your age. and your lack of knowledge that thos commits still apply to your code even if "first pr" also shows you shouldnt even be making PR's. you didnt branch off from them which means on a merge its going to be merged with it because you merged them into your main branch instead of having it as a separate branch.
image

**Comment by Kabramen** [comment]
> doesnt code here doesnt mind swinging by to insult folks like you. this isnt discord or twitter, your meme screenshot response shows your age. and your lack of knowledge that thos commits still apply to your code even if "first pr" also shows you shouldnt even be making PR's. you didnt branch off from them which means on a merge its going to be merged with it because you merged them into your main branch instead of having it as a separate branch.
image

**Comment by ThatFurry2** [comment]
Lmao, you're all goans

**Comment by Ruediger4** [comment]
I'll Be Back (in exactly 10 minutes)

**Pull request closed without merging**
