### PR TITLE
Buffed Bolts/Arrows

### PR DESCRIPTION
**Pull request by Dogamy**
## About The Pull Request

My first PR, very basic. Just edited the variables to be slightly higher and make it worth someone's time to use ranged weaponry.

## Why It's Good For The Game

Incentivises guards/hunters/anyone using ranged weaponry to use something other than Magic or Melee weapons by increasing Bolt/Arrow damage and armor penetration. Essentially makes being a ranged class executable, instead of just meta'ing usage of Magic or Melee. Potentially able to revive the use of ranged weapons.

### CODE REVIEW

**Comment by Dogamy** [comment]
I do mean it when it's my First PR- I'm very new to code and Github overall. Please give feedback and commentary.

**Comment by Stutternov** [comment]
Honestly a needed change. Bows are currently pretty bad at what they do; this pr actually restores their values how they were prior when they worked pretty well.

Only input I have is maybe to leave poison bolt damage a tad lower, they inherit the armor pen of the main arrow. So perhaps leave it lower due to ticking damage atop of the raw damage (so it's not just objectively a better arrow).

Otherwise 100% at least test merge this and adjust.

**Comment by Dogamy** [comment]
> Honestly a needed change. Bows are currently pretty bad at what they do; this pr actually restores their values how they were prior when they worked pretty well.
> 
> Only input I have is maybe to leave poison bolt damage a tad lower, they inherit the armor pen of the main arrow. So perhaps leave it lower due to ticking damage atop of the raw damage (so it's not just objectively a better arrow).
> 
> Otherwise 100% at least test merge this and adjust.

Personally? I understand where you're coming from, and maybe an ~5-10 lowered damage variable would be good? Though, it should _kinda be_ arrow+. If someone takes the time and effort to go and get berries and poison your arrows, it's an rightfully earned bufff, I'd say- but I do understand the thoughts.

**Comment by DeltaFire15** [comment]
Isn't the point of ranged weapons their, well, range? You don't need to be next to someone also trying to hit you, and can hit things from well outside of their vision if you have the drop.
From what I can see they also always embed (assuming proper use).

You also get a bonus to bow effective damage the further you go above 10 perception.

>bows are only bow skill check

No. Bow charge time scales off bow skill, strength, and perception.
Crossbows on the other hand are split into winding (str scale) and firing (crossbow skill & perception scale)

**Comment by Stutternov** [comment]
> Personally? I understand where you're coming from, and maybe an ~5-10 lowered damage variable would be good? Though, it should _kinda be_ arrow+. If someone takes the time and effort to go and get berries and poison your arrows, it's an rightfully earned bufff, I'd say- but I do understand the thoughts.

I can see why and I haven't checked how hard it is to get a poison arrow here (I rarely need to scavenge plus I knew arrows are useless) but I believe you can get the berry rather easily and it's one arrow. Maybe a ~5-10 less is more fair given you can out-sleep the poison but the stab wound on top of it is punishing. 

Maybe test it locally? Check the death time on each type.

**Comment by Dogamy** [comment]
> Isn't the point of ranged weapons their, well, range? You don't need to be next to someone also trying to hit you, and can hit things from well outside of their vision if you have the drop. From what I can see they also always embed (assuming proper use).
> 
> You also get a bonus to bow effective damage the further you go above 10 perception.

That /should/ be how it is, but it only really works like this on paper with how they are in the game. Right now, the most they do is embed and just give you a little bleeding. Especially with armor, all it does is just make it so that you've given away where you are, that you likely aren't as armed, and that you have an weak weapon and can get easily killed because you chose something ranged. It's just not worth anyone's time to even /be/ ranged, thanks to the utter uselessness of Arrows right now.

**Comment by EaglePhntm** [comment]
wtf isnt bolts and arrows like already instakill buttons

**Comment by Stutternov** [comment]
> wtf isnt bolts and arrows are already like instantly kill people on touch in any limb with a crit cause how dogshit strong they are? I literally got banned cause i accidentally one tapped the vampire lord with a crossbow before lmao.

They only do 35 damage. If unarmored it can do severity 3 wound with bad bleed but if armored it basically is worse than a dagger (which pick mode has 80 pen factor)

**Comment by Stutternov** [comment]
> I accidentally one tapped the vampire lord

Also I have no idea how you did that given they don't even get stab wounds, so at best you did 35 damage to them.

**Comment by DerFlammenwerfer** [comment]
> > I accidentally one tapped the vampire lord
> 
> Also I have no idea how you did that given they don't even get stab wounds due to no bleed no pain, so at best you did 35 damage to them.

THey have weakness to critical hits

**Pull request merged**
