### PR TITLE
Royal Guard - Archer Class, Crossbow/Musket Skill Change, & Fixing Slop

### PR DESCRIPTION
**Pull request by Stutternov**
## About The Pull Request

This PR does the following things:
- **Adds a new Royal Guard class with a unique new weapon.** That being the Royal Guard archer, who starts off with slightly 'worse' melee gear and stats than normal guardsmen, but in return gains a more powerful than usual bow (extra 25% damage!!! Zamn!!!) 
- **Adds crossbow port requested by Onutsio.** Basically makes it so skill on crossbows matters more than before; charge time for untrained being ~10 seconds, journeyman 4-5 seconds, and as low as 1 (hard-cap) on master. Also modified by perception skill. 
- **As a side-change, made it so muskets are identical to crossbow charge times.** They are orderable now, so they need to not be so cracked vs crossbows. So, this should keep them roughly equal for now.
- **Fixes bugs.** Other PRs legitimately don't fucking compile and got merged, fixed them to compile so I could even test my code.

**Give feedback on armor, please.**
Currently using a fancy brigand armor piece, I'm leaning towards just giving a chest-only piece of armor instead possibly. The class gets iron bracers as is, and it's supposed to be a royal guard archer so may fit better. Tell me what you think, keep current shown below or change-out the armor to a chest plate. (Keep in mind, no full-plate. Archer gets medium armor training + dodge expert if they opt for light armor.) 

**NOTE:** Picture provided, on-mob icon issue has been fixed. I'm merely too lazy to go set up for another screenshot rn.
image

## Why It's Good For The Game

Seemed wanted in terms of royal guard, people liked the idea of possible longbow additions in the future (too lazy rn), crossbow change sounded good and was requested, and fucking test your PRs before putting them up. I get if they bug, I get if they don't work right - I don't get when they don't even fucking compile.

### CODE REVIEW

**Comment by Stutternov** [comment]
> or I could give you no PR.

Sure?

**Comment by Stutternov** [comment]
Decided to do steel breastplate after all, looked better imo. 

Also fixed issues with new royal guard changes with this PR conflicting.

**Comment by LittleEvil9** [comment]
Finally god, a light/medium armor variant of the royal guard. How unbalanced would it be to give it polearms skill 3, for those that  want to engage more closely at melee instead of fully focusing on being an archer?

**Comment by Stutternov** [comment]
Said this in dev channel, re-iterating. Don't merge currently, sprite conflicts. I'll fix it tonight sometime. 

After that it'll be ready to merge.

**Comment by Stutternov** [comment]
Right, should be good again now.

**Pull request merged**
