### PR TITLE
Cleric & Church Improvements: psycross QoL, new Cleric subclass & more Acolyte patrons

### PR DESCRIPTION
**Pull request by Ephemeralis**
## About The Pull Request

Three things:

- Using MMB on a worn psycross causes you to start doing a devotion prayer if you have the ability to, otherwise it does nothing new. Purely a convenience/QoL thing to make people need to look at the verb panel less.
- A new Adventurer subclass has been added for the Cleric: Cloistered Devout.
    - Cloistered Devout is a spellcaster-focused variant of the cleric that foregoes all of the armor and weapon buffs it gets in exchange for gaining half the passive devotion gain that Priest gets (0.5) and access to T3 spells like an Acolyte. It does **not** gain Churn like ordinary clerics do to compensate for this.
    - It gets a gambeson, some devotional robes (matched to your chosen patron where possible) and a wooden staff as starting gear instead of the halfplate+mace+shield that cleric ordinarily gets.
    - The physical attribute bonuses cleric ordinarily gives are removed (STR, CON and END), and replaced with a -2 to STR, a +4 to INT, a +2 to PER and a +1 to SPD.
    - It has a host of bookish skills pulled from the other cleric subclasses and improved slightly to compensate for the lack of starting combat strength. It also has level 5 holy magic, which gives a pretty sizable chunk to active devotion regain when praying, among other things.
- The entire Divine Pantheon (to clarify, the Ten except Dendor, which the Druid role already covers) has been added to the Acolyte church role so that people can play clergy that aren't hardlocked to Pestra, Eora or Astrata.

## Why It's Good For The Game

Adventurer clerics can now go for a spellcastery bent if they want to, with some slight flavoring of their chosen patron.

The MMB psycross devotional prayer thing is self-explanatory.

Acolytes being able to be any Divine Pantheon patron should open the Church up to a LOT more characters.

### CODE REVIEW

**Comment by faaaay** [comment]
I like this overall, but I'm hesitant to give Clerics T3 spells in any form again, since that risks making the church obselete. That said, this seems like a good compromise, where they're guaranteed to gain devotion slower.

Can I ask why you gave them +1 speed, though?

**Comment by Ephemeralis** [comment]
No particular reason other than the other non-heavy armored cleric subclasses also have it.

**Comment by Ephemeralis** [comment]
I've gone ahead and hard pivoted this and removed the initial T3 stuff and just kept the passive devotion gain for Cloistered Devout.

I've also added the rest of the Divine Pantheon to the Acolyte job to encourage people to actually play Church roles on characters that aren't Pestran, Eoran, or Astratan.

**Comment by faaaay** [comment]
> I've gone ahead and hard pivoted this and removed the initial T3 stuff and just kept the passive devotion gain for Cloistered Devout.
> 
> I've also added the rest of the Divine Pantheon to the Acolyte job to encourage people to actually play Church roles on characters that aren't Pestran, Eoran, or Astratan.

In that case, I'm all for this PR.
Though does Acoylte have clothes/spells for people who don't follow Noc/Necra/Eora/Astrata/Pestra? ~~Followers of Noc and Necra are so rare there...~~

**Comment by Tree445** [comment]
Aren't spells assigned based on patron? This would mean other patrons wouldn't get any spells.

**Comment by Ephemeralis** [comment]
> Aren't spells assigned based on patron? This would mean other patrons wouldn't get any spells.

They are assigned based on patron, yes. `/datum/patron/divine` has Lesser Miracle as a T0 base, so Acolytes without any other spells made at this time would at least get this to play with. This would only affect Abyssor, Ravox and Xylix at the moment - everybody else in the Ten has some kind of t1, even if they're duplicated.

**Comment by Ruediger4** [comment]
I fuck with this. I always thought Clerics were a bit too strong physically yet weak faith-wise so making a Cleric version that's like a poor man's Priest is something i like

**Comment by Dumbdumn5** [comment]
> I like this overall, but I'm hesitant to give Clerics T3 spells in any form again, since that risks making the church obselete. That said, this seems like a good compromise, where they're guaranteed to gain devotion slower.

Just reiterating this from my thoughts on this discord. The church will not necessarily be played more whether or not clerics are nerfed. Removing and keeping T3 removed from clerics will get you with less cleric players and less 'easy revives', sure, but it won't make church more popular. Given there's a surgery that involves literally zero piety and just a high medical skill, it's already possible to both revive someone and cure rot like this in-game as a non-church role, and without even needing a cross around. 

The only complaint I heard beyond 'easy revives' was Dendor clerics having kneestingers that are too spammable- which sounds more like a problem with either the kneestinger spell or kneestingers in general than every single cleric necessarily needing their higher tiers lopped off.

Church needs to be made more fun and interesting with changes like this one, the addition of more to pantheons, and giving them more potential duties or responsibilities besides trivializing the soilson's job and... generally being a healbot that occasionally gets to scream about heresy.

**Comment by burdwatcher** [comment]
Mimicing what others have said here, this is not going to make me play the church more. It's just going to keep me not playing my cleric altogether because I don't want to get dragged into the boring church revolving door of reviving people. I don't really see the issue of basically not church tied acolytes roaming around, is it really so bad if we can just hang out and RP our faith in the streets and revive/derot when appropriate? Plus the limited slots of acolyte makes me feel guilty taking something that's not astrata/pestra so I _**really**_ dislike being forced to use that role to play my eoran.

**Comment by Ephemeralis** [comment]
I've gone ahead and put T3 spells back on cloistered devout (cleric subclass) with the caveat that they don't get churn as an automatic default like ordinary cleric does (since they have access to more spells via patrons most of the time).

With the maintainer's blessing, we can give this a try and see how it pans out in play.

**Comment by lowpowermia** [comment]
ordinary cleric doesn't get churn by default, as an aside, that's paladins, unless that was given in response to taking the whole lvl 3 and up stuff

**Comment by Ephemeralis** [comment]
> ordinary cleric doesn't get churn by default, as an aside, that's paladins, unless that was given in response to taking the whole lvl 3 and up stuff



Both templar *and* cleric get churn as an additional spell regardless of their patron at the moment. For the record, this is base behavior, and not my change.

**Pull request merged**
