### PR TITLE
Removes Time Stop because our event makers can't be trusted

### PR DESCRIPTION
**Pull request by AllCorruptingWyrm**
## About The Pull Request
image
This PR gets rid of the time stop spell so GMs can stop abusing it during their subpar events.

## Why It's Good For The Game

Observe:
 https://www.youtube.com/watch?v=RYVBlJdQcww

### CODE REVIEW

**Comment by EerieDream** [comment]
Event runners not robust so they have to resort to broken spells. Who would've guessed!

**Comment by Tree445** [comment]
That's not a GM. That's a player.

**Comment by Stutternov** [comment]
Won't be merged because Apple likes giving themself the time stop spell to abuse.

**Comment by worriedconcentrate** [comment]
Time stop and sleep are effectively the same spell, at the least no one killed me in time stop. Probably not worth the salt PR.

**Comment by AllCorruptingWyrm** [comment]
Great, please ensure these spells aren't given out anymore, its abysmally unfun @Tree445

**Pull request closed without merging**
