### PR TITLE
Apple's Vampire Expansion DLC

### PR DESCRIPTION
**Pull request by Tree445**
This PR is to set the very basic groundwork for the vampire faction.
- Adding Vampire Thrall and Smith
- Smith is disabled for now
- Thrall has 4 Slots
- Average Stats, Shit Loadout
- Bat Form, Recruit Sympathizer Spell, All the basic vampire traits + FAITHLESS
- Couldn't figure out how to code the actual vampire stuff, so these are work-arounds. The idea of vampires who are caught between zizo and psydon being faithless seems pretty thematic. Either way being Zizo gives no benefit and vampires shouldn't be getting healed.
- As a stark contrast to vikings, this is meant to almost be an entirely RP focused faction. Vampire faction is meant to be non-antag neutral.
UPDATE: I did figure out the vampirism situation, though it may be a bit overpowered and abused if real vampirism is given. We will go with the RP approach over real vampirism to test the waters.

### CODE REVIEW

**Comment by Tree445** [comment]
- I will note that I need to change the Vampire Thrall role name to be more ambigious, so that people dont yell vampire when they see the role name in a description. Something to differentiate them from antag vampires. I was thinking Antediluvian, but that would be more fitting for an add-on high-ranking faction rank.

**Comment by Kroto-Ker** [comment]
It would be cool if people in regular roles could have a chance to be turned into a thrall, for a sort of vampire mystery antag. Figure out who's the vampire in the keep sucking people's blood at night.

**Comment by Tree445** [comment]
> That said, if you must do this you need to set it up so _either_ vikings or vampires load in, like SS13 proper random ghost roles. (This can probably be done by just making it random if their map tiles load in.)
> 
> We can't have _three_ non-town factions all vying for a playerbase at the same time. Tribe and raider groups are already ghost towns most of the time.

There are plans to shrink and move the tribe around, since at the moment they are too large. They should be a mini-faction like vikings (6 slots), and vampires (4 slots). Overall, such small factions will do little to take away from the main faction, considering we regularly had a fuckton of players going adventurers. These factions, and more mini-faction(which will mostly be a part of the town) will serve to create more interesting avenues of roleplay outside of generic towner roles and generic adventurer roles.

**Comment by Tree445** [comment]
> Faithless is bad, this means they are immune to miracles, which are supposed to stun them on account of being undead.

They also lack the Vampire Regeneration ability, which is a major benefit to them. This is less of a PVP role/faction and more of a role focused on RP. If this is unpopular, faithlessness will be swapped for real vampirism.

**Comment by DorfGuy1** [comment]
What the heck is the faithless trait anyway, can't find it in the code.

**Pull request merged**
