### PR TITLE
[DRAFT] Merges Knight into Village Elder

### PR DESCRIPTION
**Pull request by faaaay**
## About The Pull Request

As the host is looking for a way to re-implement Knights, I'm putting this forward as one option. This merges the Knight and Village Elder into the Alderman, a knight charged with guardianship (but not ownership of!) the outer reaches of Rockhill (i.e. the Bog-town within the gate).

## Why It's Good For The Game

Apple wants Knights, and I thought this could be a fun idea. But it's 2AM right now and I need a way to demonstrate the idea, so I don't know, I'll fill out this field more in the morning. It's a draft.

### CODE REVIEW

**Comment by faaaay** [comment]
> imo
> 
> I don't think just blowing the shitty bog militia out of the water is a good idea with some big dick energy person attached to them, especially given the walk from the outlying town to the keep proper is, like, thirty seconds. Long in the context of a BYOND game, but still trivial. This would be an additional royal guard.
> 
> also riding _typically_ is capped at two for some reason, as an aside

Yeah, that's a good point, I'll look at bringing them down to be in-line with bog guard skills. Could've sworn I set their riding to 1... oh well. I'll add that to the to-do list.

**Comment by Wesreidau** [comment]
I don't know about this one. Perhaps if we had the knight spawn in the manor houses out in the bog valley with personal soilers it would make more sense.

**Comment by faaaay** [comment]
> I don't know about this one. Perhaps if we had the knight spawn in the manor houses out in the bog valley with personal soilers it would make more sense.

I'm not sure where you're referring to.

**Comment by faaaay** [comment]
The way I see it, they can either be _mechanically_ powerful and in service to the bog or they can have _authority_ over the bog.

**Comment by faaaay** [comment]
> > The way I see it, they can either be _mechanically_ powerful and in service to the bog or they can have _authority_ over the bog.
> 
> Authority over the bog would create fiction with the Bog Master.

Exactly, so they _don't_ have any concrete authority. I'm basically just voicing another reason not to give them that. 
The idea is that they're someone who's trusted as an advisor and judge, but only so far as they're assumed to be relatively wise.

**Comment by Stutternov** [comment]
The only thing I keep asking is - why.

Royal guard have knighthood and the titles are on their jobs; they even have the noble trait. The main difference being they are royal guards instead of wandering knights/hitmen. 

There is also adventurers I was asked to add for knights, the Captain is a knight, etc. 

I kinda would get this if royal Guard and adventurer was gone but it's a.. 8th knight position.

**Comment by faaaay** [comment]
> The only thing I keep asking is - why.
> 
> Royal guard have knighthood and the titles are on their jobs; they even have the noble trait. The main difference being they are royal guards instead of wandering knights/hitmen.
> 
> There is also adventurers I was asked to add for knights, the Captain is a knight, etc.
> 
> I kinda would get this if royal Guard and adventurer was gone but it's a.. 8th knight position.

Because Apple wants knights, and conceptually I prefer this to the approach they've proposed.

**Comment by faaaay** [comment]
Closing this so I can see how apple's current vision plays out and because I can't be bothered to finish this for a while

**Pull request closed without merging**
