### PR TITLE
Silver Creation [Difficult]

### PR DESCRIPTION
**Pull request by AllCorruptingWyrm**
## About The Pull Request

This PR makes silver something that can be obtained but at a gigantic cost that will absolutely be awful to make for anyone who hasn't done either A: A metric ton of alchemy, or B: Has no smithy.

Feedback: Please provide it, I have no idea if its worth trying or not.

## Why It's Good For The Game

Limiting a resource to an arbitrary point was just not needed, this gives work to both the Blacksmith and Alchemists in the round, as a sort of end goal to work towards to facilitate cooperation between two crafts. This can also be used to punish antags who want to murderbone too.

### CODE REVIEW

**Comment by EtheoBoxxman** [comment]
Steel and gold are far too easy to get to justify that being the transmute.
The reason riddle of steel is as rare to get is because it has so many steps. Perhaps throw in the cost of 1 dorpel or 1 riddle of steel to offset the time expense and value of it?

Riddle of steel would also mean that if the crown is on point, they can afford to buy it from the merchant, or goldface if lacking one. This would be the best option, I feel, as it also encourages pooling wealth and allows for a money sink as well, best case scenario.

**Comment by AllCorruptingWyrm** [comment]
sure i'll add like 2 diamonds

**Comment by AllCorruptingWyrm** [comment]
made it require 2 seffira and compiled

**Comment by AllCorruptingWyrm** [comment]
Good to merge btw.

**Pull request merged**
