### PR TITLE
Statpack Rebalancing Cope

### PR DESCRIPTION
**Pull request by Stutternov**
## About The Pull Request

People coped about bonus strength despite giving literally 0 feedback on it but "B-But you can start with +3 strength now if you choose one race and a background!" is an issue only now after like me asking - 'hey buds can you look this over since this is the slop you wanted me to do so bad?'

## Why It's Good For The Game

Idk it's rebalancing.

### CODE REVIEW

**Comment by faaaay** [comment]
don't give into the haters, we ball

**Comment by pleasekillmerek** [comment]
close this immediately, it's fine. no one complaining actually fights and they're just mad that someone else might have a hypothetical advantage of their character in a potential fight that won't ever happen.

**Comment by Stutternov** [comment]
Also I'm too lazy to remove the longbow code; I'm adding it anyway for a different PR thing but hey boom it's here I guess.

**Comment by EvenInDeathIStillServe** [comment]
Just go all in and remove racial stats.

**Comment by Kroto-Ker** [comment]
I say don't remove the strength boosts, they already get negative boosts in the statpack to balance the extra strength.

**Comment by DeltaFire15** [comment]
Species should have an, at the very least, basic level of impact on capability, that fit their species.

Their previous impact was trunchated when statpacks were added, which is okay, but some signature change to show what this species **on average** is good with, keeps flavor for them.

I feel a lot like, for some reason, a lot of people argue (both for and against) with maximum powergaming mindset when it comes to attributes, when the entire thing with races is that they give you more to play around with, aswell as some weak points to compensate for, on average.

**Comment by lowpowermia** [comment]
man im just annoyed abt the moth racial, their entire deal's brain and no bones, but their racial's speed and minus int

**Comment by faaaay** [comment]
People are mad that fights will be more even because people don't get nerfed for playing the OC they want to play

**Comment by Troopermoores** [comment]
Far to early to be making adjustments, give it a week to deal with growing pains then once you see issues that are common work from there

**Comment by bearrrrrrrr** [comment]
im coding in socks and i approve of this PR

**Comment by Stutternov** [comment]
> Also I'm too lazy to remove the longbow code; I'm adding it anyway for a different PR thing but hey boom it's here I guess.

i was un-lazy enough to remove the longbow code it turned out

**Comment by Stutternov** [comment]
Saying this again - either roles need to have their stats evaluated they hand out or this should probably be merged at this point.

I do not feel like going through every single job to adjust starting speed/strength buffs, like Rogue as a huge offender or Nordic Queen/Monk/Barb. Plus the fix for werewolfs statpack errors is on this PR.

**Pull request merged**
