### PR TITLE
Rat-wood-ification of The Furry Block.

### PR DESCRIPTION
**Pull request by Jeff-Dome**
## About The Pull Request

This PR isn't meant to be merged/taken seriously.

## Why It's Good For The Game

Lol why bother asking in LOOC. Just zape! Randomly

### CODE REVIEW

**Comment by Mannybrado** [comment]
Ohhhh... Okay!

**Comment by faaaay** [comment]
who asked

**Comment by Stutternov** [comment]
sir your Reddit ebic meme post is ready

**Comment by n3tis** [comment]
Merge this immediately

**Comment by coffeecoffeecoffee** [comment]
i don't understand
what's the complaint?

**Comment by AysheDaArtist** [comment]
Prime case of closeted furry

**Comment by Rin053** [comment]
jeff is that you

**Pull request closed without merging**
