### PR TITLE
Adds heir classes, bardic casting, and apothecary & thug for towner

### PR DESCRIPTION
**Pull request by burgerenergy**
## About The Pull Request
god damn

-  Separates the Royal Heir into distinct classes, all of whom are intentionally incompetent;
-  - The Daring Twit, who is more or less a squire, for those who want to be _adventurous_
-  - The Sheltered Aristocrat, for those who want to be a pretty prince(cess). They take after the queen to a degree, so arguably they're the most competent of the three.
-  - The Inbred Wastrel, a real piece of shit, waste of oxygen... but nobleborn. The no-run perk doesn't work, but that's out of scope!
- Adds the towner Apothecary class; a mix up of a doctor, who specializes more so in alchemy then medical practices, as well as insignificant skills in actually obtaining their reagents. They can be a physician in a pinch, but without the ability to diagnosis they're flying blind.
- Adds the towner Thug class; just a brute, really good with maces - but only as good as the watch. The brigand who lives next door, and acknowledges they shouldn't shit where they eat. They're certainly dangerous, but their aggressive ability comes at the cost of having no aptitude for defense. Find a gambeson, menace.
- Adds another subclass for bards, arcanist. The arcanist is a DnD bard, gaining spellcasting. As a cost, they have ever so slightly reduced melee skills and lose their medium armor proficiency.
- As an aside, noble guests lost their extremely high riding skill to be in line with everyone else.

The changes to Heir also takes care of #298 

I was going to add a Bogguard horse skirmisher class, but for some reason Apothecary actually generating took four hours and I still don't know what fixed it.

Admittedly, this will also people to drop in as the challenge classes as heir, but that's true of guard as well. It's a problem for another day.

## Why It's Good For The Game

Lets the prince(cess)s of the realm choose what flavor of prince(cess) they want to be. Also lets people actually get to touch the new alchemy system, as opposed to it being tethered to court magi, archivist, and sometimes merchant, as well as do CRIME. And, you know, bard things.

## Proof of testing because I'm not a savage

image image image image

### CODE REVIEW

**Comment by Stutternov** [comment]
Bard already had lost medium armor; is this being re-added?

**Comment by Stutternov** [comment]
> Bard has it as is. Can't comment there.
> 
> The thug is purposefully meant to be a potential combat class. Otherwise their value as the brute-muscle role is waning. I hemmed and hawed between three or four, but I opted with four as they won't have much of the _other_ combat values, so they should still get steamrolled by concentrated effort.
> 
> If it's bad vibes we can knock it down a rank after.

image
I believe your main may be out of date. This is current bard.dm on code.

**Comment by Tree445** [comment]
How come you made the heir classes challenge classes instead of subclasses?

**Comment by Tree445** [comment]
Oh I understand now.

Strange that there are two different ways of choosing class. Makes me wonder why the other system didn't get replaced by this method.

**Pull request merged**
