### PR TITLE
Complete Garrison Overhaul (+ Mercenary Class System, Shield Skill, & Barrack/Merc Inn Mapping)

### PR DESCRIPTION
**Pull request by Stutternov**
## About The Pull Request

This is a big PR, so I'll be outlining it in sections.

### Garrison Changes
- **Bog Guard** - Bog guard no longer get RnG archer role, since it wasn't really helpful to them, and now instead get bow skill normally. Bog guard are specially trained in axes and polearms, due to being peasants, and get some weak regular peasant skills (farming + crafting). Basically becoming a 'jack of all trades, master of few' kind of role as they'll need to train most other skills to equal other guard jobs.
- **Town Watch** - Town watch has gotten a complete face-lift, allowing you to select one of two types of class. Footman, a watchman with mace and polearm training with some skills in other fighting styles, and Archer, who specializes in crossbows, bows, and daggers with a few misc skills a hunter may have; as their life has switched from hunting to man-hunting. (I also dropped their slots from 9 -> 8. How sad... Make it even numbered, it hurts me...)
- **Men-at-Arms / Knight -> Royal Guard** - I've restored knight as no longer it's own role and rather did the old idea of just merging them together. Royal Guard are still knights but are not as 'broken' stat-wise, encouraging specialty between a 'Heavy-knight' who uses polearms and maces, or a 'Foot-knight' who uses swords, shields, and flails. Men-at-Arms had the problem of being a ripoff knight but expected to basically do the Watch's job. This hopefully acts as a good combination of the two. (Also - could up slots from 3 to 4, went with the lower end as it was suggested.)
- **Watch Barracks Changes** - Did a bunch of misc Watch barracks changes. Firstly, locking the iron gate in the basement so their water supply can't be stolen via sewers. This made no sense as both doors next to it were locked but not the gate. Secondly, armory was redone and does not have a lock only sheriff can open; bog guard can access their armory and so can men-at-arms, so why couldn't Watch? Thirdly, added flavor to the armory. It's less gear than Bog Guard but has some specialty weapons they have skills for (not 'amazing' gear but serviceable, equal to starter weapons you get but smith can still give you better ones) and roof access to the barracks which has a training area on the roof. (See picture below)
- **Fixed Watchman Round-Start Spawns** - Someone.. replaced all the Watchman spawns with Gatemaster ones. This has been amended and fixed. Someone didn't proof-check their work..
image
image

### Mercenary Class Changes
Basically just stopped Desert Rider and Grenzel being separate roles and instead merged them under the single job 'mercenary', both are still selectable **with** the new Steppesman mercenary class; a warrior with no armor training unlike the others but dodge expert and a few perks. Go play steppe Cossack in the fields.

Grenzel's hat now has armor equal to the Desert Rider's head protection, it's really light non-the-less but at least tiny bit of armor (less than a normal leather helm). Also gave Grenzel a choice between Zweihander, as the weapon is no longer 'OP' as it used to be on prior servers, and halberd. Also gave them a buff of sorts by allowing them to have heavy armor to set them apart from the rider and steppesman.

**FINALLY** also added _Mercenary round-start spawns_ that are in town rather than forcing you to walk from bog. Mercenaries actually **HAVE** their own place in town that looked.. bad. But I've redone it some, it's actually a proper semi-inn place with extra parchment for signing contracts and flavor. Also redid its roof, see guard picture and look to left.
image
image

### Shield Skill
Basically, before shields had a stupid amount of defense making all users, anyone who used them, completely trained in how to parry 99% of attacks with a shield merely by holding one. Now, shield skill exists. Shields had their defensive values lowered, **but** the solution? Shield skill acts as a defense modifier to shields, making your parry chances (and shield bashing) better as it levels.

To level, just start parrying or bashing people! Or go hit a dummy, if you're lame and boring.

### Misc Changes
Knight Errant is now a thing for adventurers, a rare knight class akin to the original regular knight role but without the lords heraldry. This was requested to make knights a thing but not have to adhere to the King and solve a bit of the issues people were having. This was requested by a few players + staff as a solution; will have to see how it goes.

At worst can be made into it's own stand-alone role rather than an adventurer role choice. (Could make it a 100% pick but keep it limited to guaranteed option on spawn, but unsure if staff want that.)

## Why It's Good For The Game

Simple - **Quality of Life** and **addressing complaints.**

- The garrison system was bad as many garrison types were indistinguishable or served no purpose in comparison to another, having bloated roles but no purpose to them as you had no specialty or could get RnG 'screwed' into a style of combat you may hate alongside tanking your skills for what you do like.
- Idk go read the discord and search 'knight' and see how many complaints you'll see. Personally, as someone who played guard, I kinda understood where they're coming from after seeing knights in action. So, hopefully this is a good compromise.
- Shield skill is **needed** to stop John Nobody from being an unstoppable force with a mere fist and a shield that can block most projectiles and hits. I'll be adjusting the skill as needed.
- Mercenary being separated made.. little sense, this hopefully helps people unite together as bands by having a single role for it.

Note: This was run by the host and other staff members, idea seemed either liked or 'yeah that could work'. So, thus why this PR is made.

### CODE REVIEW

**Comment by Stutternov** [comment]
@Jeff-Dome Hope you don't mind btw as I took ideas from your Royal Guard PR and added it here. I was asked to 'do it all in one PR' by staff.

**Comment by Stutternov** [comment]
Bunch of errors I'm noticing now that I can test it; fixing up some.

**Comment by coffeecoffeecoffee** [comment]
The mercenary changes aren't appreciated, feel unneeded and sounds wholly unfun. I am not a fan whatsoever.

**Comment by Stutternov** [comment]
> The mercenary changes aren't appreciated, feel unneeded and sounds wholly unfun. I am not a fan whatsoever.
> 
> Edit: Wait, do you mean you _got rid of grenzelhoft and desert riders to roll them into one mercenary class, the Steppesman,_ or did you make all three selectable classes, with a new Steppesman who has dodge expert but no armor training? The former is a serious negative change and the latter actually sounds based and fun. I don't see why they needed to be rolled into the same job title, but that's whatever.

They are all selectable. It's merely merged into one role instead of 2 seperate roles.

It's a 'pick your mercenary!' type. Same exact loadouts, actually buffed Grenzel a bit and forgot to add it to log.

**Comment by Stutternov** [comment]
Drafting while I get the class selection crap to work right. This.. is not working as expected.

**Comment by Stutternov** [comment]
Right - on testing, this is basically working.

The main issue is the spawns. Watchmen now just spawn at random spawners of any role on the map despite no change to their jobs name really beyond the advance classes. 

Same issue is happening for mercs.

This just needs to be fixed and it'll be good to go.

**Comment by bearrrrrrrr** [comment]
good shit

basically the only people who still want knight are the people who hog the role and should absolutely NOT be the ones playing it

i yearn for a speedmerge

**Comment by coffeecoffeecoffee** [comment]
> > The mercenary changes aren't appreciated, feel unneeded and sounds wholly unfun. I am not a fan whatsoever.
> > Edit: Wait, do you mean you _got rid of grenzelhoft and desert riders to roll them into one mercenary class, the Steppesman,_ or did you make all three selectable classes, with a new Steppesman who has dodge expert but no armor training? The former is a serious negative change and the latter actually sounds based and fun. I don't see why they needed to be rolled into the same job title, but that's whatever.
> 
> They are all selectable. It's merely merged into one role instead of 2 seperate roles.
> 
> It's a 'pick your mercenary!' type. Same exact loadouts, actually buffed Grenzel a bit and forgot to add it to log. Mercenaries are rarely filled as separate classes anyway; slots can merely be increased for mercenary if this is an issue. This makes it a bit less bloaty as these mercs are balanced to be options compared to each other.
> 
> Also, Steppesman has worked well on other servers with no armor training due to dodge expert and speed + their shield training to parry. Can at least give it a test-run.

That actually sounds good to me then, sorry for the initial knee-jerk reaction!

**Comment by bearrrrrrrr** [comment]
> To others, I disagree severely about this characterization of knight players, and I say that as someone who doesn't play it myself. What's with the blatant salt? They're _meant_ in their current iteration to be a highly geared, combat-ready role, and there's nothing wrong with that, there needs to be someone like that for the king. I don't know about the merge of MAA and knight, so no comment there, but I think it's goofy to hate on them. There are dumb ones just like any other role.

unironically more than a fifth of our tickets are for knights, a 2-person role, on an 80-person server. the player quality is consistently garbage due to the fact the job has ultimate combat skills, ultimate social status, and ultimate social flexibility. the idea is that they act like king's guards, or palace guards, but they act more like Cargo Tech Thug #992 that also are nobles and immune to most of the RP and combat balancing acts that other jobs adhere to

their design is garbage and there is a good reason every other RT server sans one has gotten rid of them

**Comment by coffeecoffeecoffee** [comment]
> > To others, I disagree severely about this characterization of knight players, and I say that as someone who doesn't play it myself. What's with the blatant salt? They're _meant_ in their current iteration to be a highly geared, combat-ready role, and there's nothing wrong with that, there needs to be someone like that for the king. I don't know about the merge of MAA and knight, so no comment there, but I think it's goofy to hate on them. There are dumb ones just like any other role.
> 
> unironically more than a fifth of our tickets are for knights, a 2-person role, on an 80-person server. the player quality is consistently garbage due to the fact the job has ultimate combat skills, ultimate social status, and ultimate social flexibility. the idea is that they act like king's guards, or palace guards, but they act more like Cargo Tech Thug #992 that also are nobles and immune to most of the RP and combat balancing acts that other jobs adhere to
> 
> never have i ever gotten on and thought 'ugh, the SOILSON is acting out again,' or 'ugh, i have ANOTHER ahelp about the acolyte'. with knight? oh, yes. i was ambivalent about the role until today tbh, when we tried to 'save' it by making it an antag-lite role and knight players just used it to be even more validhungry, fraggy, and shitty
> 
> their design is garbage and there is a good reason every other RT server sans one has gotten rid of them. we have really tried our best to save the role. it is time for them to go.

that just sounds like a player and policy problem of people who aren't making the barest attempt to roleplay, on a roleplaying server. having been staff on servers with LOTS of these issues in the past, with _experience_ gutting the role is never the solution - it's a blessing honestly that it's _unveiling all the problem players_, imo.

but whatever - I don't play knight, I play mercenary!

**Comment by Stutternov** [comment]
> @Stutternov
> 
> Personally, I like the idea that the Royal guards are elevated peasants in the standing army. But that's me. I don't see why every high role needs to be a noble because no-one actually really roleplays that out.

I personally do too, I am debating if I want to keep them as knight without the noble role (since knighthood didn't always inherently mean nobility depending on historical context as is) but I do not wish to ruin players knight RP for those who enjoy it.

May just add in these are 'lower-nobles' and some may be a rare 'commoner' given knighthood; allow a mix of roleplay for it.

**Comment by Stutternov** [comment]
> I mean, I would always like for the selected archtypes on the job selection screen, not job classes when you spawn in. For example, I hate to use it but, lifeweb.
> 
> And just have two archetypes:
> 
> Commoner
> 
> Noble-born.

While I could do this it may be a tad awkward given the way their roles work is by actual skills and stats currently. I could add a 3rd archtype but I'm not sure what would fit with 'Heavy-knight' and 'Foot-knight' other than something like 'Lesser-knight' or something; but not sure what skills I'd give them to be at least 'equal' to the others stat/skill wise.

**Comment by Stutternov** [comment]
Fixed whoever's thing broke guard spawns, since it's now working - **the draft ends.**

image

**Comment by coffeecoffeecoffee** [comment]
Oh fucking god, the royal guard change is turning out horribly

**Comment by coffeecoffeecoffee** [comment]
oh nice this actually broke mercenary spawns too

**Pull request merged**
