### PR TITLE
Removes some restrictions from alternate Court Magician outfit + makes it reflected in loadout.

### PR DESCRIPTION
**Pull request by faaaay**
## About The Pull Request

Currently, Court Magicians who are old get stat changes, and if they're also Humen they're given a different outfit with a hat. This keeps the age restriction, but removes the Humen-exclusivity. Also moves around an if statement so that this outfit change is reflected on the character setup screen.

## Why It's Good For The Game

We're not as human-centric as this codebase used to be and the robes look neat.

### CODE REVIEW

**Comment by faaaay** [comment]
image

**Comment by Tree445** [comment]
Merge conflict

**Comment by faaaay** [comment]
Fixed! Marking as such now :3c

**Comment by faaaay** [comment]
augh, i don't remember how to do that, but it IS fixed

**Comment by Tree445** [comment]
Still showing conflicts

**Comment by faaaay** [comment]
> Still showing conflicts

like I said, I don't remember how to mark it as fixed, but it is.

**Comment by Tree445** [comment]
image
I can't merge it. Might have to open a new PR.

**Comment by faaaay** [comment]
Understood, will see what I can do later todayOn 2 Sept 2024 04:57, Apple ***@***.***> wrote:
image.png (view on web)
I can't merge it. Might have to open a new PR.

**Comment by Tree445** [comment]
Re-did this PR in #437

**Pull request closed without merging**
