### PR TITLE
Ranger Subclass "Glade Walker" [DRAFT]

### PR DESCRIPTION
**Pull request by AllCorruptingWyrm**
## About The Pull Request

Grants people to have a proper Ranger experience by giving them a ranged ONLY class with Dendor's spells.

## Why It's Good For The Game

Fluff class for people who wanna play a Ranger with the con that they absolutely can not do melee combat.

### CODE REVIEW

**Comment by AllCorruptingWyrm** [comment]
i'll probably give them a -1 to STR.

**Comment by faaaay** [comment]
Suggested some edits, but they'd need to be tested

**Comment by AllCorruptingWyrm** [comment]
> This is druid with a better stat line, better traits, and a full combat skilll set. it even has a druid's alchemy skill
> 
> heck no this is the acolyte < cleric thing on steroids

They are losing str and a few other things. And dodge expert.

**Comment by Ruediger4** [comment]
This does fuck a bit w/druids, I think. Also **4 crossbow whilst keeping the 50% chance on Master bow and 25% Legendary bow**, on top of Tracking 4 and alchemy 3?

I'd say genuinely trim the hedges *significantly* because It'd probably, highly likely, fuck over druids.

Also dumb question but ya tested it in your end to see if it works, right?

**Comment by Decoy1240** [comment]
Honestly what I am hearing from everyone is buff Druid a bit then add this draft.

**Comment by AllCorruptingWyrm** [comment]
will become a templar loadout if dendor when I get to it

**Pull request closed without merging**
