### PR TITLE
[Draft] Re-Map

### PR DESCRIPTION
**Pull request by Tree445**
## About The Pull Request

Shrunk the map 100 y tiles, adding adventurer guild as new latejoin spot. Also spawn for adventurer. Attempting to merge Innkeeper, Mercenary, Shopkeeper all into the same building to reduce size of town and better centralize rp to a single hub. I have plans to reduce the size of the castle in the future aswell. If anyone wants to give feedback or take a crack at improving my design feel free. I intend to remove the extra buildings and replace it with this one.

I also intend to get rid of the watchmen base since we never even see any watchmen players. It would probably be a good idea to merge watchmen with either bogguard or royal guard.

Bog
image

Ground floor:
image
Basement (Adventurer Spawn):
image
Top Floor (Merc Spawn):
image

### CODE REVIEW

**Comment by RikaruZW1** [comment]
Hold on, thiiiiis might shitcan a dungeon or two, such as Wraith Island unless their travel points are getting moved.

**Comment by Tree445** [comment]
> Hold on, thiiiiis might shitcan a dungeon or two, such as Wraith Island unless their travel points are getting moved.

Already properly moved all the dungeons. Only thing that got scrapped were the multiple little buildings/camps with mobs in them. Going to stick to keeping any form of loot acquisition to high quality dungeon design.

**Comment by Byosfeer** [comment]
Centralizing RP to a single hub seems like a well-meaning but shortsighted idea, inn, merchant, and mercenaries have such different role that it's not logical from a gameplay and lore standpoint in my eyes to push them all into one spot. Seems like an effective way to deaden town as a whole.

**Comment by FatCatSS13** [comment]
Is nobody going to mention how this completely ruins the inn? Where are the private rooms to sell? And everything else that the inn \should\ have? It's cool that you're trying to make an 'RP hub' of sorts but this just completely shafts the inn and also innkeep.

**Comment by Tree445** [comment]
> Is nobody going to mention how this completely ruins the inn? Where are the private rooms to sell? And everything else that the inn \should\ have? It's cool that you're trying to make an 'RP hub' of sorts but this just completely shafts the inn and also innkeep.

image

I didn't include a screenshot of the basement floor, but that is where adventurers spawn, and also 3 Inn rooms are here. As I continue to make changes, I'll most likely end up putting the brothel 1 floor lower, and adding the fancy rooms somewhere, not on the ground floor.

**Comment by Tree445** [comment]
> Centralizing RP to a single hub seems like a well-meaning but shortsighted idea, inn, merchant, and mercenaries have such different role that it's not logical from a gameplay and lore standpoint in my eyes to push them all into one spot. Seems like an effective way to deaden town as a whole.

Same problem as mentioned above. Shop is far too big for what it accomplishes with the amount of space allotted to the role, and Mercenary building is used maybe once every 20 rounds and functions horribly for it's intended purpose which is to be a front desk/base for mercenaries to be hired from... In the 200+ rounds, we've had one player use it for that purpose, and otherwise it's hardly ever used at all.

**Comment by Tree445** [comment]
image
Design change for base floor

**Comment by FatCatSS13** [comment]
> > Is nobody going to mention how this completely ruins the inn? Where are the private rooms to sell? And everything else that the inn \should\ have? It's cool that you're trying to make an 'RP hub' of sorts but this just completely shafts the inn and also innkeep.
> 
> image
> 
> Update on the basement floor,but that is where adventurers spawn, and also 3 Inn rooms are here. I'm reducing the amount of rooms available since they are absolutely never remotely filled. On any round, at best 1 or 2 of the regular rooms are taken. As I continue to make changes, I'll end up putting the fancy rooms somewhere not on the ground-floor, and likely add the brothel 1 z-level lower than the basement.

untrue, evidently you've never played or seen someone play innkeep before as i sell a \lot\ of the rooms, i usually sell around 3-4 rooms on a slow-ish round and a lot of the time all of them are sold if the server is highpop, and if you're going to reduce the amount of rooms, at least add some variety to them, they look extremely bland.

**Comment by Tree445** [comment]
> > > Is nobody going to mention how this completely ruins the inn? Where are the private rooms to sell? And everything else that the inn \should\ have? It's cool that you're trying to make an 'RP hub' of sorts but this just completely shafts the inn and also innkeep.
> > 
> > 
> > image
> > Update on the basement floor,but that is where adventurers spawn, and also 3 Inn rooms are here. I'm reducing the amount of rooms available since they are absolutely never remotely filled. On any round, at best 1 or 2 of the regular rooms are taken. As I continue to make changes, I'll end up putting the fancy rooms somewhere not on the ground-floor, and likely add the brothel 1 z-level lower than the basement.
> 
> untrue, evidently you've never played or seen someone play innkeep before as i sell a \lot\ of the rooms, i usually sell around 3-4 rooms on a slow-ish round and a lot of the time all of them are sold if the server is highpop, and if you're going to reduce the amount of rooms, at least add some variety to them, they look extremely bland.

I'm not the best at decorating things, that is why I previously mentioned that anyone is free to download the draft mapfile and make edits to it. Feel free to contribute if you're able to.

image
As of now, this is the latest version of the top floor, but I'm struggling with making a good design for the second floor considering it's supposed to be for mercenaries, but also the person who designed the first floor gave it two staircases leading up, and I feel there's too much space upstairs for just mercenaries with the current redesign of the original design.

**Comment by Tree445** [comment]
For the most part, the draft is almost complete. The layout has been set more or less. 
To-Do list:
Interior of:
- Mage Guild
- Inn
- Castle
The Noble Manor needs work.
I need to finish the south-east corner of town.
Details need to be added to the town overall, including re-adding the pipes that let you move from rooftop to rooftop, and adding more detailed roads that look broken off and worn down.

With the finished product, we reduce the Map size from 255x400 to 255x290.

I still think we can continue to reduce the size of the map even further in the future, but this should be a good starting point and a baseline for establishing a map that is a lot more unique to Hearthstone.

**Comment by FatCatSS13** [comment]
> > > > Is nobody going to mention how this completely ruins the inn? Where are the private rooms to sell? And everything else that the inn \should\ have? It's cool that you're trying to make an 'RP hub' of sorts but this just completely shafts the inn and also innkeep.
> > > 
> > > 
> > > image
> > > Update on the basement floor,but that is where adventurers spawn, and also 3 Inn rooms are here. I'm reducing the amount of rooms available since they are absolutely never remotely filled. On any round, at best 1 or 2 of the regular rooms are taken. As I continue to make changes, I'll end up putting the fancy rooms somewhere not on the ground-floor, and likely add the brothel 1 z-level lower than the basement.
> > 
> > 
> > untrue, evidently you've never played or seen someone play innkeep before as i sell a \lot\ of the rooms, i usually sell around 3-4 rooms on a slow-ish round and a lot of the time all of them are sold if the server is highpop, and if you're going to reduce the amount of rooms, at least add some variety to them, they look extremely bland.
> 
> I'm not the best at decorating things, that is why I previously mentioned that anyone is free to download the draft mapfile and make edits to it. Feel free to contribute if you're able to.
> 
> image As of now, this is the latest version of the top floor, but I'm struggling with making a good design for the second floor considering it's supposed to be for mercenaries, but also the person who designed the first floor gave it two staircases leading up, and I feel there's too much space upstairs for just mercenaries with the current redesign of the original design.

i'll try taking a crack at it soon, although it would probably be better if you just didn't combine all of these buildings, specifically the merchant's

**Comment by Tree445** [comment]
> > > > > Is nobody going to mention how this completely ruins the inn? Where are the private rooms to sell? And everything else that the inn \should\ have? It's cool that you're trying to make an 'RP hub' of sorts but this just completely shafts the inn and also innkeep.
> > > > 
> > > > 
> > > > image
> > > > Update on the basement floor,but that is where adventurers spawn, and also 3 Inn rooms are here. I'm reducing the amount of rooms available since they are absolutely never remotely filled. On any round, at best 1 or 2 of the regular rooms are taken. As I continue to make changes, I'll end up putting the fancy rooms somewhere not on the ground-floor, and likely add the brothel 1 z-level lower than the basement.
> > > 
> > > 
> > > untrue, evidently you've never played or seen someone play innkeep before as i sell a \lot\ of the rooms, i usually sell around 3-4 rooms on a slow-ish round and a lot of the time all of them are sold if the server is highpop, and if you're going to reduce the amount of rooms, at least add some variety to them, they look extremely bland.
> > 
> > 
> > I'm not the best at decorating things, that is why I previously mentioned that anyone is free to download the draft mapfile and make edits to it. Feel free to contribute if you're able to.
> > image As of now, this is the latest version of the top floor, but I'm struggling with making a good design for the second floor considering it's supposed to be for mercenaries, but also the person who designed the first floor gave it two staircases leading up, and I feel there's too much space upstairs for just mercenaries with the current redesign of the original design.
> 
> i'll try taking a crack at it soon, although it would probably be better if you just didn't combine all of these buildings, specifically the merchant's

image

image
Latest version
Planning to move adventurer and merc spawns underneath the Inn.

image
Merc is going to be north of the current inn basement area. And I ended up with 3 extra inn rooms downstairs since all of them were moved upstairs.

**Comment by FatCatSS13** [comment]
> 
> Latest version Planning to move adventurer and merc spawns underneath the Inn.
> 
> image Merc is going to be north of the current inn basement area. And I ended up with 3 extra inn rooms downstairs since all of them were moved upstairs.

this is fine, the fancy rooms look a bit uninspired and i also notice the lack of a private suite for the innkeeper. i **still** think that merging the merchant's of all things with the inn is a bad idea.

**Comment by RikaruZW1** [comment]
Yeah seeing the map changes tested in action, and I'm gonna have to take back any support I have for this. I was able to clear four of the five dungeons in an hour and a half. That's just, no. I do not like this. Also parts of the map are really unpolished and janky, and there's only one Meister available in the entirety of the town. Heck I bet the stockpile got shitcanned. *sigh*.

**Pull request closed without merging**
