### PR TITLE
Adds Pilgrim Roles to Towner, Disables Pilgrim

### PR DESCRIPTION
**Pull request by Stutternov**
## About The Pull Request

Basically nothing has _really_ changed in this other than tidying-up the role list and stopping pilgrims/towners from being adventurer role spawns. Pilgrim roles were identical to towner baring a few, those being the master roles (smith, woodcutter, peasant, etc) and the 'noble' role - which has been flat-out disabled because we have noble guest; pilgrim noble was an objectively worse and useless version.

All of those roles (besides noble) have been moved to Towner. Pilgrim is still, technically, a thing - it's just ONLY assigned via migration wave now. And all towner stuff like minstral are able to be pilgrim loadouts now. Pilgrims are, effectively, wandering towners. (Could maybe make towners not be late-joinable, and instead spawn as pilgrims, but idk that just makes it confusing.)

Also - only real major changes here, got rid of the gender-based stat bonuses on the master roles and minor stat tweaks. Before women would get worse stats than the male counterpart for - whatever reason. Now just standardized it to use what males got but it gives it regardless of gender now, only keeping the gender-specific clothing instead. Some roles, like master woodcutter, did get strength lowered slightly but got given endurance, and some love was given to peasant due to how bad their stat-spread was.

## Why It's Good For The Game

Following reasons:
- Confuses people less what the difference between towner and pilgrim are.
- Less role-bloat on the spawn/late join screens.
- Towners now have the proper towner classes, like master level worker classes that only pilgrim had before. And vice-versa for odd roles like minstrel and drunkard for pilgrim.
- Some roles had the dumb 'women r bad at dis' stats. Adjusted, made it not base stats off gender.
- Some roles had either high stats/skills (Master woodcutter) while others (peasant) were kinda low. Tried to touch them up a tad.
- Pilgrims still have use as late-join migrant waves.
- Pilgrims no longer choose adventurer loadouts to be, quite literally, adventurers with just a lower chance. (Staff and players, again, requested this. I left it initially to avoid being too heavy handed; but it was requested.. again..)

### CODE REVIEW

**Comment by Stutternov** [comment]
> Personally, I'd like a more elegant way of doing legendaries. If it pops in your list you'd feel kind of off _not_ taking it, even if that's not on brand for your persona. Rather have it be a chance to proc when you take the main class, although I suppose that'd involve editting it into every main class which is eugh.

That's more or less outside the scope of this PR as I'm merely doing clean-up and fixing towner role just being objectively worse pilgrim role; when they.. should realistically be the same. (Towner just shouldn't exist but does because of migrant system of latespawn pilgrims vs late spawn towners.)

I would prefer just making them equal. I could fully just disable master roles but it feels pointless to do so, and personally I have in the past had the ability to pick one of these while playing Rogue servers and passed it up. Play a character, if you choose the role because you want the rare pick - that's more or less on you.

**Comment by faaaay** [comment]
The only potential issue I can see here is that, unlike Towners, Pilgrims don't have a bank account by default and this would make that no longer an option. Not sure if that's something people care much about. Looks like it could be a good change overall.

**Comment by Dumbdumn5** [comment]
Little odd having the illiterate dendorite bog nudists spawning in town with a bank account, or tradesman gimmicks who want to set up shop near the tribe/out in the bog, personally? Otherwise, very happy to finally have some towner stats brought up to par.

**Comment by Stutternov** [comment]
> Little odd having the illiterate dendorite bog nudists spawning in town with a bank account, or tradesman gimmicks who want to set up shop near the tribe/out in the bog, personally? Stand by the same mentality I had for the cleric changes. If we want people to play owner, make town gameplay more interesting, not the only option. I don't see Pilgrim as role-bloat, more an opportunity for roleplaying skilled workers or laymen without answering to Rockhill or living under the crown. While I won't support its removal in the slightest, I'm otherwise very happy to finally have some towner stats brought up to par and the class selection fixed!

Pilgrims have the **exact** same roles as town besides the useless noble role (we added noble guest) and the legendary role choices, which weren't on town for some reason.

You already **can** be a nudist with a bank account if you wanted, you can select nudist as a towner. Pilgrim is, quite literally, a bloat role. Towner was an added role for idk what reason given towners _are_ pilgrims and someone Just added adventurer classes to it for whatever reason.

**Comment by Dumbdumn5** [comment]
> Pilgrims have the exact same roles as town, they both have the CAT_PILGRIM tag besides the useless noble role (we added noble guest) and the legendary role choices, which weren't on town for some reason.
> 
> You already can be a nudist with a bank account if you wanted, you can select nudist as a towner. Pilgrim is, quite literally, a bloat role. Towner was an added role for idk what reason given towners are pilgrims and someone just added adventurer classes to it for whatever reason. Prior to whatever added towner, Pilgrim was the role you selected to do work.
> 
> There's not even a cost to opening a bank account; you just walk up to an ATM and it opens one for free. There's really nothing unique to it unless you want me to make towners just - not start with one? That's the only difference between a pilgrim role and a towner. Pilgrims also still exist on migrant waves (because I'm too lazy to go overhauling that system) but they'd actually spawn as migrants.

Lacking a bank account prevents the rod of the master working on you and a few other checks iirc that involve you having a bank. Spawning in the bog also puts you closer to the tribe, lets you better play the fantasy of a bog-dweller or otherwise uninvolved party in the grander 'politics' of each faction, and leaves you answerable to absolutely nobody. Opting to open a bank account or not in-game for no cost isn't the issue I'm concerned with.

Just because they have the same roles available doesn't make them fulfill the same _idea_, bloat roles are roles that offer literally no difference in gameplay, serve zero purpose beyond something solely aesthetic, or that have otherwise little to no mechanical differences. A spawn location on the complete other side of the map, that gives players a number of more mundane thematic choices for their backstory that don't lean into the adventurer power fantasy, and that gives players the option to not be involved in either the town or the tribe's gameplay loop is substantial reason enough for it to exist as its own 'thing'. 

Given the example, spawning as a towner with the nudist challenge class makes... little thematic sense when you're more or less a mildly unhinged bog-dweller worshipping a nature god that's equally madenned, much like playing as a travelling carpenter, chef, or smith wouldn't make near as much sense if you spawned well within city limits, with an established bank account, and already as a member of a town you may not even want your character to've been a part of in the first place under direct rule of the local lord.

While mechanically identical otherwise, I feel those opportunities are important to let people explore.

**Pull request merged**
