### PR TITLE
Noir changes mix 1

### PR DESCRIPTION
**Pull request by EaglePhntm**
## About The Pull Request
Stuff based on requests and whatever i thonk.

- makes alcohol vice message clearer as "time for some booze" rather than "time for a drink" as if implying need to drink water.
- Reduces SKILL_EXP_NOVICE by 25 to 50 so people can get started with crafting and stuff even easier, was request but maybe good idea.
- Tried to stop the vote spam and keep its original delay from round start.
- Footjob can now be performed while the performer has boots/shoes.
- kills twig platforms
- allows stamina for zombies because that shit is fucked.
- removes zombie force ghosting
- reduces the hunger and dehydration rate to hopefully stop the annoying constant hunger and thirst, moreso considering how there is often issues with food even in town likely due to lack of players most rounds, sustaining on a silver cost apples too often.
- Makes barkeep renamed to Innkeep as the owner of the inn.
- Makes barkeep be more like an ex-adventurer based on the big old sword at the wall of the inn, giving 3 sword skill and unarmed/grappling.
- ~~Funny small sex healing 0.01 to fire, brute and oxy every act, cause it may be funny if utilised. Only works if buckled to bed. should heal 1 points brute every 4 times it trigger, 1 fire every 10 times.~~ sigh, asked to be replaced by hunger regen.
- Removes non-churchie forced god picks for more freedom. Idk how this will end.
- Makes some HIS pronouns in sex mechanics to THEIR so it works for most.
- Halves time it takes to take out compost.
- makes subtypes of the glass pot so crafting a stone and iron pot is properly named and described now.
- adds stone blacksmithing tools so its no longer a paradox for blacksmiths to need blacksmiths to do blacksmithing.
- adds stone pickaxe thats barely better than a stake but likely more durable.
- fixes for nightman missing var since the other PR waited so long it became obsolete.

Will likely need to see how zombie ghosting and stamina changes go, and also about the no-forced god stuff.

it builds fine i swear 
image

## Why It's Good For The Game
It's a mixed bunch, feel free to discuss specific changes if you are a maintainer.

### CODE REVIEW

**Comment by CVSthePharmacy** [comment]
me jerking my schlong to heal after I kill a man, yeah this is toooooootally balanced bro, congrats on making sex the meta, dumbass.

**Comment by EaglePhntm** [comment]
except it is funny, although good luck using it as a proper means to heal it heals like 0.01 damage each time it acts. Maybe try reading the code before sliding some yappucino over here.

**Comment by Erwbrad** [comment]
I suggest that you make a status effect for jerking off called "PNC" - but it does not work for sex, and it gives you +2 INT at the cost of -2 fortune (for sinning)

**Comment by EaglePhntm** [comment]
> > except it is funny, although good luck using it as a proper means to heal it heals like 0.1 damage each time it acts. Maybe try reading the code before sliding some yappucino over here. It also now checks for being buckled to bed although it doesnt really work rn
> 
> Funny doesn't mean it should be merged. Get real. -0.1 for jerking my penis, is both a bad change and makes zero sense gameplay wise and generally situation wise. It makes sense zero, and it shouldn't be added because of that fact alone.

image

**Comment by EaglePhntm** [comment]
It's too ineffective to be usable as a meta compared to sleeping, stop yapping son. If everything is added cause they contribute to something greater this would be tgmc medieval edition.

**Comment by Stutternov** [comment]
truly a needed mechanic, sex healing. we’ve peaked, chat, an incentive to erp.

**Comment by Erwbrad** [comment]
> truly a needed mechanic, sex healing. we’ve peaked, chat, an incentive to erp.

"Helllo there, madamesoille, I would like to heal you. Does thou accept thine pintle unto thine reproductive gland?"

**Comment by bearrrrrrrr** [comment]
kinda ehhh on sealing (sex healing)

**Comment by EaglePhntm** [comment]
its vital trust me.

**Pull request merged**
