### PR TITLE
Simple Fix

### PR DESCRIPTION
**Pull request by WWWWW-Git**
This one simple fix will drastically increase the server's quality.

### CODE REVIEW

**Comment by Stutternov** [comment]
image

**Comment by Jul-Jul** [comment]
Agreed. Good change.

**Comment by Troopermoores** [comment]
Another "let's not make the other roles fun let's hurt the role people are enjoying because who needs a player base amiright?"

**Comment by EerieDream** [comment]
First pilgrims, now adventurers. Gvlp.

**Pull request closed without merging**
