### PR TITLE
Update motd.txt

### PR DESCRIPTION
**Pull request by ButtercupFantasy**

### CODE REVIEW

**Comment by Stutternov** [comment]
No idea who this is but funnily based pr

Doing gods work.

Apple/Kiet pls speed merge this while you continue hiding what Ckeys your prior used and instant banning me for reporting it to staff.

**Comment by AllCorruptingWyrm** [comment]
Can I be included on the reddit thread post please?

**Comment by n3tis** [comment]
hey mom that's me

**Comment by ChungusGamer666** [comment]
gemmy

**Comment by Cybernov117** [comment]
Can you guys stop shitting the github for once.

**Comment by Stutternov** [comment]
Absolute cinema.

**Review by Cybernov117 — APPROVED** [review]
Fuck you all, I just wanted a server where I can be myself, already had to deal with the milk posting you obsessive creeps.

**Pull request closed without merging**
