### PR TITLE
Acolyte Update Change

### PR DESCRIPTION
**Pull request by Merek2**
## About The Pull Request

Adjusted skills, did not give them more than cleric, although the church has a few more patron roles. I only allowed patron with miracles and defined purpose that are played by people. I added Eora although note that she still does not get her own prayers so it is really limited. Also gave armor trait and a better belt as well as a basic weapon. The weapon isn't as great as the cleric.

## Why It's Good For The Game

This basically gives the acolyte a few more skills and traits that make it possible for them to be on almost equal footing with the cleric. It's mostly so people will think about playing a acolyte, which was limited by a lot of things. They are not a full on role made with combat in mind, but they can general fight as well as a cleric.

### CODE REVIEW

**Comment by EaglePhntm** [comment]
well giving acolytes more skills and prayers will fix that

> I think this is more an issue with adventurers being unlimited than acolytes. Adventurers are just more attractive roles, generally.
> 
> Why spawn as an acolyte when you can spawn as acolyte plus with half-plate and mace skills. It's a literal no-brainer. Or for example, Crusader. Why spawn as an acolyte when you can be a frag-role and have free shit.

**Comment by oprimeolt** [comment]
why would acolytes need plate armor skills?

**Comment by Merek2** [comment]
I mean it's this or take armor away from cleric but I'm not touching cleric also unless staff wants me to.

**Comment by Merek2** [comment]
I changed armor, with acolyte only getting medium. They are still a class that should get something combat wise. Not having any armor training at all wouldn't make a lot of sense.

**Comment by Wesreidau** [comment]
I struggle to see the acolyte as something other than a _light armor class_ who remains in the back with _spells supporting the front_ line. Templars are the tanks, and Paladins are discount Templar. Clerics are what don't fit, because nothing like them is in the Church. I might also be wrong, but it seems nothing like an acolyte is an adventurer either. This I'll mark as a nebulous ?.

A proposal I worked on with another was floated for a Cleric-like 'Vestal' as a Church class back on Blackstone. The intention was to be a medium-armor mace class for the church who aligns with cleric; it was an all-female role to match the templar's all-male. Alongside this would be getting plate training off the Cleric, as frankly that is what screws with the balance on this, the only plate-armored adventurer to my knowledge. I can dig for the details by request.

Ideally I'd see...

In order of miracle powers, ascending: Templar/Paladin, Vestal/Cleric, Acolyte/ ? , Priest.
In order of martial power, ascending: Priest, Acolyte / ? , Vestal/Cleric (medium armor, journeyman), Templar/Paladin (plate armor, expert).

Debuffing the cleric to no longer spawn in half-plate with plate training would reduce the number of players picking it for stats, and adding a 'church cleric' to the church simultaneously will shift adventurers to a 'real job'.

**Comment by Merek2** [comment]
Alright. No armor training, and I changed a bit of the combat skill, though I'm giving them enough for self-defense for now and giving alchemy and all of the other stuff since it's still more 'support' than they had before. This should make them at least more support than they were and give them at least the ability to self-defend in cases of NPC, and basic hunting.

**Comment by Merek2** [comment]
Updated to work with the patron change Eora

**Comment by ACESTOACES** [comment]
WHAT DID THE CLERICS DO TO DESERVE THIS…

**Comment by Joe-clod** [comment]
as long as you don't touch or buff my templar I am happy, cuh.

**Pull request closed without merging**
