### PR TITLE
Pillory Patch from Ratwood

### PR DESCRIPTION
**Pull request by Gardelin013**
-Pillories have latches now;
-They can be latched/unlatched by anyone (RMB), but also can be locked/unlocked with the key; 
-Locked pillories can be unlocked with the right key only; 
-Properly working lockid.

-Set density to 0 after buckle so people can throw stuff at the victim.

### CODE REVIEW

**Comment by Wesreidau** [comment]
... Tangental, but any idea why throwing rocks at pillories hit the pillory and not the prisoner? This isn't the case with crosses.

**Comment by Gardelin013** [comment]
> ... Tangental, but any idea why throwing rocks at pillories hit the pillory and not the prisoner? This isn't the case with crosses.

I'll look into it a bit later

**Comment by Stutternov** [comment]
> ... Tangental, but any idea why throwing rocks at pillories hit the pillory and not the prisoner? This isn't the case with crosses.

It's because the pilory has density, if density is 0 it'll go through.

**Comment by Gardelin013** [comment]
> > ... Tangental, but any idea why throwing rocks at pillories hit the pillory and not the prisoner? This isn't the case with crosses.
> 
> It's because the pilory has density, if density is 0 it'll go through.

oh well changed density to 0 then

**Comment by sheetofseaweed** [comment]
Maybe set density to 0 only when someone is locked in it? So that people don't walk through them normally.

**Comment by Gardelin013** [comment]
> Maybe set density to 0 only when someone is locked in it? So that people don't walk through them normally. Just a suggestion, though.

already done

**Pull request closed without merging**
