### PR TITLE
Mortar & Pestle Update, Increases Trekker's Delight Availability

### PR DESCRIPTION
**Pull request by EtheoBoxxman**
## About The Pull Request
Allows Mortar & Pestle to produce mill_results as priority. Allows you to get gem dust, salt, etc.
Adds trekker's delight potion to merchant's consumables, next to the other potions
Gives ranger starting trekker's delight and starting alchemy to make more, assuming they can get the materials to do so.

## Why It's Good For The Game
Mortar & Pestle change was something I wanted to do before, but couldnt figure it out. It'll make it easier for future bootleg alchemy, once I work out a way to get that done.

### CODE REVIEW

**Comment by Tree445** [comment]
I'm against giving Bog trekking to ranger/witchunter for the reason that they are not natives to RockhilL. They are adventurers from elsewhere. Bogmen and Tribals are defacto natives who know how to handle the bog more than anyone else. Giving it to inquisitor under the assumption that they're adept at hunting creatures through the bog aswell.

However, I am all for throwing a few bogtrekking potions into their loadouts.

**Comment by EtheoBoxxman** [comment]
> I'm against giving Bog trekking to ranger/witchunter for the reason that they are not natives to RockhilL. They are adventurers from elsewhere.

Witchhunter's whole repertoire is the same as inquisitor, with the difference being inquisitor is ordained by the church- This is the only reason I added to that role.
Ranger, it makes total sense that they at least get it, because that's how rangers work in every tabletop things here have been taking inspiration from- Read, Pathfinder's woodland stride or DND's natural explorer features.

I'd argue that if rangers at least are given the potion, they should also have the alchemy skill to be able to make more.
Either option accomplishes the same boon, though.

**Comment by Tree445** [comment]
From my perspective, I view bog_trekking as an homeland advantage, similar to American Revolutionaries vs British. Foreigners dont know the ins and outs of the bog and how to traverse it. While a ranger may be familiar with the woods, they arent familiar with the bog. If there was a towner version of ranger, I would be more prone to give the trait to them. Otherwise a foreign ranger is going to have a harder time getting adjusted. 

It would be good to sprinkle some big potions across the map for everyone, not just rangers exclusively. Aswell as adding them to the merchants list of purchasable items.

**Comment by EtheoBoxxman** [comment]
There is a towner version of ranger, technically- The hunter role.
I'll go back through and add bog trekking potions to the shop as well as the ranger's loadout in a bit, though.
I think I'd like to give ranger alchemy so they can be independent on making their own bog trekking potions, though. Thoughts?

**Comment by Tree445** [comment]
Increase the cost to 60. What is the recipe recipe for the potion?

**Pull request merged**
