### PR TITLE
Built the Wall

### PR DESCRIPTION
**Pull request by Wesreidau**
Built the Wall, Again.
Removed bugged wall in merchant window.
Area'd outdoor/town/roofs on Z-5.
Nudged bog house one tile down.

Bog village untouched otherwise; will move in next PR.

## About The Pull Request

Adds the town wall as detailed in https://github.com/Tree445/Hearthstone/pull/248

Slight tweak of murder hole layout based on some gameplay experience.
Uses new Craftstone murder-hole tiles.

## Why It's Good For The Game

1. Adds a curtain wall around the sewer that will prevent AI mobs from running into the sewer ditch and removing themselves from play, a real problem.
2. Provides an exciting set piece for defending the gate from mobs of orcs, vikings, goblins, whatever.
3. Gates start unlocked and can be left unlocked, operated in person by a simple garrison key.
4. Round start does not require opening, IE the bog gate, and the manning the gate provides all comforts of home and great vantage points and communication.
5. Two watchmen can effectively shut down the bridges into town, preventing cutthroats and thieves from easily escaping unless they risk sewer hijinks.
6. Destruction of the gate is no big deal, as a one-wide door is able to be replaced by carpenters.
7. Room to improve with levered iron gates, etc, if the guard or king wish.
8. Posting guards near the town entryways will improve survivability of people who hit an ambush outside of town and run in. No more dragging wolves to the merchant and smith! A guard is right there to help!
9. Have you seen how pretty it is?
10. Guard can eat and sleep in the towers and be right next to the action, able to converse with those coming and going without being isolated, as they are at the bog gate.

### CODE REVIEW

**Comment by faaaay** [comment]
I'm totally in favour of this, but could we possibly see screenshots of the final version of these changes?

**Comment by Wesreidau** [comment]
image
image
image
image
image

Nothing particularly remarkable. Just changes the rough stone murder holes to craftstone, and makes murder-holes appear in pairs since that's a lot more useful.

**Comment by Wesreidau** [comment]
A broader rework of the bog valley pushing it out from the wall and making it more humdrum and ramshackle is in play, I just want to get the wall up first.

**Comment by Tree445** [comment]
#283 is up if you want to put it up around that. I would suggest leaving some gaps in the wall that need reparation as suggested previously in the last Wall PR

**Comment by Wesreidau** [comment]
> #283 is up if you want to put it up around that. I would suggest leaving some gaps in the wall that need reparation as suggested previously in the last Wall PR

Making it so.

Regarding gaps, it appears we've got some already on the sewer Z. I'll add a broken iron grate or two and be sure some sneaky routes exist after the bog village overhaul.

**Pull request closed without merging**
