### PR TITLE
Removes hairstyle and ancestry restrictions for Desert Mercenaries

### PR DESCRIPTION
**Pull request by kyowaaaa**
## About The Pull Request
Removes code that limits Desert Mercenary females to only utilizing three hairstyles. Removes code and list of required ancestries as well, given request of contributors.
Proof of boot/working:  https://imgbox.com/Q3j6dfgt

## Why It's Good For The Game
As of now, I see no "lore" reason for this to exist for the class, especially given the larger customization focus for players/characters on the server. This simply allows users to not be surprised when their hairstyle doesn't match in game.

### CODE REVIEW

**Comment by kyowaaaa** [comment]
If this isn't an acceptable change, I am willing to dig through the hairstyles for more "tomboy" or shorter/managed hairstyles to add to the list instead.

**Comment by bearrrrrrrr** [comment]
seems fine, we removed this with many other roles but i guess this one got missed

**Comment by Stutternov** [comment]
If doing this make the headgarb hide hair.

If you open the front to show your face your hair clips through it.

**Comment by kyowaaaa** [comment]
Certainly. Let me take a look at it.

**Comment by Mannybrado** [comment]
https://github.com/Tree445/Hearthstone/pull/152#issuecomment-2250388238 

In old rogue this was never an issue as there were 2 separate sprites for having a helmet and not having one, but now that all of the ss13 hairstyles were copied in with no thought this system doesn't really work. You love to see it!

**Comment by kyowaaaa** [comment]
https://imgbox.com/7owz1mvl https://imgbox.com/YfgxDQkA
Should be working fine, now.

**Comment by EaglePhntm** [comment]
what the fuck i already did this before, the fuck apple

**Comment by EaglePhntm** [comment]
> seems fine, we removed this with many other roles but i guess this one got missed

na man im pretty damn sure i removed this but it returned somehow it seems

**Comment by EaglePhntm** [comment]
@kyowaaaa remove the forced skin tones too while you are at it then.

**Comment by EaglePhntm** [comment]
thanks bro

**Comment by Tree445** [comment]
Is this removing LALVESTINE/SHALVISTINE, and are the restrictions being removed for males aswell?

**Comment by kyowaaaa** [comment]
Males were not under hairstyle restrictions as per previous code. Ancestry restrictions (var/static/list/canonical_heritage_check_list) was unisex, which was removed with my latest change.

**Pull request merged**
