### PR TITLE
Restore Old Visored Sallet Icons

### PR DESCRIPTION
**Pull request by Wesreidau**
## About The Pull Request

Restores the sprites for sallets and visored sallets to their older style. Slight tweak for appearances. Sallet now uses onmob icons that match the visored sallet profile. Slight tweak of one or two pixels which looked poorly before.

## Why It's Good For The Game

The redone visored sallet sprite had a strange Armet style mouthpiece which was ahistorical and looked very odd.

### CODE REVIEW

**Comment by coffeecoffeecoffee** [comment]
The reason for the visored sallet change is because it now has mouth protection. "Ahistorical" is not a great reason for sprites to contradict their protection values - could you show the sprites?

**Comment by Wesreidau** [comment]
image
image
image

Your sprite change contradicts its protection value.
Historical sallets rarely had breaths, and if they did, used pinholes and not vertical slices in the steel.
A sallet sits far enough forward over a bervor that no breaths are required, although some bervors had breaths in them. These were also pinholes.
I've done enough hobbysmithing and research to go into detail, but I'll spare the discussion.

**Comment by coffeecoffeecoffee** [comment]
> image image image
> 
> Your sprite change contradicts its protection value. Historical sallets rarely had breaths, and if they did, used pinholes and not vertical slices in the steel. A sallet sits far enough forward over a bervor that no breaths are required, although some bervors had breaths in them. These were also pinholes. I've done enough hobbysmithing and research to go into detail, but I'll spare the discussion.

You're showing it with a bervor, which has mouth protection and has it very visibly. In code, I had changed it to protect the mouth to make it viable compared to other sallets - what plans do you have to make the visored sallet visibly cover your mouth, unless you want to remove that protection?

**Comment by coffeecoffeecoffee** [comment]
> Player information is required over being historically accurate.

This. Why not give us a historically accurate alternative and sprite it then? I'm open to my sprite being changed, I really just threw it together to appease Ratwood and got positive feedback from some others. It just needs to either not have mouth protection, making it worse than all the other options, or have mouth protection and have that reflected on the sprite somehow.

**Comment by Wesreidau** [comment]
Okay, then get rid of the mouth protection.

I don't really care. I'll wear it with a bervor anyway.

**Comment by Edgar-Allan-ShitPoest** [comment]
Your last comment reads as a little spiteful, but I personally prefer the new sprite over the old one and you've joked at least that this change is for your own personal 'drip' over balance anyway. I don't think a change should be merged on the basis of your preferences alone when a  lot of work went into creating the new sprite and it actually genuinely looks better than the old one? Plus- historical accuracy is a weak argument in rogue town code all together especially when it comes to armour. 

it's a no from me on this one brotherman

**Comment by glitchbow** [comment]
> > > Player information is required over being historically accurate.
> > 
> > 
> > This. Why not give us a historically accurate alternative and sprite it then? I'm open to my sprite being changed, I really just threw it together to appease Ratwood and got positive feedback from some others. It just needs to either not have mouth protection, making it worse than all the other options, or have mouth protection and have that reflected on the sprite somehow.
> 
> I never really understood historical accuracy in Roguetown design. It was never really accurate to begin with.
> 
> After all, should we remove shylocks and make manual banking a thing because it's historically accurate? It's what level of internal consistency are we willing to accept? All that really needs to matter is does the world setting work with it's internal parts.

This. The game's current food ingredients and recipes are also not 100% historically accurate either but it's still okayish as-is.

"Get rid of this because I don't like it aesthetically" when something improves gameplay is silly. Don't replace the mouth protection ones, Wes, just add your historically accurate ones if you want them. Taking away one when other people are fine with it is silly, just have both.

**Comment by Wesreidau** [comment]
Following the concerns that the icon needs to more clearly communicate mouth coverage I have tweaked the icon to signal this properly.

image
image
image

Now as for the historic argument...

The word used to describe this helmet is 'sallet'. There are hundreds and probably thousands of pictures you can find of 'sallet' helmets online. It is a specific word with a specific meaning. This is a fantasy setting. Fantasy settings often have castles. We often see castles in a certain style, of several towers around one large central tower and a wall linking those outer towers. This follows the real-world pattern of what a castle of the middle ages looks like. A castle might be patterned more like a roman fort or the ringed city of Minas Tirith, but a castle looks like a castle.

We would not, however, expect a castle to not have towers, not have walls, or have them in such an arrangement as to not be defensible. A pile of stones is not a castle. A bunker complex is not a castle. A dungeon is not a castle. Castles, as we can see in every piece of fantasy, look like we expect a castle to be in the time period the fantasy work depicts and the style of the setting.

The Grenzelhoft mercenary looks the way the Grenzelhoft mercenary looks because Grenzelhoft is patterned after the Holy Roman Empire and the mercenaries are patterned after Landsknechts. They have flamboyant hats and puffy sleeves because that is the fashion of the historical pattern they follow. They can be fantasy. They can be an elf or a tiefling or a wildkin or whatever you like as a Grenzelhoft mercenary, but they are still in the pattern of the historical precedent.

We are not a sufficiently divergent in our themes to justify diverging from the historical pattern with a word so specific as 'sallet'. We have the messer sword, which looks like the historical messer. We have the elven saber, which looks like a saber. We have Zybantine gear patterned after Arabian or Bessarabian patterns of arms and armor.

Why then should a sallet not look like a sallet?

The burden of proof is on someone wanting to move the appearance of a thing from its commonly understood form, an appearance specifically defined by its name which is itself a very specific term to describe this very specific pattern of helmet, to another form. You cannot shift that burden of proof. I want an orange to be colored orange. If you want the fruit called 'orange' to be purple because this is fantasy, you would have to give the argument yourself.

The prudent move is to name the new form of this helmet to something else. An Orcish sallet, or a Skullet, or whatever name you please. But not to reshape a thing and make a wholly new style of helmet still using the old name, then resist restoring the form to match the name's meaning by shifting the burden of proof.

I will be editing the sprites to meet the concerns of those who want the visored sallet to clearly show it is covering the mouth. I will be doing so in a modular format to meet codes-in-socks' other request. But please take the time to consider that everything in the game with a historical name already resembles its historical parallel, from billhooks to lutes, so why should a very specific word for a style of helmet not be represented by that style of helmet?

**Pull request closed without merging**
