### PR TITLE
Pestra Nostink

### PR DESCRIPTION
**Pull request by Merek2**
## About The Pull Request

This gives all Pestra followers the NOSTINK trait like the Physician role. I know that would mean they get three traits but only one is really something that offers a advantage. This shouldn't do a lot. This is mostly because Pestran followers if they can eat rot would be able to handle stink.

### CODE REVIEW

**Comment by Stutternov** [comment]
This is just a further buff to choosing specific patrons while other followers have no traits at all. 

Go adding stuff to other patrons, not keep buffing one specific one further.

**Comment by Merek2** [comment]
I am more than willing to add more to a few things. This change is generally because the Pestran should be able to you know, be around people which they are expected to cure.

**Comment by faaaay** [comment]
I think it's more important for a feature change to be an improvement, or something that's needed, than to be done just because it fits. It seems to me like an unneeded buff to a patron that already gives a great perk (Rot Eater). The justification that "Pestrans should be able around the people they cure" doesn't quite convince me. Your patron doesn't just give you every ability you need to perform their bidding, especially if you just pray to them and aren't any form of clergy.

**Comment by faaaay** [comment]
> Sorry but being able to shove rotten food in your mouth but not be able to tolerate the mere scent of rot is fucking stupid

Okay, let's replace the rot eater perk, then.

**Pull request closed without merging**
