### PR TITLE
Normalizes skills/stats for male/female heirs

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

For some reason male heirs get flat out better stats/skills than female heirs. This PR adjusts their skills a bit and gives heirs the same skills/stat adjustments regardless of gender. Also fixes a bug that gave male heirs master sword skills - both genders now simply have journeyman sword skills instead.

Males/females both still spawn with unique outfits, but I did give females a proper belt with 3 slots as opposed to a cloth one.

## Why It's Good For The Game
De-chuddifying. Female heirs probably shouldn't just be objectively worse than male heirs.

### CODE REVIEW

**Comment by faaaay** [comment]
Glad to see this change!

**Comment by Kroto-Ker** [comment]
Would it be possible to throw in riding for heirs too? I feel like it'd be appropriate for them to be able to ride saiga, I have a friend who requested it.

**Comment by Wesreidau** [comment]
I prefer gender equality over gender equity in my medieval fantasy game. Maybe adding some subclasses so heirs can choose an archetype would be nice, and people could lean into a gender norm if they wished to or not in that way?

**Comment by faaaay** [comment]
> image

what did they mean by this

**Pull request closed without merging**
