### PR TITLE
Ruediger's Faithless Change: De-Redditization

### PR DESCRIPTION
**Pull request by Ruediger4**
## About The Pull Request

# First of all: Atheism is fucking stupid.

You can't be a fucking Atheist when people are literally getting their rotting corpses turned back into smooth baby skin. People's arteries mended by A FUCKING PRAYER.

So, here's your option, if you so insist:

### Being Faithless!
Yes-sir! Now you, YES, *YOU*, can experience the discrimination of believing in NO GOD at all in a Grimdark (patent pending) enviroment!

### BUT BE. FUCKING. WARNED.
Anything that is faith-related that should **AID YOU**, does not work.

I'll put it in big bold letters for people who can't bother to read a few lines.

# IF YOU ARE FAITHLESS, YOU CANNOT BE UNROTTEN, REVIVED, OR HEALED BY MIRACLES.

Stick to the bit. Don't be a coward. Go find a surgeon. Medicine as a skill is now relevant.

## Why It's Good For The Game

People have been wanting to be agnostic/faithless for a while, but Atheism is fucking silly. You can choose to not feel strong about it, and the Gods will, in turn, not feel strong about you. A challenge for some. Also, ***it'll make surgeons very fucking valuable, as well as health potions!*** Hooray!

### CODE REVIEW

**Comment by Ruediger4** [comment]
Heelp IDK why it queued up shit I already PR'd. I'm Dumb Babby.

Anyways leave feedback, comments, etc.

**Comment by Ruediger4** [comment]
Whoops forgot to make it able to be chosen as a FAITH, not just a patron.

**Comment by Ruediger4** [comment]
Okay, should ACTUALLY work now

**Comment by Ruediger4** [comment]
> them

A part of me wanted to make the whole HEH... REDDIT MOMENT jokes but honestly I was just mad at people simply wanting the Atheism thing back on w/o having any stakes.

You can make a character who has no strong ties to any God and therefore doesn't care but you better stick to science now.

**Comment by Ephemeralis** [comment]
I know you're leaning into a bit here, but you can save future feature devs like 5 seconds of work by renaming `TRAIT_SILLYPERSON` to `TRAIT_FAITHLESS` and pretty much immediately make large code blocks involving the functionality much more readable.

Excellent addition, though!

**Comment by Ruediger4** [comment]
> I know you're leaning into a bit here, but you can save future feature devs like 5 seconds of work by renaming `TRAIT_SILLYPERSON` to `TRAIT_FAITHLESS` and pretty much immediately make large code blocks involving the functionality much more readable.
> 
> 
> 
> Excellent addition, though!

Will keep it in mind! May edit it as soon as I get home for clarity's sake. I did it for yhe silly's, to be fair.

**Comment by Ruediger4** [comment]
# Properly renamed the trait from SILLYPERSON to FAITHLESS for future coders

**Pull request merged**
