### PR TITLE
More tiefling customization

### PR DESCRIPTION
**Pull request by josephpatrickgreen**
horns and a wagging tail ported from ratkeep

### CODE REVIEW

**Comment by josephpatrickgreen** [comment]
> tested this on a local ham? sometimes (not all the time) can cause issues when a direct port, just wanna double check ya took a look.

tested on local, the only thing that doesnt work is the edits to the dmi that include the original tiefling horns but i figured that would work on the server. when i swapped out the horns dmi with the new one, the new state didnt appear on my end. I dont know what the fuck is up with .dmi files.

**Comment by josephpatrickgreen** [comment]
this should be adequate now.

**Comment by SayonaraEcho** [comment]
When merge? :clueless:

**Comment by josephpatrickgreen** [comment]
> When merge? :clueless:

dont know.

**Pull request merged**
