### PR TITLE
Hand Nerf

### PR DESCRIPTION
**Pull request by ghost**
Pickpocketing Skill isn't good for hand to have.

## Why It's Good For The Game

Why is it good for the game? Pickpocketing is a retardedly broken skill. We don't need hands walking around disarming everyone. (Not that has currently happened). They're spy-master (At least what Vide claimed), not some fucking run of the mill rogue that can sneak and steal.

### CODE REVIEW

**Comment by EaglePhntm** [comment]
> > > Talked to host yesterday/day before, the mentioning lowering the sword skill so it's not the same as a knights at level 5 aka master.
> > > Might want to consider re-lowering that one as well given it was a buff to the class for whatever reason alongside the pickpocketing.
> > 
> > 
> > its expert already not master pretty sure, also the job description says its a supposed spymaster, whats a spymaster that himself cant spy and slip in some pockets when needed.
> 
> You can't pickpocket things onto people. That's just not possible. Don't add skills and don't mess with things you don't actually know how to use.
> 
> You're a coder. Look at the steal intent.

slip in some pockets mean by hand, you cant even read plain language to begin with lol.

**Comment by EaglePhntm** [comment]
> > > > > Talked to host yesterday/day before, the mentioning lowering the sword skill so it's not the same as a knights at level 5 aka master.
> > > > > Might want to consider re-lowering that one as well given it was a buff to the class for whatever reason alongside the pickpocketing.
> > > > 
> > > > 
> > > > its expert already not master pretty sure, also the job description says its a supposed spymaster, whats a spymaster that himself cant spy and slip in some pockets when needed.
> > > 
> > > 
> > > You can't pickpocket things onto people. That's just not possible. Don't add skills and don't mess with things you don't actually know how to use.
> > > You're a coder. Look at the steal intent.
> > 
> > 
> > slip in some pockets mean by hand, you cant even read plain language to begin with lol.
> 
> Pickpocket skill doesn't deal with that. Pickpocket still is used ONLY in the steal intent check.

do you REALLY not know how to read and come here making a pr?

**Comment by EaglePhntm** [comment]
> > > > > > > Talked to host yesterday/day before, the mentioning lowering the sword skill so it's not the same as a knights at level 5 aka master.
> > > > > > > Might want to consider re-lowering that one as well given it was a buff to the class for whatever reason alongside the pickpocketing.
> > > > > > 
> > > > > > 
> > > > > > its expert already not master pretty sure, also the job description says its a supposed spymaster, whats a spymaster that himself cant spy and slip in some pockets when needed.
> > > > > 
> > > > > 
> > > > > You can't pickpocket things onto people. That's just not possible. Don't add skills and don't mess with things you don't actually know how to use.
> > > > > You're a coder. Look at the steal intent.
> > > > 
> > > > 
> > > > slip in some pockets mean by hand, you cant even read plain language to begin with lol.
> > > 
> > > 
> > > Pickpocket skill doesn't deal with that. Pickpocket still is used ONLY in the steal intent check.
> > 
> > 
> > do you REALLY not know how to read and come here making a pr?
> 
> Brother, you added a two skills for no reason. Don't act like you're not the retard here when you shat all over the floor.
> 
> Sneaking was the only skill that was semi-justifiable. Pickpocketing isn't justifiable. Take your silly opinions and stances elsewhere.

Dude in alt account calls me silly lmao, whatever it doesnt matter if it gets merged or not either way, hand loses a utility that could have situationally became useful, not like hand would be going around pickpocketing with pickpocket 3 skill with 50%+ fail chance to be a thief plus, got name and role to risk, so i dont know why its even an issue to you except the fact me making the said PR, if you didnt have something to be butthurt about, surprised you went this far to get the git and make a pr, unless you are retaining something. Disarming? Be real.

**Comment by EaglePhntm** [comment]
training pickpocketing to max by checking the code sure sounds like the way of the powergamer. I know how the stuff work, pretty sure the advisor thing is mostly put on the hand role in contrary to what the job description says. Not like kings ever ask advice or listen, either way i think removal of the pickpocket skill will make hand a more plain asset with less utility.

**Comment by EaglePhntm** [comment]
You don't hear anything right far as I can tell.

**Comment by EaglePhntm** [comment]
> > You don't hear anything right far as I can tell.
> 
> Mods? Ban this guy from my comment section. I'm tired of his insane rambling.

i wasted my time trying to explain you something so simple it could be first grader math, but you are a just baiting at this point, i'm out of here.

**Comment by EaglePhntm** [comment]
Why would I, rogue is fine.

**Comment by Erwbrad** [comment]
can we get a vulpkian good sex boost if they have sex with humen

**Comment by EaglePhntm** [comment]
> > Why would I, rogue is fine.
> 
> Rogue is fine-ish. Pickpocketing is still busted.

pickpocketing is fine idk what gave you the fuckin trauma, maybe blackstone. You gotta be not just out of their sight but also win the roll to take anything, and its on the usual delay iirc.

**Comment by CVSthePharmacy** [comment]
This should be merged

**Pull request closed without merging**
