### PR TITLE
Mage's Apprentices can leave the tower 

### PR DESCRIPTION
**Pull request by faaaay**
## About The Pull Request

Currently, a specific door on the top floor of the tower requires the Magician's unique key, meaning that Apprentices are trapped if they spawn on the top floor despite their quarters being there.

## Why It's Good For The Game

you should be able to enter and exit your workplace

### CODE REVIEW

**Comment by faaaay** [comment]
Hey, 500k changes doesn't look right, Map formatting stuff from StrongDMM, I guess?

**Comment by Stutternov** [comment]
[ATTENTION, APPRENTICE HAS BREACHED CONTAINMENT!](https://youtu.be/xz0HvEVCziY?si=8cj4HJXOvgAIdavx)

**Comment by Tree445** [comment]
There was a map update, if you could add this change to the most recent mapchange.

**Comment by faaaay** [comment]
agh, i hate map conflicts

**Comment by faaaay** [comment]
THERE we go.

**Comment by faaaay** [comment]
> if you're doing map edits up there can you also add a functional light to the bedroom floor
> 
> mage apprentices are both trapped and can't see shit, it's not a very welcoming experience

also yeah i added a light on the wall

**Pull request merged**
