### PR TITLE
Implements mothers' milk; Eoran pies and cheeses

### PR DESCRIPTION
**Pull request by DerFlammenwerfer**
## About The Pull Request
Because some people cannot refrain from being disturbing little sweat goblins, and because others can't refrain from removing content to spite the afore-mentioned DLSGs, I have decided to code this as both a giant middle finger to both sides of the aisle, and a compromise for the people who actually roleplay responsibly.

Here's what this PR aims to accomplish:

- Make it easy to tell the difference between milk collected from a person, and milk collected from an actual animal.
- Define separate code paths for cheese made from the former, and cheese made from the latter, to prevent the former from being used for economic benefit to the detriment of roleplay.
- Add at least some basic lore reason that cheese made from mothers' milk would exist; ties in with Eora and the concept of either fertility rites or an indulgence between partners.
- Allow the creation of Eoran berry and apple pies using mothers' milk and salt, which are described as an indulgence between partners.

What this PR does **NOT** do:

- Alter any of the existing cooking recipes, except to restrict subtype crafting. This means you will need to find a female goat or cow, or buy milk from someone who has one if you want to cook non-Eoran food with butter or cheese.
- Attribute any economical value to the new reagent or anything made from it. If people want to spend coin on it, let it be a roleplay thing only.

## Why It's Good For The Game
This is the solution that still allows people to cook with it in a limited capacity, without allowing bad-faith players to use it as an avenue for violating consent. I even went a step further to make it so the mothers' milk reagent is distinctly named from the non-fetish animal product.

As an aside, I caught heat for suggesting this alternative solution after the individual who made a PR to remove the cooking content made a separate PR with a similar solution, **_and then of their own accord decided to close that PR anyway._** I get that you are tired of hearing about this argument, but obviously a not-insignificant number of people wanted this. Closing that PR was super petty and I'm so done with that BS. I see your executive decision, and I raise you mine. [Twirl on it.](https://media.istockphoto.com/id/140472118/photo/middle-finger.jpg?s=612x612&w=0&k=20&c=PHWkY3qathm5pjKIIJ5G2fggGxln0puxrdYlD6ly3Nc=)

### CODE REVIEW

**Comment by AysheDaArtist** [comment]
Imagine getting so heated you make lore to explain titty pies and not look at how fucked the playerbase has been baseline with it originally.

You do you man, I'm trying to keep this from being Medieval SPLURT.

**Comment by DerFlammenwerfer** [comment]
> Imagine getting so heated you make lore to explain titty pies and not look at how fucked the playerbase has been baseline with it originally.
> 
> You do you man, I'm trying to keep this from being Medieval SPLURT.

People being disturbing little sweat goblins with it is largely an administration issue, not a code issue. I really don't have a dog in the fight, but I think coders should stay in their own lane. By all means, fix unintended bugs for the sake of the in-game economy, and write changes that ensure the sanctity of consent, but it is not your duty or your place to **_police_** the playerbase.

**Comment by YuiY1997** [comment]
This is a really weird hill to die on

**Comment by Gardelin013** [comment]
Need

**Comment by SaintHusky** [comment]
> > Imagine getting so heated you make lore to explain titty pies and not look at how fucked the playerbase has been baseline with it originally.
> > You do you man, I'm trying to keep this from being Medieval SPLURT.
> 
> People being disturbing little sweat goblins with it is largely an administration issue, not a code issue. I really don't have a dog in the fight, but I think coders should stay in their own lane. By all means, fix unintended bugs for the sake of the in-game economy, and write changes that ensure the sanctity of consent, but it is not your duty or your place to **_police_** the playerbase.

This man is spitting facts.

**Comment by Feralape** [comment]
You're a savior

**Comment by Stutternov** [comment]
Admins have proven they are unwilling or unable to police this prior. Seeing within a day the amount of uncomfortable open display of lactation stuff in complete public and the tricking people into consuming kink related material.

This is why you shouldn't take PRs that are completely sexual in content for no other reason than giving someone their dopamine hit under the excuse 'admin have to police'. 

I didn't have time to see this but as is staff are undermanned and did not handle the multiple complaints they got last time. I don't trust players in any way to ever be tasteful with this, nor do I trust staff to ever police this like you think.

Shouldn't have been added in the first place.

**Comment by Wesreidau** [comment]
Merge it. It fixes the problem.

**Comment by stew9703** [comment]
Just kill lactation in general I dont want to have to handle other people's fetishes in IC situations like a chef only making lactate stew.

**Comment by faaaay** [comment]
While I personally think the mechanic should be disabled entirely until we have proper code _and_ administrative measures for it, this is a good way to compromise.

**Comment by Kroto-Ker** [comment]
isn't this a way to basically make your own food infinitely as well? regardless even with the ability to determine where milk comes from I think it'd still be relatively easy for people to consume breast milk products unknowingly. Only people who know of the issue will meticulously examine every piece of food they come across. Also this is just a niche fetish overall, I don't think it's worth all of this.

**Comment by Mannybrado** [comment]
The PR that makes breast milk unable to be used to make food is infinitely better than this. Keeps the fetish content without it being something that can be powergamed. It's a joke it's like this in the first place.

**Pull request closed without merging**
