### PR TITLE
Smithy changes electric boogaloo

### PR DESCRIPTION
**Pull request by codyman765**
## About The Pull Request
Changes the smithy in town once again, bringing it more in line with the prior smithy and removing the outdoor forging area, while adding in the past QOL update for the smiths back in along with shrinking the size a bit from the older bigger smithy that it used to be as well as a complete overhaul of the upstairs, however I did not change much about the roof dining area for the tavern.

Ground floor is very similar to the older version of the smithy most notably shrunk down and compressed to a better degree while still giving smiths room to work without issue and adding in long overdue working shutters for the smiths so they can lock the store down for the night when they need to eat and sleep, giving players a clear cue that no one is in at the moment. It starts closed and due to levers jank need to be briefly toggled once to sync the icon states.  Added in a lightly grassy cobble mix in the freed area since I saw people liked to set up stalls in the newly freed space on the current one and I figured this would be a good spot for them to set up. The line of dirt leading to the main door of the smithy offers no slowdown so it shouldn't affect people going straight into the smithy with ores and the such. Mason door is in the back
groundfloorfinal

Upper floor has a full revamp and redesign compared to the prior version of the smithy, better usage of the space, dinner and cooking area for the workers. Slightly shrunk one of the main smiths rooms to be the same size as each other, shrunk the storage area and most notably move the stairs for the masons higher up to clear a bigger area on the ground floor while still giving masons ease of access to the main floor of the smithy.
upstairs final

Roof is largely untouched, might come back in the future and revamp this for the tavern if there is an interest
roof

## Why It's Good For The Game
The current smithy we have, while looking very pretty is a very tight and cramped workspace for the four smiths to work in. I personally was having issues working in it when trying it and the feed back I was hearing from other smiths in that round and others prompted me to make this edit of the old version to try to pretty it up while keeping features smiths requested/had and lost in the new smithy, such as the extra smithy keys, the snack and the apprentice beds and one mason bed, and the sacks for moving ore and ingots easily.

Overall I do think the current smithy is very pretty but has alot to be desired functionality wise and for its tight quarters that cause traffic jams when the smith is populated, no to mention when a cart comes through with ore. The outside fence area is a very easy break in point, partly due to the fact that the anti thieving fence does not work on 2/3 of the sides. and with how tight it is in there, anything along the inside edge of the fence can be picked up by anyone who walks past on the outside. As well as allow people to throw things into the area and at the smiths while working.

I think the current smithy would do much better with a some small edits and a relocation to somewhere else on the outskirts for an townie smith or player to claim, maybe remove the furnaces and anvils to prompt players to claim the building as their own and work towards setting up their own smithy in time.

### CODE REVIEW

**Comment by burdwatcher** [comment]
As I told you on the side, I'd prefer if the current smithy was workshopped to be a bit wider to alleviate congestion concerns. I would much prefer if we're making towns that have buildings that aren't just blocky warehouse cubes with nothing in them like the current ground floor on this PR. It's more immersive if the buildings look like messy things thrown together without city planning or zoning making sure everything is a perfect grid, this looks more like a wal-mart than a medieval/fantasy smithy. But ultimately I don't play smith so I don't really care to vote either way.

**Comment by Sixzma** [comment]
> That is way too big for _potentially_ four people.
> 
> Also it turns us to the smithy line just spilling out into the street, which sucks.

This smith has been shrunk considerably compared to the original old smithy. And its for the FOUR apprentices and TWO masons. Besides this is an upgrade to the current smithy we have, considering the amount of complains the smith players had.

**Comment by codyman765** [comment]
> That is way too big for _potentially_ four people.
> 
> Also it turns us to the smithy line just spilling out into the street, which sucks.

So, went and did some quick counting to compare the two smithies, the current one takes up **145** tiles up on the ground floor, vs this version of it which takes **151**, and if you _dont_ count the stairs up to the 2nd level for the masons its **142** which on its own would be even smaller then the current smithy we have. but again _with_ the stairs its **151** so they are already _**very**_ close in size. 

As for the line thing most places with a que or a line tend to follow the building itself rather then go straight out from the building itself. Im not fully sure why the trend is for players to line up straight out from it. And as has already been pointed out by another already, four smithies and two masons for a total of 6 people potentially working in the dwarven quarter. It also might be worth trying to lean things away from it being called the smithy and just the dwarven quarter to be fair. Due to thats what its designated as via zones. But I also would like to point out the smithies can spend easily the first two hours in a round non stop working, the upper floor was made in mind of this to give workers a _space to RP_ and not have to go far from the smithy, and have the tools needed to keep their stats from falling due to sleep or hunger and thirst. I have seen far too many smiths just working non stop for hours and then falling over at the anvil due to just how ungodly tired their character is from working for most of the week straight.  

But could you be a bit more clear what area you think its too big?

**Comment by burdwatcher** [comment]
> > That is way too big for _potentially_ four people.
> > Also it turns us to the smithy line just spilling out into the street, which sucks.
> 
> So, went and did some quick counting to compare the two smithies, the current one takes up **145** tiles up on the ground floor, vs this version of it which takes **151**, and if you _dont_ count the stairs up to the 2nd level for the masons its **142** which on its own would be even smaller then the current smithy we have. but again _with_ the stairs its **151** so they are already _**very**_ close in size.
> 
> As for the line thing most places with a que or a line tend to follow the building itself rather then go straight out from the building itself. Im not fully sure why the trend is for players to line up straight out from it. And as has already been pointed out by another already, four smithies and two masons for a total of 6 people potentially working in the dwarven quarter. It also might be worth trying to lean things away from it being called the smithy and just the dwarven quarter to be fair. Due to thats what its designated as via zones. But I also would like to point out the smithies can spend easily the first two hours in a round non stop working, the upper floor was made in mind of this to give workers a _space to RP_ and not have to go far from the smithy, and have the tools needed to keep their stats from falling due to sleep or hunger and thirst. I have seen far too many smiths just working non stop for hours and then falling over at the anvil due to just how ungodly tired their character is from working for most of the week straight.
> 
> But could you be a bit more clear what area you think its too big?

I think the 3 wide counter is a mind trick that convinces people to line up leading away from the building. It's awkward for someone to stand next to you in a 3 wide counter area if you're in the center of it because it looks like they're just there with you for your order. No one is going to stand one space away from the person placing their order because this is ss13 and if you don't stand right next to someone in line it appears as if you're not in the line. Someone could stand at the end of either part of the 3 wide counter but it would just be awkward for laying things out on the table to hand over.

So people just queue up leading away from the building as it has none of these small problems that make people feel subconsciously uncomfortable.

**Comment by codyman765** [comment]
Alright, went in and shuffled some things around out of the growing concern about the line, slid the building back and created a kind of pocket for the counter to sit at, giving more room for the line.
Capture

**Comment by codyman765** [comment]
Quickly fixed a missing tile under the new back door for masons I had missed.

**Comment by codyman765** [comment]
Updated the smithy to be on the most current map as of today 9/1/2024 Also added in my minor roof/Tavern shared space idea I was playing with.
rooftop

**Comment by codyman765** [comment]
Updated to current map, removed shutters
shuttergone

**Pull request closed without merging**
