### PR TITLE
Racial stat obliteration beam [draft]

### PR DESCRIPTION
**Pull request by AllCorruptingWyrm**
## About The Pull Request

This PR obliterates the racials certain races gets for better and for worse as was intended. I have no idea if these were the exact numbers.

## Why It's Good For The Game

Why.

### CODE REVIEW

**Comment by Stutternov** [comment]
Those stats do nothing now. Racial bonus handles racial stats.

**Comment by AllCorruptingWyrm** [comment]
> Those stats do nothing now. Racial bonus handles racial stats. See the Statpack port PR.

People are apparently getting absurd amts of str on round start and getting debuffs on stuff from a convo on discord

**Comment by Stutternov** [comment]
> People are apparently getting absurd amts of str on round start and getting debuffs on stuff from a convo on discord

These aren't what's causing it. It's from the following:
- Statpack choices
- Job bonuses (I.e Royal guard gets +4 or +3 strength)
- And random rolling. I.e - you start with base 10 strength if no bonuses from stat or job. You will roll between 8-12 strength. So -2, -1, 0, 1, 2.
- (If wearing) Dragon ring

See here how that specstats are disabled from being assigned. It's a hold-over.
image

**Comment by AllCorruptingWyrm** [comment]
https://www.youtube.com/watch?v=4qgH0c4NThw

**Pull request closed without merging**
