### PR TITLE
Sus Cheese - Uncursed

### PR DESCRIPTION
**Pull request by AysheDaArtist**
## About The Pull Request
CHANGE: Changes lactation milk from breasts to give breastmilk rather than normal milk

## Why It's Good For The Game
This prevents the making of cheese/butter from players who could lactate and from being able to sell it or use it mechanically after they did so.

### CODE REVIEW

**Comment by Stutternov** [comment]
homelander-milk

**Comment by Gardelin013** [comment]
The tavern doesn't serve elf cheese anymore 😔

**Comment by Rin053** [comment]
Dark elf breastmilk, thanks to those who produce it having centuries of exposure to cave fungi and mold and the fazress, tastes a little more mushroomy than minty elven breastmilk. To any human who sample it, the result is a little more chalky, and ever so slightly tart/hot (way way those tiny cinammon heart Valentine's Day hard candies have heat), but to elves who sample dark elf breast milk, it taste sweeter than it seems to humens ( and far less minty than their own breast milk). Interestingly, to dwarves, both elven and dark elf breast milk taste a lot like (original, unsweetened) licorice.

**Comment by Gardelin013** [comment]
> Dark elf breastmilk, thanks to those who produce it having centuries of exposure to cave fungi and mold and the fazress, tastes a little more mushroomy than minty elven breastmilk. To any human who sample it, the result is a little more chalky, and ever so slightly tart/hot (way way those tiny cinammon heart Valentine's Day hard candies have heat), but to elves who sample dark elf breast milk, it taste sweeter than it seems to humens ( and far less minty than their own breast milk). Interestingly, to dwarves, both elven and dark elf breast milk taste a lot like (original, unsweetened) licorice.

Lies, dark elves produce the chokolate flavor

**Review by DerFlammenwerfer — CHANGES_REQUESTED** [review]
Allow the production of cheese with this, but define that cheese under a new recipe that sets the price value to 0.

For instance:
`/datum/crafting_recipe/roguetown/cooking/cheese/breastmilk
	name = "fresh cheese (breastmilk)" /datum/reagent/consumable/breastmilk
	reqs = list(
		/datum/reagent/consumable/breastmilk = 5,
		/obj/item/reagent_containers/powder/flour/salt = 1)
	result = list(/obj/item/reagent_containers/food/snacks/rogue/cheese,
				/obj/item/reagent_containers/food/snacks/rogue/cheese,
				/obj/item/reagent_containers/food/snacks/rogue/cheese)
	tools = list(/obj/item/reagent_containers/glass/bucket/wooden)
	sellprice = 0`

**Comment by DerFlammenwerfer** [comment]
> I don't see why this should be a thing at all. Yes we can argue about preferences or whatever but It felt rather forced fetish when it was requested by an admin and wasn't held up to a vote by the community.

It's not a huge loss, and I'm not pretending like it is. I just know some people like this feature and I'd rather not see it intentionally left out because including it might be some stain on the coder's ego. To quote, they didn't want to become known as 'the breastmilk guy'

**Comment by AysheDaArtist** [comment]
> Allow the production of cheese with this, but define that cheese under a new recipe that sets the price value to 0.
> 
> For instance: `/datum/crafting_recipe/roguetown/cooking/cheese/breastmilk name = "fresh cheese (breastmilk)" /datum/reagent/consumable/breastmilk reqs = list( /datum/reagent/consumable/breastmilk = 5, /obj/item/reagent_containers/powder/flour/salt = 1) result = list(/obj/item/reagent_containers/food/snacks/rogue/cheese, /obj/item/reagent_containers/food/snacks/rogue/cheese, /obj/item/reagent_containers/food/snacks/rogue/cheese) tools = list(/obj/item/reagent_containers/glass/bucket/wooden) sellprice = 0`

My dude...   https://github.com/Tree445/Hearthstone/pull/215

Stop, seriously, you're the Xth person to just come in on this "debate" and state the exact solution I've already provided while also being blasted for protecting this kink I don't even care for.  No matter how you slice it, walking into a kitchen with breast milk cheese on a table is going to be jarring, it should not be normalized, it should not be celebrated.

We expected people to be mature and adult about this and as usual they went in the most childish ways about it.  Selling their own tit milk to the Stockpile in the form of butter and cheese, and rather than do the work to get real milk, they just skip the middle man and make pies from their tits.

I don't see ANY RP from any parties here other than LRP bullshit and I don't want to deal with it anymore.  The majority of people going "But keep it!" for the sake of what, the few people who are okay with this while the rest make jokes and kink shame and are just offput by the strangeness of it?  I'm keeping in bottling milk for the sake of it and even that makes me feel uneasy since people can't easily identify it. 

This is all about CONSENT and ECONOMY STABILITY, the rest of whatever any of you think this is about ( Kink Shaming / Agenda / etc. ) is all in your head, **I SHOULD NOT HAVE HAD TO EVER BE PUT IN THIS POSITION IN THE FIRST PLACE**

Coders: Review. Your. Fucking. Code. and have some god damn insight, don't tell me you can code this but go "Oh, tee hee, I made it milk and not a separate milk that doesn't ruin the economy and not let people make tit pies and cheese to trick people into eating"

This PR exist to put a stop to this ridiculous debate, if you want to re-add the cheese, we can do so with a future PR, but enough is enough and I'm tired boss.

**Comment by DerFlammenwerfer** [comment]
> This PR exist to put a stop to this ridiculous debate, if you want to re-add the cheese, we can do so with a future PR, but enough is enough and I'm tired boss.

I do not think it should be impossible to tell between the two, and I do not think tricking people into indulging a kink through mechanics is okay. That is NOT the purpose of what I said. 

I'm all for ensuring the opportunity for consent, but the responsibility for dealing with situations where consent is violated through trickery is not and has never been **your** responsibility. That's on staff, who should be handing out day bans at the minimum for this kind of behavior.

**Comment by AysheDaArtist** [comment]
https://github.com/user-attachments/assets/2474f36d-f479-42e0-bf95-51d6a7e524bd

**Pull request merged**
