### PR TITLE
Renamable Saigas

### PR DESCRIPTION
**Pull request by EtheoBoxxman**
## About The Pull Request
What if you could name a saiga you personally saddle, send tweet

## Why It's Good For The Game
Personalization for mounts. What's there not to love?
And what better way to motivate someone than to give them something to lose?

### CODE REVIEW

**Comment by Onutsio** [comment]
Im Bog the Frog and this is my favorite pr on the gitadel

**Comment by Tree445** [comment]
Is this tested and does it work? I feel like lots of naming related PRs seem to have issues.

**Comment by EtheoBoxxman** [comment]
> Is this tested and does it work? I feel like lots of naming related PRs seem to have issues.

I tested it, yes!
Currently, Saiga are the only creatures that can be saddled this way.
Unless this changes, the name change can only happen once per saiga, as well. 
I see no code for removing saddles, either. One and done per saiga, and the name change applies only to the targetted saiga's name.

**Comment by EtheoBoxxman** [comment]
Also went and replaced the local saigas with unsaddled saigas, and placed 5 saddles in a chest in the basement, similarly to how the farm's saigas are provided.

image
image

**Pull request merged**
