### PR TITLE
Warlock & Artificer

### PR DESCRIPTION
**Pull request by josephpatrickgreen**
## About This PR
This PR adds the warlock class and an artificer trait to the game. The artificer trait is not added to any class (which means it is safe to add to the game). Artificer trait allows for slap crafting of items and gems to produce different resulting enchanted items.

Potential candidates of the artificer include:
-tribal smith
-smith
-a new towner class "artificer" based out of the masons
-a new mage subclass "artificer" who does not learn magic
-a new class "artificer"
Do NOT give any keep or church roles an artificer. They already have the greatest ability of all: "kill anyone for any reason without repercussion" and do not need further enhancement.

## About The Warlock
Warlocks are individuals who have formed a pact with an otherworldly entity, gaining supernatural powers in exchange for their faith or other significant sacrifice. Their powers are derived from sources beyond mortal understanding and are often associated with dark magic and forbidden knowledge.

Warlocks have traded their faith for power, thus are faithless. They also all start with eldritch blast.

Please note the **bold** features are new additions that are explained at the bottom.

## Otherworldly Patron (Subclasses)
Warlocks choose 1 of 8 patrons on game start:

### **archfey** (face/caster)
-Grants most seelie spells
-give **wild magic** trait (not yet implemented)

### **celestial** (healer)
-give **eldritch healing**

### **fathomless** (jack of all trades)
-dodge expert trait
-medium armor trait
-water breathing trait

### **fiend** (combat caster)
-no fire trait
-**kiss of the fiend** trait

### **genie** (face)
-**signet ring**
-rich pouch
-magic lamp (just flavor)
-dodge expert trait

### **great old one** (utility caster)
-you gain the learn magic tab

### **hexblade** (melee)
-dodge expert trait
-medium armor trait
-**pact weapon**

### **undead** (tank)
-medium armor trait
-heavy armor trait
-no stink trait
-infestation spell
-**cloak of flies** spell

## Boon (what did you trade your faith for?)
This is another round start choice (if the warlock feels underpowered after testing, give them 2)

### **strength**
-**pact weapon** 
+1 strength

### **knowledge**
-**patron grimoire** added to hands
+1 intelligence

### **love**
-give **soulbond ring**
-goodlover trait

### **power**
-trade eldritch blast for **empowered eldritch blast**

### **health**
-give **eldritch healing**
+2 athletics

### **wealth**
-rich pouch
-give **eldritch talisman**

### **purpose**
-**constellation chain** added to wrist

### **friendship**
**Find Familiar** spell

## Wild Magic
5% chance for spells to do something random

## Kiss of the Fiend
when you cast certain projectile spells, hurl a firebolt in the same direction a half second later.

## Signet Ring
While worn you have the noble trait

## Pact Weapon
datum added to a weapon
-1.2x stats
-named
-given "singing item"
-non-owner wielders are burned periodically
-can be right-clicked by owner to turn into different weapon
-uses arcane skill rather than the weapon skill
-can invoke with mmb to prompt a poll for ghosts to possess it

## Singing Item
datum added to an item
-random personality: compassionate, bloodthirsty, righteous, manipulative, paranoid, singing
-talks when attacking, wielded or dropped

## Cloak of Flies
A toggleable spell which creates a cloud of flies that deals damage over time to inhalers

## Patron Grimoire
A spellbook which when held in hands or placed on hip gives you access to 3 random cantrips and message

## Soulbond Ring
a ring which when worn by another mob, soul links you, this mob will have a heart attack after 30 seconds if you die.

## Empowered Eldritch Blast
Eldritch blast with one square knockback that has a longer cd and more damage

## Eldritch Healing
A faithless version of lesser miracle

## Eldritch Talisman
a talisman which, while worn gives you more fortune

## Constellation Chain
A chain which, while worn (on wrist) gives you nightvision)
double the force of a regular chain so it may be used as a blunt instrument

## Find Familiar
A spell that polls ghosts in an attempt to create a hell goblin, skeleton, shade or boglobster, after use, this spell deletes itself from your known spells

## About The Artificer
Artificer is not a class but a trait. A player with this trait has the ability to slap craft items on to gems for unique enchantments on the item called **Infusions**. This process consumes the gem. The infusions depend on the item type used during crafting. This process changes the item name to [item name] of [infusion name]. 

## Giver Infusions
**Headwear Infusions:**
awareness- give perfect tracking trait
water breathing- give water breathing trait
disguise- give disguise self spell (wip)
intellect- +2 intelligence
telepathy- give encode thoughts
defense- if armor worse than kettle helm, set to kettle helm armor values

**Mask Infusions**
night- give night vision
defense- if armor worse than iron mask, set to iron mask armor values

**Armor Infusions**
propulsion- increase walking speed by 1.1x
magical strength- cant be pushed, +1 strength 
tools- activate to get a hammer, pickaxe, axe, lockpick (wip)
fire resistance- no fire trait

**Robe Infusions**
mind sharpening- +2 int

**Cloak Infusions**
protection- mage armor spell (wip)
the bat- bat polymorph spell

**Belt Infusions**
giant strength- +2 strength

**Bracers Infusions**
archery- +2 bows, +2 crossbows

**Gloves Infusions**
thievery- +2 lockpick, +2 stealing
ogre power- +1 con, +1 str
missile snaring- dodge missile trait
swimming and climbing- +2 swimming +2 climbing

**Boots Infusions**
the winding path- misty step spell (wip)
striding and springing- leaper trait
the spider- web walk trait and +2 climbing
wings- fly spell (wip)
levitation- tbd

**Ring Infusions**
spell-refueling- spell that refreshes all spells (long cooldown) (wip)
jumping- z-jump trait
mind shielding- no detect trait
protection- mage armor (wip)
free action- bog trekking (basically what it does, dumb name)
the ram- charger trait

**Neck Infusions**
thoughts- encode thoughts spell
adaptation- no stink trait
wound closure- eldritch healing (any) spell
health- +2 con

**Weapon Infusions**
radiance- weapon glows like a torch
returning- weapon returns when thrown

**Staff Infusions**
arcyne focus- +1 arcane skill

**Shield Infusions**
repulsion- 5% chance to create a repulsion wave on block (wip)

**Instrument Infusions**	
haunting- while players, move things around, play spooky whispers, flicker the lights.
the sewers- gain summon rous spell, tame rous, when you play it rodents and snakes follow you

**Rope/Chain Infusions**
climbing- +3 climbing

## Change Infusions

**Bottle Infusions**
alchemy- **alchemy jug**

**Pouch Infusions**
holding- **bag of holding**

**Stone Infusions**
sending- create paired **sending stones**, activate one to send a message to the other

**Light Infusions**
revealing- double light 

**Eye Infusions**
charming- charm person spell (wip)
the eagle- +3 perception (wip)

**Gem Infusions**
scrying- just turn into a scrying orb.

**Signal Horn Infusions**
blasting- **horn of blasting** massive repulsion wave when used. 10% chance to cause an explosion. (wip)

## TO DO:
-make the infusions have tiers depending on the gem used
-give artificer trait to some class

### CODE REVIEW

**Comment by Elli-Skala** [comment]
It's a requirement to be faithless but some of this I feel like could also fit well with inhuman worship

**Comment by josephpatrickgreen** [comment]
> It's a requirement to be faithless but some of this I feel like could also fit well with inhuman worship

It's not a requirement to pick the class but it does force you to be on spawn. The faithless instead of inhumen was an attempt to make them not immediately valid to anyone who suspects you of being a warlock.

**Comment by RikaruZW1** [comment]
bro why has apple not merged and updated this yet what the fu-

**Comment by josephpatrickgreen** [comment]
> bro why has apple not merged and updated this yet what the fu-

Squeaky wheel gets the grease. Make some noise then.

**Comment by RikaruZW1** [comment]
> > bro why has apple not merged and updated this yet what the fu-
> 
> Squeaky wheel gets the grease. Make some noise then. Speaking of which... I have to make that grease spell.

Would but last time I pestered Apple about updating he did kinda threaten to mute me on discord at one point, so I'm a little wary about poking too hard.

**Comment by josephpatrickgreen** [comment]
> > > bro why has apple not merged and updated this yet what the fu-
> > 
> > 
> > Squeaky wheel gets the grease. Make some noise then. Speaking of which... I have to make that grease spell.
> 
> Would but last time I pestered Apple about updating he did kinda threaten to mute me on discord at one point, so I'm a little wary about poking too hard.

Eh I dunno, it should be in eventually. The code itself is cool as fuck.

**Pull request merged**
