### PR TITLE
Fertility toggle for genitals, alongside updating code ingame to check for it.

### PR DESCRIPTION
**Pull request by kyowaaaa**
## About The Pull Request

- [x] Update vaginas and testicles to have related fertility/virility variables across all files
- [x] Ensure organs are properly initalized with defaulting to being fertile/virile
- [x] Ensure all different testicle objects properly inherit virility values (Should be done, need to confirm)
- [x] Update customizer code for both organs to allow player preference for toggles
- [x] Bring vagina related code in customizer to a standardized level to allow same customizations (customizer_entry/organ/vagina needs created and related code adjusted for it)
- [x] Add check for impreg related code (sexcon.dm) to check for fertilty and virility for catching and pitching players.
- [x] Test and ensure nothing explodes horribly across multiple cases since I'm touching a ton of files

## Why It's Good For The Game
Player comfort for people who do not want to see/be involved in pregnancy/impregnation related play with consequences (as of right now, a single line saying you're pretty sure you're pregnant. This could of course change). Builds a baseline to allow anyone who wishes to develop more ERP related code to said preferences without causing issues for these players. Also brings standardization to the code for a few things to allow future customization options.
Discussed in #development-chat with @GarDelin in relation to ERP system updates. I don't ERP so I'm doing a lot of code diving. Request of an unmentioned friend as well.

### CODE REVIEW

**Comment by kyowaaaa** [comment]
Coding this stains my soul. Let me know if there's any other content requests/requirements. Going to be slow going since I'm going back to my work week in a few hours.

**Comment by coffeecoffeecoffee** [comment]
You're doing god's work, but I'm about to make that stain so, so much worse - what about some kind of mechanic that optionally allows for people to make their partner's belly size mechanically bigger from cumming inside them, even if just by 1 stage per... session, depending on their virility?

**Comment by kyowaaaa** [comment]
> You're doing god's work, but I'm about to make that stain so, so much worse - what about some kind of mechanic that optionally allows for people to make their partner's belly size mechanically bigger from cumming inside them, even if just by 1 stage per... session, depending on their virility?
I'mma not touch that yet due to my belief that others want to do pregnancy/belly related stuff akin to that. I appreciate you encouraging my work though, haha!

**Comment by Tree445** [comment]
> > You're doing god's work, but I'm about to make that stain so, so much worse - what about some kind of mechanic that optionally allows for people to make their partner's belly size mechanically bigger from cumming inside them, even if just by 1 stage per... session, depending on their virility?
> 
> I'mma not touch that yet due to my belief that others want to do pregnancy/belly related stuff akin to that. I appreciate you encouraging my work though, haha!

I do not believe anyone is currently working on that. Though the belly sprites have been added in for character customization prior to starting your round.

**Comment by kyowaaaa** [comment]
Apologies for my absence and most likely presumptive comments earlier. Sudden house repairs are making it difficult to focus in on this. Will ensure any other code that touches this during my somewhat slower progress has conflicts fixed. Going to avoid scope creeping this given my slower progress right now; thank you all for your patience.

**Comment by kyowaaaa** [comment]
Okay, I'm basically done beyond making sure doing the deed works/doesn't work properly, and ensuring nothing in the customizer broke. I'm going to wait until I'm fresh after work tomorrow and walk entirely down a checklist.

**Comment by kyowaaaa** [comment]
https://imgbox.com/XjST7bRN 
https://imgbox.com/Abct3rGG
https://imgbox.com/13Pr1tgQ
https://imgbox.com/PyTdsn5u
Customizer choices for fertility/sterility work, including with child organs (internal testes)
Basic check done on the impregnation with helper verbs (/mob/living/carbon/human/proc/is_fertile() and is_sterile)
Vagina code is updated to a standardized point, will be easier to customize in the future if we ever need it for some reason.
Characters passing the check with the added helper verbs still get the impreg blurb. Otherwise, it can't happen.
Nothing seems to have broke horribly and I've spent since I got home from work testing it. Requesting someone to look over changes before merging if at all possible.

**Pull request merged**
