### PR TITLE
+2 slots to satchel

### PR DESCRIPTION
**Pull request by EaglePhntm**
## About The Pull Request
Increases satchel slots by 2

## Why It's Good For The Game
Should help with the choke of having little space for most.

### CODE REVIEW

**Comment by Tree445** [comment]
Double it a lot. Especially when you consider that you can have 2 satchels. And backpacks do the same job while giving you a LOT more slots, at the cost of having to take it off to withdraw.

**Comment by Ruediger4** [comment]
I think you can still have quite a lot of inventory by mixing belts, pouches and satchels, all w/o being a weird storage creep/loot goblin.

You want more? Get a handcart going!

Satchels are VERY powerful in that you can just pull shit outta it by standing still for a single sec and 2 clicks, usually things that dont fit in belts or pouches, so doubling it just like that "for the working class" is ???

Working class can get handcarts going!
I've seen some bog guards/mercs/templars get handcarts to move their gear around too

**Comment by Wesreidau** [comment]
I'd agree with one or possibly two slots, but three seems like the big ask. I do, however, keep running into 'I need one more slot' problems. Four or five slots is enough for a barebones surgical kit, which I really would like to see in something other than the giant backpack.

**Comment by EaglePhntm** [comment]
guess i'll just expand satchel to maybe 5 and leave backpack alone

**Pull request merged**
