### PR TITLE
Viking update map changes and armor

### PR DESCRIPTION
**Pull request by WWWWW-Git**
This is a major update for the Viking faction which puts them more in line with what we currently have in terms of lore. Vikings get new armor, which isn't craftable but each one spawns with a set and there are spares left in the room they spawn in. The Viking king gets his own unique set of stronger armor, as well as a unique sword. The Viking area as well as combat music has been updated as well. To balance the faction somewhat, I have removed the great smelter they spawn with and replaced it with a normal smelter. This pushes the Vikings to actively go out in search of a ROS if they want to more readily get steel equipment. I also removed the spells that the Vikings spawn with, which seemed somewhat random. And finally, the ability to recruit players as 'Graggarite Thralls' has been given to the Viking king. Currently this should function the same as the king's ability to make normal citizens into watchmen or how tribals can recruit new members. Please let me know if any of that is in any way broken.

The new armors being added are as follows: Elven Barbute, Elven Winged Barbute, Grenzelhoft Knight Helmet, Iron Harness, Iron Chestplate, Iron Couters, Striped Pants, Plain Pants, Fancy Brigandine, Fancy Cuirass and finally the Noble Cuirass. All these items can be acquired by smithing except for the Striped Pants and Plain Pants which can be acquired via sewing. It is also worth pointing out the Grenzelhoft Knight Hemet's feathers can be recolored in the same way the plume of the Footman Helmet and the detail of the Grenzelhoft Hat can be recolored.

### CODE REVIEW

**Comment by Moribun** [comment]
I see this as "I kitted up the faction I like to pvp better" updates like this, forced enthralling? your pulling ratwood shit. Graggarite Thralls yes lets give someone the abbility to be a vampire antag without being a vampire antag.

**Comment by faaaay** [comment]
> I see this as "I kitted up the faction I like to pvp better" updates like this, forced enthralling? your pulling ratwood shit. Graggarite Thralls yes lets give someone the abbility to be a vampire antag without being a vampire antag.

It's not that kind of thralling, it's just a recruitment ability for declaring that someone is now a thrall (i.e. servant).

**Comment by Stutternov** [comment]
The graggarite weapon is cracked strong btw. 50 damage modified by strength.

**Comment by Elli-Skala** [comment]
I still don't see what purpose the vikings fulfill that bandits didn't already outside of ease to spawn

**Comment by Tree445** [comment]
> > I still don't see what purpose the vikings fulfill that bandits didn't already outside of ease to spawn
> 
> Vikings were randomly added. People voted for more antag roles and instead of making bandits their own fleshed out faction Apple decided to add Vikings instead without really telling anyone or making it fit with any pre-established lore.

I already coded viking by the time I threw up the vote, but I was asked to make a vote before adding them, so I did.



> I still don't see what purpose the vikings fulfill that bandits didn't already outside of ease to spawn

That's essentially the point, though vikings are a theme that we've been playing with on this server since it was first made. We had a lot of viking events, but never any playable vikings.

**Pull request closed without merging**
