### PR TITLE
Mechanic - Tracking

### PR DESCRIPTION
**Pull request by DeltaFire15**
## About The Pull Request
This PR adds tracking as a mechanic, aswell as an associated skill.
Moving around (on the ground) may at times leave behind tracks, which remain hidden until noticed by a keen-eyed tracker.
Currently, this applies to dirt / grass (low chance), aswell as mud (fairly high chance).

Tracks last for about fifteen minutes, becoming more and more difficult to spot the more time passes.
Spotting Tracks is governed by Perception and Skill, albeit spotting a track does not always convey all information present within, instead being split into ranges of success, with Skill mattering more than Perception for analysis itself.
Successfully spotting a track that is not your own will increase your tracking skill.

Note that spotting tracks reveals them **only** to you.

Leaving tracks is controlled by the type of turf for its base chance (currently only the turfs mentioned above, feel free to provide input), additionally modified by sneaking (lowers chance, impacted by sneak skill), running (increases chance, not impacted by skills), and by wearing armor (may increase chance depending on total torso encumbrance).

When aware of a track, examining it will provide the information you were able to gain from it, while clicking it with an empty hand will conceal the track, removing it.

(There are also potentially some further interactions I could think of, but for now this should be enough to gauge the concept).

Some classes have gained this skill, namely:

- Dwarf Ranger & Ranger - 2
- Hunter - 2
- Assassin - 2
- Mercs - 1
- Bog Guard - 1
- Bogmaster - 2
- Witchhunter (rare class) - 4
- Bandit - 1
- Tribal Guard - 2
- Monster Hunter (Warrior subclass) - 3
- Sentinel (elven Ranger) - 2
- Village Elder - 2

Werewolves also have a new trait related to this mechanic, making them always successful at locating tracks, while also always receiving full information from them, at least while in wolf form.

If you can think of other classes that would be adept at tracking, do tell, these are only the most obvious to me.

Track sprite is kind of bad, but hey at least it's a reference.

Also fixes a random compile warning in the lux file.

## Why It's Good For The Game
Some neat environmental storytelling. Any ground-bound being may leave tracks, which might tip people off about odd happenings or where someone may have been heading.
Could also be used for events, albeit may require some knowledge to configure.

### CODE REVIEW

**Comment by Elli-Skala** [comment]
> If you can think of other classes that would be adept at tracking, do tell, these are only the most obvious to me.
only one I can think of is maybe matthios bandits due to them prowling the terror bog

**Comment by DeltaFire15** [comment]
> I love this PR, but do you expect any performance impact from this?

Good question! Tracks once they exist themselves should be fairly negligible performance-wise (since the only thing they do unless interacted with is a single timer for their expiry.
Creation is a bit more complicated, since its check hooks into move(), which is called fairly often. It doesn't do any big loops however, and should also be relatively negligible. If it isn't, there's probably some microoptimizations to be done (like splitting the prob() calls into one before the bonus modifiers.

**Comment by Ephemeralis** [comment]
Looks great!

Would be wonderful to have signals added for tracks - such as when creating them and when consuming them. There's a lot we can do with this from a gameplay pov I think and signals will make it a *lot* easier.

**Comment by DeltaFire15** [comment]
> Would be wonderful to have signals added for tracks - such as when creating them and when consuming them. There's a lot we can do with this from a gameplay pov I think and signals will make it a _lot_ easier.

Sure, signals can be useful for a lot of things, but I feel like anyone that knows how to write COMSIG using things also knows how to make something send one in the way they need it to.
So, I'll leave that to them, as opposed to adding unneccessary (if minor) load to having a bunch of `SEND_SIGNAL`s
Unless it's something you want, like, right now.

**Comment by Ephemeralis** [comment]
I can think of a spell or three that could meaningfully interface with this, but you're right - it's not a huge deal to just add the signal stuff when needed.

**Comment by faaaay** [comment]
Sentinel (rare elf-exclusive ranger class) and Village Elder might be fitting for a couple points of Tracking.

**Pull request merged**
