### PR TITLE
Cantrips Fixes

### PR DESCRIPTION
**Pull request by josephpatrickgreen**
Additions:
-Mind Sliver cantrip and scroll
-Poison Spray cantrip and scroll
-Primal Savagery cantrip and scroll
-Ray of Frost cantrip and scroll
-Poison Bite trait for primal savagery

Changes:
-increased various cooldowns
-bonfire now uses campfire basetype
-encode thoughts and guidance are now a targeted spells
-spellscrolls updated to new spell obj types

Fixes:
-fixed invoked abilities to check for only mobs
-mending works now
-frostbite now slows
-light now works
-magic stone works now

### CODE REVIEW

**Comment by josephpatrickgreen** [comment]
> magic stone is broke too

fixed

**Comment by josephpatrickgreen** [comment]
Another fix in, forgot to push.

**Comment by josephpatrickgreen** [comment]
> acid splash also needs a fix. other than that checks.

what's wrong with acid splash? it has the same cd as spitfire

**Comment by Tree445** [comment]
> > > acid splash also needs a fix. other than that checks.
> > 
> > 
> > what's wrong with acid splash? it has the same cd as spitfire
> 
> didnt work when I tested it.

It works. It's an AOE on where-ever it explodes.

**Pull request merged**
