### PR TITLE
Adds new patron blessings

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

This PR adds new passive blessings for Ravox, Abyssor, Noc, Astrata, and Xylix.

Blessing of Abyssor - You cannot drown.
Blessing of Ravox - Your body can go longer without eating/drinking. Nutrition drain from walking/running is halved.
Blessing of Noc - +1 fortune buff at night.
Blessing of Astrata - +1 fortune buff during the day.
Blessing of Xylix - Access to a secret language known as Trickster's Tongue. To most others, it sounds like gibberish.
Blessing of Malum - Damage taken from being on fire is halved.

## Why It's Good For The Game

Currently Dendor, Necra, Pestra, Eora, Graggar, Matthios, and Boatha are the only deities that give blessings to their followers - this adds a few more blessings for patron deities that currently lack blessings.

I missed Psydon and Zizo - but I'll probably make another PR and add something for those two some other time. This covers the /majority/ of patrons, at least.

### CODE REVIEW

**Comment by DeltaFire15** [comment]
Malum: Perhaps either sleeping on rock (/ stone) flooring (natural primarily) like if it were a bad quality bed (or slightly below), or the Astrata / Noc luck bonus except only active while you are underground.

**Comment by Disheveled-arch** [comment]
Blessing of Ravox threatens to make growing food roughly half as important.  BIG Adventurer buff, Big Towner/soilson/farmer nerf.  IMO

**Comment by Disheveled-arch** [comment]
> > Blessing of Ravox threatens to make growing food roughly half as important. BIG Adventurer buff, Big Towner/soilson/farmer nerf. IMO - Not good for food economy.
> 
> Soilsons regularly make several thousand mammon just selling apples/grain to the stockpile every round. I really don't think they're gonna be significantly impacted by certain players having to eat less often.

There is already a problem with people choosing Adventuring over Town oriented roles because of the high access of skills and increased stats that Adventurers get.  This to illustrate that people DO make decisions about their character creation specifically to do with what is easier to play the game.  Using this observation, I believe that there will be a not-insignificant shift towards Ravox for the passive.  This will depress the NEED for food, and eventually the production of food will go down due to the lack of demand, causing further detriment to folk across the board who aren't Ravox followers.  I imagine this will likely be a fair number of the Adventurers that contribute to the adventurer bloat that I hear about PR's trying to fix.  People gravitate towards the path of least resistance. I think the passive is too good.  

And yes while food is available in the stockpile, no one gives a shit about it enough to Regularly cook the more elaborate meals, to feed the town with these elaborate meals or food items, giving reasons to populate the communal food areas. Doing this will reduce the frequency that more niche food items are cooked, causing their sprites to sorta be wasted space.  Remove Cheesemaker, Cut out anything that isn't Copiette, Apples, Crab Meat, raisins, toast or hearth cooked fish.  We already have a passive that circumnavigates food in a way, AND WE OFFSET THE BENEFIT BY MAKING THE FOLLOWERS 'EVIL'/Social Pariahs.  

I believe the Ravox Passive is a bad change.  It will shift the meta further in a direction you won't want it to go.   This IS a nerf to specialist towner Classes, and towners in general, as well as a HUGE BUFF to the folks who play 'Path of least resistance' characters (Adventurers), don't get it twisted.

**Comment by Disheveled-arch** [comment]
> > I believe that there will be a not-insignificant shift towards Ravox for the passive.
> 
> I really don't agree with you. If you're the type of person to just powergame, Dendor's passive blessing is still like objectively the strongest and most useful for combat and has been for a while - and yet we don't see dozens of people playing Dendor just for the passive.
>
Hey man, people don't agree on things all the time!  It's all good!  Firstly I don't think all powergamer's are created equal.  And the existence of an (arguably) more powerful Passive does not mitigate the changes we are talking about in whole (though maybe in minute part) since when considering HRP non-combat passive benefits, Between Graggar and Ravox, Ravox is now firmly and well beyond Graggar, and will argue till I am blue in the face, that is is likely better than Dendors (but this is fine, because they aren't effecting the balance of the same things). 

> > I believe the Ravox Passive is a bad change. It will shift the meta further in a direction you won't want it to go. This IS a nerf to specialist towner Classes, and towners in general, as well as a HUGE BUFF to the folks who play 'Path of least resistance' characters (Adventurers), don't get it twisted.
> 
> I think considering this a "nerf" to towner classes is pretty bonkers. Some players needing to eat less often does not affect towner classes anywhere near as much as you think; especially considering it's piss easy to get food without ever interacting with towners at all. Towners are not and have not ever been required for food and this PR isn't gonna change that.

I am not convinced of this yet, sorry.

> > Doing this will reduce the frequency that more niche food items are cooked, causing their sprites to sorta be wasted space. Remove Cheesemaker, Cut out anything that isn't Copiette, Apples, Crab Meat, raisins, toast or hearth cooked fish.
> 
> This comment reads as completely nonsensical rambling; you're suggesting removing half of the food in the game because some players might not be hungry as often. Take a step back and chill out, brother.

I am not saying that we remove them NOW, I am saying that I think eventually this will cause a lack of usage of the more niche food articles that I think don't get much play today. 

However fair, it read nonsensical/hyperbolic to illustrate a point and that doesn't jive with some folks.


----

Any response to the fact that Graggites already have a passive that circumnavigates ANY crafted meal while RP wise ostracizing them, and Ravox passive is flat better when compared?  
Just have to eat a handful of apples over the span of two weeks and be square? Apples are already so cheap and plentiful in the stockpile I've heard, and anyone can grow them, not just the farmers.

**Comment by Disheveled-arch** [comment]
> > Malum: Perhaps either sleeping on rock (/ stone) flooring (natural primarily) like if it were a bad quality bed (or slightly below), or the Astrata / Noc luck bonus except only active while you are underground.
> 
> Cool ideas! I wanted to make them take reduced fire damage but unfortunately couldn't get it working properly. There's existing code for a fireproof trait, but being completely fireproof would've been stupid overpowered. I'll definitely come back to Malum/Psydon/Zizo with something eventually in another PR though.
> 
> I also want to eventually add new miracles for deities who are lacking cleric content as well; maybe I'll add those last few blessings along with that PR! I've got some pretty fun ideas drafted up for Malum clerics.

Ah cool!  Finally!  I made some suggestions on the suggestion page for Malum!  I am so happy someone is finally looking into this!

**Comment by Disheveled-arch** [comment]
> Like I said in the post above, the numbers can be adjusted pretty easily if Ravox's reduced nutrition drain is a bit overtuned, but I don't think reduced nutrition drain is fundamentally a bad idea or circumvents eating entirely.

Alright that is a fair point, it can be fiddled with on the back end if things turn out fucky.  That one just worries me is all.

**Comment by Wesreidau** [comment]
Pestra needs that 'iron nose' trait where you don't throw up from miasma.

**Comment by Ephemeralis** [comment]
Astrata is already a wildly popular choice for a variety of reasons - I'm not sure the +1 fortune buff during the time period where people are most likely to be out and benefitting from it is really a good idea. I'd recommend making this more conditional like requiring someone to be in openspace w/ no roof (aka must be able to see the sun) during the day - same deal with Noc, too. Honestly, you can probably skip giving these two trait bonuses.

Abyssor is good!

Ravox is a bit much, to be honest. It's a subtle-but-serious kind of addition that I think overly gamifies the choice. I'm not really sure what to replace it with though - maybe something like a change to the Strong intent that increases the bonus strength to +2 maybe in exchange for the Weak intent not taking effect? Probably not a good idea either.

Xylix is also good! For extra shenanigans, I'd suggest adding the bonus language to Matthios as well.

Malum is where I'd suggest that a +1 to fortune while indoors buff comes into play, especially given the role fortune plays in crafting overall.

**Pull request closed without merging**
