### PR TITLE
Rebalances times so that they are better distributed

### PR DESCRIPTION
**Pull request by Multigamer99**
## About The Pull Request

Changelog
 - Day and Night now take up 8 hours each instead of 4 and 16 respectively
 - Dawn and dusk now take up 4 hours each instead of 2
 - Night->Dawn is now at 4:00
 - Dawn->Day is now at 8:00
 - Day->Dusk is now at 14:00
 - Dusk->Night is now at 18:00
 - Fixes a runtime error involving testing for something within mind while on the character creation menu that i found along the way.

## Why It's Good For The Game

Requested by many players (and a bug fix on the last point)

### CODE REVIEW

**Comment by AysheDaArtist** [comment]
Yes Please!

Days are very quick especially for RP focused moments.  Having longer nights can also help antags play out situations and get out before daylight.

**Comment by WoodenTucker** [comment]
kind of a debuff to vamps

**Comment by WoodenTucker** [comment]
> > kind of a debuff to vamps
> 
> Major debuff to v-lord.

so does author intend to address that or is it is just supposed to be a debuff

**Comment by Multigamer99** [comment]
Yeah it's unintentional as a debuff to vamp lord. I mainly did this because one of the admins had been trying to get someone to make this change for a while.

also if vamp lord doesn't have disguise the same way that lesser vampires do imma be so disappointed since they should have disguise tbh, after all the lesser ones have it!

**Comment by Multigamer99** [comment]
As for addressing it, I'm not fully sure what the best approach would be. I know antags as a whole are in a weird state right now though.

**Comment by Mannybrado** [comment]
vamp lord still doesn't have disguise, yeah

**Comment by Multigamer99** [comment]
Changelog:
- Grants disguise to vampire lords
- Fixes the code that assumed vampire lords couldn't have disguises

Known bugs (that I will fix later assuming I remember to):
- Vampires don't burn in daylight until the time of day changes at least once after they are spawned

**Pull request merged**
