### PR TITLE
Wood to Coal and Crafting Menu Optimize

### PR DESCRIPTION
**Pull request by Drayco84**
Alright, I screwed up and merged both of these into one instead of making them separate. Go me... Anyway...

Adds two new alchemy recipes: 3 sticks into 1 coal and 1 small log into 2 coal.
Rearranges the crafting menu to be more efficient to use, updates a few recipes, and standardizes item entries.

## About The Pull Request

- Adds an alchemy that converts 3 sticks into 1 coal, and ~~1 small log into 2 coal~~ _**one small log into a single coal**_ so alchemists don't need to set up a furnace to convert logs into coal.
- Rearranges the crafting menu to be more efficient for players to use.
- The four types of bait no longer need tables to craft. (This never made any sense to me.) Now hunters can be wandering the bog and resupply bait without needing to look for a table.
- Wooden spoons now make three items per craft, the same number as wooden bowls made per craft.
- Wooden trays are now also three per craft.
- Adds a meal set craft to just directly make a tray, mug, bowl, and spoon.
- Bone spears and axes now require a stone instead of a staff or log, respectively.

## Why It's Good For The Game

Alchemists will have less prep work since they can just convert sticks and small logs directly into coal, and even get skill xp for it!
The crafting menu was an oddly arranged mess and honestly, it still kinda is but hopefully people will be able to find things more easily now and the craft items that require the oddest combination of materials (Like the book making kit and papyrus crafts.) are now higher on the list so when the specific crafting materials are around, it's easier to find and craft.

### CODE REVIEW

**Comment by Drayco84** [comment]
Who do I need to pester to get this added before more crafts show up?

**Comment by SarahUDot** [comment]
**This is a non-maintainer's feedback, take it with a grain of salt:**
- I'd equalize small log to coal with furnace, since it's strictly more efficient to do alchemy than do the manual labor of turning logs to coal with your PR.
- You could probably sort the crafting menu using a listsort (or some func. that exists) based on an options verb that lets the player choose between alphabetical, unsorted and arbitrary usefulness.
- Odd numbers on spoons, bowls and trays is annoying, but no a bad thing imo. It gives incentive to make more if you want sets and can feel more realistic.

I don't have any heavy opinion on the rest, but I hope you like the feedback.

**Comment by Drayco84** [comment]
Alright, updated.

- Small log to coal changed to yield only one coal to retain production parity with a furnace. I kinda wanted to reward players for dragging around a small log instead of a bundle of ten sticks as you get 3 sticks for chopping up a small log. However, I'm not overly attached to the Sticks 2 Coal alchemy and that can be dropped if it's OP.
- If I knew how to use listsort or some similar function, I would do so and assign item types to each individual item as that WOULD be easier and far more future-proof. Unfortunately, I don't know how to code that.
- I understand, but a small log makes three bowls while only making two spoons. I thought spoons were smaller than bowls, so it just didn't make logical sense to me given that you're working with the same amount of material. The trays I changed because I might as well go for parity with all of those items, and the full set for a small log is so somebody doesn't need to gather a ton of logs to make some mess sets and can make only one or two if needed.

Well, anybody else have any feedback? I really would like to get this merged before more crafting items are added and I don't want to "move on" to another pull request as that would lead to overwhelming myself. (Damn you, ADHD.) And if somebody is taking their time to review this thing to make sure I didn't put something in that wasn't documented, well or otherwise... I really can't blame them. I tried to be a lot better about that this time.

**Comment by Drayco84** [comment]
This pull request has been remade and split into it's component changes, I didn't know how to merge/resolve conflicts with the new updates, so I just remade them. Thus, this is now redundant and need to be removed from the merge list.

**Pull request closed without merging**
