### PR TITLE
Second Amendment

### PR DESCRIPTION
**Pull request by WWWWW-Git**
This update makes firearms more accessible, but NOT easier to get. Desert Rider now has two archetypes, a melee one and a ranged one, with the ranged one spawning with a rifle and an ammo pouch with ten bullets. The ONLY way to currently obtain more guns other than going Desert Rider is via the merchant. A gun on its own costs 600 mammons to acquire from the merchant, ammo pouches which contain ten bullets each can be acquired also, 300 mammons for 3 pouches and thus 30 bullets. There is also a cheaper alternative of 150 mammons for 5 individual bullets. Thus far what guns there are have not been shown to be very OP, and as such I feel comfortable adding them in a wider space. Also added is a new skill 'firearms', which the Desert Rider ranged archetype spawns with 3 levels in.

Other than that, other additions are mainly that of some new clothes, jewelry and a craftable banner people can hold, with multiple different heraldry designs to choose from.

### CODE REVIEW

**Comment by Tree445** [comment]
I feel like there needs to be an entirely different subclass to receive the firearms. I'm not sure how fitting it is to give the desert mercs rifles. I have been meaning to add in pirates for a while.

**Comment by Stutternov** [comment]
I don't think anyone class should start with a firearm, given it's basically the best ranged weapon in the game. It opens Pandora's box to start adding more and more muskets to other classes.

It should be a rare dungeon find or expensive order. Not round start option.

**Comment by faaaay** [comment]
Personally, I don't think making guns more normalised rather than some mystical foreign trinket is good for the setting or fits its tone.

**Comment by faaaay** [comment]
> They still are foreign trinkets you literally cannot acquire it unless you're desert rider or buy one

They're still way more obtainable, going from something that's only found at the end of the dungeon to a thing you can just buy or bring with you. They're no longer... Unique. Keeping them rare adds a certain mystique, having characters come in already wielding them makes them more normalised.

**Comment by DorfGuy1** [comment]
> > I don't think anyone class should start with a firearm, given it's basically the best ranged weapon in the game. It opens Pandora's box to start adding more and more muskets to other classes till the entire niche of muskets is just bog standard. (Thus why I didn't do musketeer royal guard type on consideration.)
> > The argument of 'rarity is a moot point because crossbow' is offset by the musket being a flat-out armor ignore, allowing max severity wounds because it will ALWAYS do 50 damage. While a crossbow only has 50 AP, meaning it will never always do 70 damage unless hitting unarmored targets. Skill on ranged weapons effects **nothing** but your reload/draw (aim) time. Thus why literally anyone can use a crossbow but only at 4-5 skill do you suddenly notice your draw time is enough to use it reliably verses shoot and stab.
> > It should be a rare dungeon find or expensive order. Not round start option.
> 
> A fair amount of this can be solved by simply reducing the armor pen to something more reasonable. The arquebus could bonk through mail and our various flavors of medium armor within both reason and range, but wasn't infallible and certainly couldn't deal with heavier armor. An armor pen of, idk, eighty is more appropriate and less egregious from a game design point; a spicy, high import weapon that still plays by the same rules of the game.
> 
> ps rename the musket to arquebus

This is the way forward. Early guns were countered by some heavy armor. Maybe make the projectile stick in someone more often like an arrow, but decrease the armor pen by a lot and the damage by some.

**Pull request closed without merging**
