### PR TITLE
Nsfw headshots

### PR DESCRIPTION
**Pull request by EaglePhntm**
## About The Pull Request
- Adds NSFW Headshot option with 'Be Snowflake' option under defiant which will work similiar to defiant. NSFW Headshot has its own button under view headshot when examining people. ***This does not replace regular headshots***

- Fixes belly being too high on dwarf races, oddly didnt matter for normal races that i put the belly to belt offset, although no matter what i do slightest change to layering breaks everything for some reason.

### CODE REVIEW

**Comment by CVSthePharmacy** [comment]
pejis adn vabima

**Comment by coffeecoffeecoffee** [comment]
finally, a way to goon it till i 'gurt while i play Hearthstone

**Comment by glitchbow** [comment]
Considering the garbage I've seen on this server, people will still manage to "Be Snowflake" and put a NSFW headshot as the main headshot and won't change even if this gets added. I really wish character quality moderation was better.

**Comment by EaglePhntm** [comment]
> Considering the garbage I've seen on this server, people will still manage to "Be Snowflake" and put a NSFW headshot as the main headshot and won't change even if this gets added. I really wish character quality moderation was better.

havent seen such myself, F

**Pull request closed without merging**
