### PR TITLE
Port - Lethalstone Statpacks

### PR DESCRIPTION
**Pull request by Stutternov**
## About The Pull Request

Ports over Lethalstone Statpacks https://github.com/LethalStation/LETHALSTONE/pull/4 and redoes racial stats to be balanced around this system. I will label them all below, as well as what Statpacks you can choose from.

Basically - your species gives you a VERY small positive bonus stat (or positive and negative depending on how strong the stat is that it gives you) instead of a whole line of stats. Also, gender-based stat assign has gone away as well. Instead you now choose your statpack, as shown below, that chooses what sort of bonuses you will get with tradeoffs included.

image

**Furry Races:**
- **Akula** - 1 Endurance
- **Wild-Kin** - 1 Perception
- **Vermin-Folk** - 1 Speed, -1 Intelligence 
- **Half-Kin** - 1 Perception
- **Drakian** - 1 Strength, -1 Endurance
- **Kobold** - 1 Speed, -1 Constitution
- **Sissean** - 1 Constitution
- **Lupian** - 1 Intelligence
- **Moths** - 1 Speed, -1 Intelligence
- **Vulps** - 1 Intelligence
- **Tabaxi** - 1 Speed, -1 Intelligence

**Base Races:**
- **Dwarfs** - 1 Constitution
- **Dark Elves** - 1 Perception
- **Elves** - 1 Speed, -1 Constitution
- **Goblins** - 1 Speed, -1 Intelligence
- **Humens** - 1 Intelligence
- **Aasimar** - 1 Strength, -1 Perception
- **Half-Orc** - 1 Strength, -1 Intelligence
- **Tiefling** - 1 Intelligence 

And now, onto the **Statpacks!**
Agile types, for rogues/rangers/thugs
- **Swift**; -1 Strength, -1 Perception, -1 Constitution, 1 Endurance, 2 Speed
- **Hardy**; -1 Strength, 2 Constitution, 1 Endurance, -1 Speed
- **Tricky**; -1 Strength, 1 Perception, -1 Endurance, 1 speed, 1 or -1 Fortune
- **Thuggish**; 2 Strength, 1 Perception, -1 Intelligence, -1 Speed
- **Wary**; -1 Strength, 2 Perception, 1 Intelligence, 1 Constitution, -1 Speed

Mental types, for wizards/the religious/templars
- **Studious**; -1 Strength, 1 Perception, 2 Intelligence, -1 Endurance 
- **Resolute**; -2 Perception, 1 Intelligence, 1 Constitution, 1 Endurance
- **Zealous**; 1 Strength, -1 Perception, 1 Intelligence, 1 Endurance, -1 Speed
- **Foresighted**; -1 Strength, 2 Perception, 1 Intelligence, -1 Endurance
- **Adept**; -1 Strength, 1 Perception, 1 Intelligence, -1 Constitution, 1 Speed

Physical types, for farmers, warriors, and fighters
- **Trained**; 1 Strength, -1 Perception, -1 Intelligence, 1 Constitution, 1 Endurance
- **Muscular**; 2 Strength, -1 Perception, -2 Intelligence, 1 Constitution, -1 Speed
- **Alert**; 1 Strength, 1 Perception, 1 Intelligence, -1 Constitution, -1 Endurance 
- **Taut**; 1 Strength, -1 Perception, -1 Intelligence, -2 Constitution, 1 Speed
- **Toil-Hardened**; -1 Perception, -1 Intelligence, 1 Constitution, 2 Endurance

And the _wildcard_ section; mostly for challenge-mode or 'meme' builds.
- **Wretched**; -2 Strength, -2 Perception, -2 Intelligence, -2 Constitution, -2 Endurance, -2 Speed, 3 Fortune
- **Fated**; Random chance of 1 or -1 in every skill
- **Frail**; -4 Strength, -4 Perception, -4 Intelligence, -4 Constitution, -4 Endurance, -4 Speed, -4 Fortune (For if you hate yourself)

## Why It's Good For The Game

I've been asked for this a ton, and I disliked myself how species were balanced and how hard it was, due to this, to make species feel different without underpowering them or overpowering them.

This makes it more like a proper DnD-esc game, with choosing a sort of stat-type rather than than your _gender_ handling stats atop of a weirdly heavy focus on race; which I do get, and do understand it helps them feel different - but imo stuff should be done like racial perks to make them feel different rather than stats alone in the future. (I.e - dietary restrictions, etc.)

**NOTE:** I tested this PR to make sure it _works_, balancing may be needed as time goes or on suggestion. I have _not_ tested how these stats mold with current jobs which still give stat bonuses or ages which still give bonuses/penalties depending on your in-game character age.

### CODE REVIEW

**Comment by Hemlock32** [comment]
Tabaxi aren't listed in the list for stats.

**Comment by Stutternov** [comment]
> Tabaxi aren't listed in the list for stats on the PR?

Fixed, missed them in description. They are in files-changed though.

**Comment by Stutternov** [comment]
> Two things; minor aesthetic, I'd say calling it something like nature would make sense, but details.
> 
> Second, and actually; one thing I found very tedious with the system is that you have to more or less select each one in turn. Could you perhaps make the Statpack button clickable, and it just vomits a full stat read out into chat? Spammy, but it's lobby so oh well.

I actually wanted to maybe call it backgrounds and rework it a bit just name/desc wise, but I could swap it to nature. Waiting for staff feedback as well since one said they may have input; though not a bad idea.

As for the second, the way it works currently is on selecting it tells you that statpacks stats to your chat. Spitting them all out would flood the box pretty badly due to font size; I think it works OK for the moment as you'd just click through; given you probably wouldn't want to use a good few anyway.

**Comment by Ephemeralis** [comment]
Delighted to see this ported here too!

burger's suggestion of 'Nature' instead of 'Statpack' is a good thematic change I think. Otherwise, these adjustments all look great.

**Pull request merged**
