### PR TITLE
Matthios Reflavor - No more 'Comrade' Anachronism, Small Lore Adjustment

### PR DESCRIPTION
**Pull request by Wesreidau**
## About The Pull Request

This PR slightly changes flavor text for Matthios and the associated Bandit antag, removing 'comrade' and redistributionist language and shifting to a more setting-appropriate tone of civilized versus uncivilized raiders.

Individual changes are specifically noted in commits by title.

The changes bend toward a book in-game which I wrote, a poem called 'The Gift of Matthios', which framed Matthios as having given fire to Man to produce of men slaves to warmth, comfort, fire and industry; slaves which the Free-Men later plunder from. It can be thought of as a hunter lying in wait near a bait. This theme was drawn from a round of bandit I played where I wondered what sort of deity Matthios was, and produced a poem to litter about as a threat when I got that role.

The only principle lore change beyond shifting language slightly away from 'comrade' and 'redistribution' is the notion Matthios stole fire from Astrata, as opposed to the nebulous underworld. This sets Matthios' theft and chaos as the direct antithesis of Astrata's flame and order. Theft of fire granted the mortal thief Matthios divinity (or he plundered such from Astrata while in the heavens), but his purpose was not to make things better for men, but to make those weaklings who huddled around the campfires prey to the free-men who did not need the Gift at all; his worshippers.

## Why It's Good For The Game

The flavor text being shifted from 'comrade' to something that invokes a deeper lore, no longer 'AI-slop' as I hear it called, is an important step to developing the lore within the game world itself.

### CODE REVIEW

**Comment by Stutternov** [comment]
Matthios is a Narco saint.... you cannot gentrify him.....

**Comment by Wesreidau** [comment]
### Concerns So Far

>Comrade can mean to be, one in close companion.

I am familiar with the use of the word comrade in German, English and Russian. German 'Kamerad', in this time period, would at most refer to a fellow Grenzelhoft mercenary as it meant fellow-soldier. 'Comrade' in English would not be used until a socialist magazine in 1884. 'Tovarisch' was the Soviet adaptation of 'fellow-traveler', another communist idea based on the notion of two people travelling a road together, a common practice.

In either case, 'Comrade' as an English word draws its use from modern political contexts and in no way reflects an idea of a fellow revolutionary in a peasant revolt from 1000-1500 AD.

>Mathois is the shitty communist meme due to Peasant rebel.

Because it is a shitty communist meme we should probably change it. I am proposing such a change. This change can also allow Peasant Rebellion to change its tone as well. Matthios worshippers will always know fellow Matthios worshippers and so the rebel leaders will have the ability to spot early converts from fellow thieves and outcasts.

Any Bandits will also spot Matthios worshippers and know them as potential allies, and there exists a possibility bandits and revolutionaries (whom we might rename to Free-Men) start using the identifying trait to coordinate.

>Matthios is a Narco saint.... you cannot gentrify him.....

This is the opposite of gentrification. Matthios is becoming solidly the god of men who refuse to bow to kings, walls, rules, taxes, wealth, tithes and laws. This is doing so by adding all manner of frontiersmen, wanderers and vagabonds to his worshippers and opening up a direction for roleplay beyond out of place communist memes.

### Post-Scriptum

Looking into the 'Peasant rebel' aspect some opportunities open for future development, which is out-of-scope and in no way required to go forward with the proposed changes...

_However, while it is not my current intention to overhaul the Revolutionary game mode in any way, and certainly without a serious discussion first, some code exists to force Matthios worship for revolutionary leaders and a more extensive discussion could be had to make revolutions into Matthios cults, not as a 'cult' game-mode, but as a spread of Matthios worship and its trait of identifying fellow worshippers as a replacement to the Red Rev Icon. This makes dealing with antag rev rounds a matter of rounding up and torturing confessions of Matthios worship out of people, and if we add some code to the confession paper system, de-converting them back to their original deity or allowing them to pick an orthodox patron and mechanically locking them out of apostasy unless their confession is burned. This also places the Church against the antag revolution since it is a spread of heresy, and gives the Inquisitor a very important job to hunt down Matthios worshippers while producing a way to de-rev them and not force killing and round-removing them. As the Dungeoneer lacks confession papers, Church/Crown conflict still arises with how to handle captured revolutionaries._

**Comment by coffeecoffeecoffee** [comment]
My concern is how heavily this rips directly from the story of Prometheus.

**Comment by coffeecoffeecoffee** [comment]
> > My concern is how heavily this rips directly from the story of Prometheus.
> 
> Great media is stolen from good media.

There is a difference between "strong inspiration" and "straight up ripped from".

**Comment by coffeecoffeecoffee** [comment]
> > > > My concern is how heavily this rips directly from the story of Prometheus.
> > > 
> > > 
> > > Great media is stolen from good media.
> > 
> > 
> > There is a difference between "strong inspiration" and "straight up ripped from".
> 
> There's alot of straight ripped ideas that no-one really focuses on. Psydon was a direct rip from Lifeweb's PC bullshit.

Psydon was direct ripped from a server many people have never even played on, which is long gone. This Matthios shit is straight up a classical tale renamed in a cringeworthy and lazy move, lazier even than AI slop, which is at least _original._ It's not _hard_ to do better than AI, just put in something that takes an old concept like Prometheus and changes it _at least a fucking little._ This is just recolored OC tier.

Important to note I don't at all mind the comrade or redistribution of wealth removal, that was pretty bad too. Just keep working on the lore before making it _this,_ or just fucking name him Prometheus if you're going to go with this.

**Comment by Stutternov** [comment]
> This is the opposite of gentrification. 

the-simpsons-gentrification

**Comment by Wesreidau** [comment]
... I am surprised nobody knows the Matthios lore already includes Matthios stealing fire to give to humanity.

All I did is change it from stealing from the underworld to stealing from Astrata.

**Comment by coffeecoffeecoffee** [comment]
Wow. And I mean wow. Where does it say that? That's fucking... Awful, and don't I have egg on my face now.

**Comment by Wesreidau** [comment]
> Wow. And I mean wow. Where does it say that? That's fucking... Awful, and don't I have egg on my face now.

The Matthios idol description that you look at when you play bandit. 

Anyhow, the lore isn't 'new', but it is being expanded upon and slightly tweaked. Part of the 'new' lore is a book I wrote and put into the library. I'll go ahead and drop it here, so you know where I'm going with all of this. Apologies for not including it earlier.

> ### The Gift of Matthios
> 
> Darkness comes before light. This truth is plain for all with eyes,
> And for those without, the truth is lost in darkness. Without light,
> No mortal mind can comprehend the world, its wonders or horrors,
> And those in blindness know only the heat of flame or cold of winter.
> 
> In the vastness of uncivilized wildlands, one learns the truth of fire.
> It is not a gift from Matthios, stolen for the good of mankind.
> It is a curse, carefully graced with the glimmer of enticing embers,
> Forever luring the unwary closer before darkness takes them.
> 
> To understand, place your mind in the forest. Dark and forboding,
> Its ancient boughs spread above you as a sky against the sky.
> No moonlight filters through its dewy leaves, no sun can burn away
> the chill and ghost-wrapping fog that dwells beneath.
> 
> The scent of fire reaches your nose. The flicker of golden, hearth-warm
> Flames touch your eye. From miles it can be sensed by this mortal coil,
> Craving to know its cheerful heat upon a smiling face. Yet it is a lure.
> It has ever been a lure. Matthios did not lay out this trap unwisely.
> 
> Flame matters not where it is kindled, it shall always draw to it souls.
> Kindling to fuel, fuel to roast flesh, feasts to wooden halls, iron to hew
> More wood, stone to raise the ramparts higher; ever on the fire hungers.
> Ever on the bait reeks headier of wealth, wine, and women.
> 
> Matthios has laid this trap on behalf of his worshippers.
> The free men who have no need of flame.
> The free men who will suffer no chain.
> The free men watching distant fires.
> 
> In darkness we cannot be seen as we draw nigh.
> Through darkness we will cut the sleeping throat.
> Into darkness we will bear away our ransack.
> Within darkness shall endure our blind rapine.
> 
> All that glitters is not gold, and all made by flame is fleeting.
> Die not for the soulless stones you heap between flame and night.
> Resist the fire, you men who wish to be free.
> Return to the darkness, or be ransomed to it.

So as you can see, Matthios is developed differently from Prometheus. This is a (oh God I just realized this and it horrifies me) subversion of the Prometheus myth. Rather than be a titan who steals fire from the gods on behalf of humans and is punished by the gods for it, Matthios is a man who steals fire from the gods and attains deification for it. However giving said fire to humanity was not to improve humanity, but create slaves of those called to the lure of fire. Matthios has found a way to hunt men with fire as a bait. Matthios' worshipers are "Free-Men", those who do not need fire, or walls, or cities, but who dwell in the forests and plunder riches from those Matthios' 'Gift' has enslaved to comfort and the illusion of safety.

Its all very 'Dark Forest' Fermi paradox, for those of a science fiction mindset.

I hope that assuages concerns this is just a Prometheus rehash; it was before this PR, but now its got some more depth to it, cuts away the non-fantasy 19th century elements and goes solidly in a different direction.

**Comment by bearrrrrrrr** [comment]
said in discord but i like dis pr

would like it more if it was modular SCREECH

+1

**Pull request merged**
