### PR TITLE
Towner Skills Rebalance Pass

### PR DESCRIPTION
**Pull request by LynxSolstice**
## About The Pull Request

THIS PR IS INTENDED TO MAKE TOWNERS FAR BETTER THAN ADVENTURERS IN THEIR RESPECTIVE SPECIALIZATIONS.

## Why It's Good For The Game

0 towners with 30 adventurers, shows a severe systemic issue of powercreep, this should hopefully be a step in the right direction.

### CODE REVIEW

**Comment by EaglePhntm** [comment]
funny guy tried to **sneak an adventurer limiter.**

**Comment by coffeecoffeecoffee** [comment]
Stealth changes fucking bad.

**Comment by LynxSolstice** [comment]
I was talking about it actively in Development on the Discord and forgot to include it, it's not a stealth change, don't worry.

**Comment by faaaay** [comment]
On one hand, I worry about Towner power creep. On the other hand... yes please, Towners need this to be appealing.

**Comment by Tree445** [comment]
My face when people start killing themselves and getting revived to get their metafriends to get more adventurer slots.

On a serious note. I don't think limiting adventurer is a good thing for now.

**Comment by DerFlammenwerfer** [comment]
Yeah no, don't try to sandbag a slot limitation with an improvement to towner/pilgrim roles. If you want to make sweeping changes, you do them one category at a time in separate PRs.

**Comment by LynxSolstice** [comment]
> My face when people start killing themselves and getting revived to get their metafriends to get more adventurer slots.
> 
> On a serious note. I don't think limiting adventurer is a good thing for now.

Alright, I'll axe the adventurer changes for now, maybe open a different PR for it down the road or something

**Comment by LynxSolstice** [comment]
Done

**Pull request merged**
