### PR TITLE
Unisex Character Creator port

### PR DESCRIPTION
**Pull request by Tree445**
+Comment out randomization when swapping body types

### CODE REVIEW

**Comment by Ephemeralis** [comment]
Happy to see this ported!

One thing I forgot to add and never got around to: THROAT should have something for gender-neutral royalty, such as king/queen. "Sovereign" is probably a safe bet if you don't want to get too far into the weeds.

**Comment by Tree445** [comment]
Right. I didnt think of that. How do F_titles get handled with this?

**Comment by Tree445** [comment]
> Happy to see this ported!
> 
> One thing I forgot to add and never got around to: THROAT should have something for gender-neutral royalty, such as king/queen (the King/Queen Speaks etc). "Sovereign" is probably a safe bet if you don't want to get too far into the weeds.

Right. I didnt think of that. How do F_titles get handled with this?

**Comment by Ephemeralis** [comment]
> > Happy to see this ported!
> > One thing I forgot to add and never got around to: THROAT should have something for gender-neutral royalty, such as king/queen (the King/Queen Speaks etc). "Sovereign" is probably a safe bet if you don't want to get too far into the weeds.
> 
> Right. I didnt think of that. How do F_titles get handled with this?

They don't, I think. Another oversight. The game will default to body type over selected pronouns when setting titles.

**Comment by Tree445** [comment]
> > > Happy to see this ported!
> > > One thing I forgot to add and never got around to: THROAT should have something for gender-neutral royalty, such as king/queen (the King/Queen Speaks etc). "Sovereign" is probably a safe bet if you don't want to get too far into the weeds.
> > 
> > 
> > Right. I didnt think of that. How do F_titles get handled with this?
> 
> They don't, I think. Another oversight. The game will default to body type over selected pronouns when setting titles.

Might be a good idea to add a variable that controls F_title separately from bodytype. Could likely even just slap it onto Pronouns instead, with a default to masculine titles for it/is and they/them

**Comment by Tree445** [comment]
This also makes me wonder about classes/roles that change stats based on gender, which can be explained away with body types, but f_title would solely have to be separate for the sake of pronouns.

**Comment by faaaay** [comment]
Blessed PR, but do racial stats default to pronouns or body type? I assume the latter.

**Comment by Ephemeralis** [comment]
> Blessed PR, but do racial stats default to pronouns or body type? I assume the latter.

They default to body type.

This change was accompanied by a statpack PR on my fork that removed the racial body type differences and instead allows players to choose an equivalent set of bonuses from prebuilt packs. It's a bit awkward without it for these reasons.

**Comment by faaaay** [comment]
> > Blessed PR, but do racial stats default to pronouns or body type? I assume the latter.
> 
> They default to body type.
> 
> This change was accompanied by a statpack PR on my fork that removed the racial body type differences and instead allows players to choose an equivalent set of bonuses from prebuilt packs. It's a bit awkward without it for these reasons.
> 
> For example: [LethalStation#4](https://github.com/LethalStation/LETHALSTONE/pull/4)

I'll look at porting this.

**Pull request merged**
