### PR TITLE
Sus Milk Cheese & Butter

### PR DESCRIPTION
**Pull request by AysheDaArtist**
## About The Pull Request
ADD: Adds in Breastmilk Cheese ( and their aged variants ), Adds in Breastmilk butter
CHANGE: Milk from breasts is changed to Breastmilk

## Why It's Good For The Game
Lactation was setup to give milk... this was a terrible oversight as it is crashing the economy, causing awkward moments, and overall being abused.  This PR changes it so lactated milk is considered breastmilk and that can be still be used to make breastmilk cheese, and breastmilk butter, however, these breastmilk variants cannot be sold or used in cooking.  Breastmilk cheese can still be used as bait, and can be consumed akin to food, same as the butter.

This keeps it from still being RP for others while not breaking the economy and tricking people into eating sus cheese/butter
(I can't do anything about the liquid milk, you gotta RP that out my wayward son )

### CODE REVIEW

**Comment by Wesreidau** [comment]
... use 'Curious Cheese' and 'Curious Butter'. I feel dirty having even posted here.

**Comment by AysheDaArtist** [comment]
Yea I'd like to not even have to do this PR flat out, and here we are

It's dead ass breastmilk cheese, I don't want people mixing it up
"what's so curious about it"

Yea, no, this is the compromise, or it gets removed.

**Comment by AysheDaArtist** [comment]
> honestly I think referencing it as such makes it weirder as opposed to peace of mind
> 
> that said you can just... spawn goats, I am not sure it's particularly economically breaking?

People are making their own tit cheese and selling it to the stockpile, they are absolutely breaking the economy and tricking people into eating tit cheese/butter is vile

**Comment by AysheDaArtist** [comment]
gonna make the executive decision here and just say "No"

**Comment by AysheDaArtist** [comment]
Going to make the executive decision here and say "No"

**Comment by coffeecoffeecoffee** [comment]
yeah i'm ngl I'm VERY happy that it is creating actual ingredients and stuff FOR the people who like that fetish but it shouldn't be mechanically and economically viable items, just edibles/drinkables for fun
I appreciate this as it essentially kills them as powergame items

**Pull request closed without merging**
